### ISSUE TITLE
toolbar show exception

### ISSUE THREAD

**Issue by luochengyang** [HeidiSQL/HeidiSQL#1968] opened 2024-06-21 05:23 UTC
**Preconditions**

* HeidiSQL version:
* Database type and version:
* OS:win10
**Describe the bug**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/4494831/e5c932d8-209b-4464-bf4a-76fbb6d6eac8)

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2024-06-21 05:26
Can you please post a screen where I can see the height of the button, like when you hold the mouse over the button?

**Comment by ansgarbecker** [comment] 2024-06-21 05:27
Duplicate of #1967

**Closed by ansgarbecker** 2024-06-21 05:27 UTC
Labels: bug
