### ISSUE TITLE
Display bug when connecting to a second database

### ISSUE THREAD

**Issue by webdbase** [HeidiSQL/HeidiSQL#2002] opened 2024-08-08 16:46 UTC
### What where you trying to do?
Connect to a second database and see all its tables in the tree.

### What actually happened?
Connected to a second database. The tables tree is not correctly displayed. The newly connected DB is not visible. One needs to collapse the tree of the first database and scroll down to see the other tables.

### What did you expect to happen?
Connect to another database and see all tables in the tree.

https://github.com/user-attachments/assets/df9c49d2-f02b-4183-9e58-1b551fdc7117

### HeidiSQL version

12.8.0.6911

### Database server version

-

### Reproduction recipe

Go to File => Connect
Click on some database name
See error message: Partial tree or none with tables from the newly connected database is visible.

**Comment by ansgarbecker** [comment] 2024-08-11 12:33
I cannot reproduce here what you show in your video.
Please post details about your setup:
* your Windows version
* theme/style used in HeidiSQL (Preferences > General > Style theme)

**Comment by webdbase** [comment] 2024-08-13 07:16
Microsoft Windows [Version 10.0.19045.4651]
Preferences > General > Style theme is Windows

**Comment by ansgarbecker** [comment] 2024-08-13 09:21
Ok thanks for the info. There must be some setting you are using differently than me, as I am still not able to reproduce that. Could you export the settings, but leaving out the sessions?

**Comment by webdbase** [comment] 2024-08-14 05:45
LastSessions<|||>1<|||>e-uni-tunel|Пловдив
LastActiveSession<|||>1<|||>Пловдив
SessionManager_WindowWidth<|||>3<|||>1040
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,53
ColsVisible_connform.ListSessions<|||>1<|||>0
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
TableTools_WindowWidth<|||>3<|||>1044
TableTools_TreeWidth<|||>3<|||>357
Usermanager_ListWidth<|||>3<|||>293
ColWidths_UserManagerForm.listUsers<|||>1<|||>192,80
ColsVisible_UserManagerForm.listUsers<|||>1<|||>0,1
ColPositions_UserManagerForm.listUsers<|||>1<|||>0,1
ColSort_UserManagerForm.listUsers<|||>1<|||>0,0
ColWidths_frmTableEditor.listColumns<|||>1<|||>45,220,141,138,60,137,122,136,260,128,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>405,100,80,120,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>10,227,139,108,48,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
CoolBand0Index<|||>3<|||>0
CoolBand0Break<|||>3<|||>1
CoolBand0Width<|||>3<|||>1360
CoolBand1Index<|||>3<|||>1
CoolBand1Break<|||>3<|||>1
CoolBand1Width<|||>3<|||>1360
dbtreewidth<|||>3<|||>231
MainWinMaximized<|||>3<|||>1
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,316
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,316,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,124
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,256
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>198,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>4,1
DateTimeEditor_CursorPos_Type4<|||>3<|||>6
TableTools_FindText<|||>1<|||>228
MemoEditorWidth<|||>3<|||>1044
MemoEditorHeight<|||>3<|||>500
ExportSQL_CreateTables<|||>3<|||>1
UpdatecheckLastrun<|||>1<|||>2024-08-08 16:42:23
GridExportEncoding<|||>3<|||>0
GridExportFormat<|||>3<|||>1
querymemoheight<|||>3<|||>158
ExportSQL_DataHow<|||>3<|||>2
ExportSQL_Output<|||>3<|||>3
ExportSQL_CreateDatabases<|||>3<|||>1
WrapLongLines<|||>3<|||>1
GridExportSeparator<|||>1<|||>\t
TableTools_WindowHeight<|||>3<|||>646
sqloutheight<|||>3<|||>101
SQL Attr Comment Foreground<|||>3<|||>8421504
SQL Attr Comment Background<|||>3<|||>536870911
SQL Attr Comment Style<|||>3<|||>2
SQL Attr ConditionalComment Foreground<|||>3<|||>8421504
SQL Attr ConditionalComment Background<|||>3<|||>536870911
SQL Attr ConditionalComment Style<|||>3<|||>2
SQL Attr DataType Foreground<|||>3<|||>128
SQL Attr DataType Background<|||>3<|||>536870911
SQL Attr DataType Style<|||>3<|||>1
SQL Attr DefaultPackages Foreground<|||>3<|||>536870911
SQL Attr DefaultPackages Background<|||>3<|||>536870911
SQL Attr DefaultPackages Style<|||>3<|||>1
SQL Attr DelimitedIdentifier Foreground<|||>3<|||>32896
SQL Attr DelimitedIdentifier Background<|||>3<|||>536870911
SQL Attr DelimitedIdentifier Style<|||>3<|||>0
SQL Attr Exception Foreground<|||>3<|||>536870911
SQL Attr Exception Background<|||>3<|||>536870911
SQL Attr Exception Style<|||>3<|||>2
SQL Attr Function Foreground<|||>3<|||>8388608
SQL Attr Function Background<|||>3<|||>536870911
SQL Attr Function Style<|||>3<|||>1
SQL Attr Identifier Foreground<|||>3<|||>32896
SQL Attr Identifier Background<|||>3<|||>536870911
SQL Attr Identifier Style<|||>3<|||>0
SQL Attr Number Foreground<|||>3<|||>8388736
SQL Attr Number Background<|||>3<|||>536870911
SQL Attr Number Style<|||>3<|||>0
SQL Attr PLSQL-ReservedWord Foreground<|||>3<|||>536870911
SQL Attr PLSQL-ReservedWord Background<|||>3<|||>536870911
SQL Attr PLSQL-ReservedWord Style<|||>3<|||>1
SQL Attr ReservedWord Foreground<|||>3<|||>16711680
SQL Attr ReservedWord Background<|||>3<|||>536870911
SQL Attr ReservedWord Style<|||>3<|||>1
SQL Attr Space Foreground<|||>3<|||>536870911
SQL Attr Space Background<|||>3<|||>536870911
SQL Attr Space Style<|||>3<|||>0
SQL Attr SQLPlus-Command Foreground<|||>3<|||>536870911
SQL Attr SQLPlus-Command Background<|||>3<|||>536870911
SQL Attr SQLPlus-Command Style<|||>3<|||>1
SQL Attr String Foreground<|||>3<|||>32768
SQL Attr String Background<|||>3<|||>536870911
SQL Attr String Style<|||>3<|||>0
SQL Attr Symbol Foreground<|||>3<|||>16711680
SQL Attr Symbol Background<|||>3<|||>536870911
SQL Attr Symbol Style<|||>3<|||>0
SQL Attr TableName Foreground<|||>3<|||>16711935
SQL Attr TableName Background<|||>3<|||>536870911
SQL Attr TableName Style<|||>3<|||>0
SQL Attr Variable Foreground<|||>3<|||>8388736
SQL Attr Variable Background<|||>3<|||>536870911
SQL Attr Variable Style<|||>3<|||>0
DoUsageStatistics<|||>3<|||>1
FieldEditor_Set<|||>3<|||>1
LineBreakStyle<|||>3<|||>1
DataLocalNumberFormat<|||>3<|||>0
LastUsageStatisticCall<|||>1<|||>2024-07-23 21:18:52
AutoReconnect<|||>3<|||>1
Updatecheck<|||>3<|||>0
UpdatecheckBuilds<|||>3<|||>1
UpdatecheckInterval<|||>3<|||>0
FavoriteObjectsOnly<|||>3<|||>0
ColWidths_frmInsertFiles.ListColumns<|||>1<|||>100,80,568
ColsVisible_frmInsertFiles.ListColumns<|||>1<|||>0,1,2
ColPositions_frmInsertFiles.ListColumns<|||>1<|||>0,1,2
ColSort_frmInsertFiles.ListColumns<|||>1<|||>-1,0
ColWidths_frmInsertFiles.ListFiles<|||>1<|||>598,70,80
ColsVisible_frmInsertFiles.ListFiles<|||>1<|||>0,1,2
ColPositions_frmInsertFiles.ListFiles<|||>1<|||>0,1,2
ColSort_frmInsertFiles.ListFiles<|||>1<|||>0,0
queryhelperswidth<|||>3<|||>20
DataFontSize<|||>3<|||>9
GridExportSelection<|||>3<|||>1
MainWinLeft<|||>3<|||>0
MainWinTop<|||>3<|||>0
PromptSaveFileOnTabClose<|||>3<|||>0
FileDialogEncoding_MainForm<|||>3<|||>5
DatabaseFilter<|||>1<|||>elpr|uis<{{{><}}}>elp<{{{><}}}>ui<{{{><}}}>elpr<{{{><}}}>
GridExportOutputCopy<|||>3<|||>1
GridExportOutputFile<|||>3<|||>0
GridExportColumnNames<|||>3<|||>1
ColWidths_frmRoutineEditor.listParameters<|||>1<|||>10,374,90,70
ColsVisible_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColPositions_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColSort_frmRoutineEditor.listParameters<|||>1<|||>-1,0
TableEditorTabsHeight<|||>3<|||>161
MainWinWidth<|||>3<|||>1372
MainWinHeight<|||>3<|||>542
SessionManager_WindowLeft<|||>3<|||>259
SessionManager_WindowTop<|||>3<|||>60
PlinkExecutable<|||>1<|||>plink.exe
ExportSQL_ServerDatabase<|||>1<|||>[Същото като на изходния сървър]
SQL Attr ConsoleOutput Foreground<|||>3<|||>536870911
SQL Attr ConsoleOutput Background<|||>3<|||>536870911
SQL Attr ConsoleOutput Style<|||>3<|||>5
SQL Attr ProcName Foreground<|||>3<|||>536870911
SQL Attr ProcName Background<|||>3<|||>536870911
SQL Attr ProcName Style<|||>3<|||>0
LogToFile<|||>3<|||>0
Language<|||>1<|||>
FontSize<|||>3<|||>12
Field_NullBackground<|||>3<|||>-16777216
RowBackgroundEven<|||>3<|||>536870911
RowBackgroundOdd<|||>3<|||>536870911
FieldColor_Real<|||>3<|||>255
GridRowLineCount<|||>3<|||>1
LogHorizontalScrollbar<|||>3<|||>1
GridExportTerminator<|||>1<|||>\r\n
TableTools_FindCaseSensitive<|||>3<|||>0
HightlightSameTextBackground<|||>3<|||>65535
FilterPanel<|||>3<|||>0
DonatedEmail<|||>1<|||>
Usermanager_WindowWidth<|||>3<|||>892
SQLHelp_WindowWidth<|||>3<|||>969
SQLHelp_WindowHeight<|||>3<|||>514
SQLHelp_PnlLeftWidth<|||>3<|||>340
Usermanager_WindowHeight<|||>3<|||>391
SQL Attr Key Foreground<|||>3<|||>16711680
SQL Attr Key Background<|||>3<|||>536870911
SQL Attr Key Style<|||>3<|||>1
Theme<|||>1<|||>Windows
GUIFontName<|||>1<|||>
GridExportClpFormat<|||>3<|||>1
GridExportClpColumnNames<|||>3<|||>1
GridExportClpAutoInc<|||>3<|||>1
GridExportClpSeparator<|||>1<|||>\t
GridExportClpEncloser<|||>1<|||>
GridExportClpTerminator<|||>1<|||>\r\n
GridExportClpNull<|||>1<|||>\N
GridExportWindowWidth<|||>3<|||>694
GridExportWindowHeight<|||>3<|||>511
GridExportEncloser<|||>1<|||>
GridExportIncludeQuery<|||>3<|||>1
GridExportNull<|||>1<|||>\Z
IconPack<|||>1<|||>Silk
PreferencesWindowWidth<|||>3<|||>1104
PreferencesWindowHeight<|||>3<|||>584
FileImport_WindowWidth<|||>3<|||>803
SQLHelp_WindowLeft<|||>3<|||>143
SQLHelp_WindowTop<|||>3<|||>214
WebSearchBaseUrl<|||>1<|||>https://www.google.com/search?q=%query
ThemePreviewWidth<|||>3<|||>1382
ThemePreviewHeight<|||>3<|||>754
ThemePreviewTop<|||>3<|||>-8
ThemePreviewLeft<|||>3<|||>-8
SessionManager_WindowHeight<|||>3<|||>569
AutoExpand<|||>3<|||>1
CreateDbCollation<|||>1<|||>utf8_general_ci
FileDialogEncoding_loaddataform<|||>3<|||>5
CSVImportWindowWidth<|||>3<|||>1118
CSVSeparatorV2<|||>1<|||>\t
CSVEncloserV2<|||>1<|||>
CSVImportFieldEscaperV2<|||>1<|||>
DisplayObjectSizeColumn<|||>3<|||>0
CSVImportIgnoreLines<|||>3<|||>1
CodeFolding<|||>3<|||>0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,391
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
TableTools_Datatype<|||>3<|||>3
TableToolsFindMatchType<|||>3<|||>0
UpdateCheckWindowWidth<|||>3<|||>623
CSVImportWindowHeight<|||>3<|||>725
GridExportAutoInc<|||>3<|||>1
MaxQueryResults<|||>3<|||>100
CSVImportDuplicateHandling<|||>3<|||>0
ShowRowId<|||>3<|||>1
ColumnSelectorWidth<|||>3<|||>281
ColumnSelectorHeight<|||>3<|||>268
AlwaysGenerateFilter<|||>3<|||>1
SQLHelp_PnlRightTopHeight<|||>3<|||>162

**Comment by ansgarbecker** [comment] 2024-11-23 09:40
Well I tried to find a relevant difference between your settings from above and mine, but I couldn't find anything. And I'm still unable to reproduce the issue here. Tested on multiple screens with even different DPI settings - no problem.

Please verify you're using the latest build (not just the official v12.8 release) and report back.

**Comment by webdbase** [comment] 2024-11-30 13:55
Latest version, revision 12.8.0.6958. Still the same problem.

https://github.com/user-attachments/assets/49404f3a-6d26-4bcd-892f-6122dcb5ec09

**Comment by webdbase** [comment] 2024-12-17 08:50
Same thing.

https://github.com/user-attachments/assets/f7499360-cbad-4b88-9977-784289d19939

**Comment by ansgarbecker** [comment] 2024-12-17 09:31
Thank you.

Two more things:
* what's the DPI setting on your screen?
* in your above posted config file, there's a "broken" setting: `GUIFontName<|||>1<|||>` - I just created the same setting here and got a strange GUI font and size. I will provide a fix which ignores such broken font names.

**Comment by webdbase** [comment] 2024-12-17 16:50
On windows 11 the display resolution is 1920x1200 (recommended), Scale 150% (recommended)
On windows 10  with multiple displays:
 Display No. 1 - resolution 1920x1080 (recommended), Scale 120% (recommended)
 Display No. 2 - resolution 1920x1080 (recommended), Scale 100% (recommended)

**Comment by ansgarbecker** [comment] 2024-12-28 10:03
Please check with the next build. After applying a filter I am now repainting the tree, probably that helps.

**Comment by ansgarbecker** [comment] 2024-12-31 13:07
I'd like to keep #2063 open and close this one, so we have only one to refer to. Please starr that issue to get updates. It seems a solution will take some time.

**Closed by ansgarbecker** 2024-12-31 13:07 UTC
Labels: bug
