### ISSUE TITLE
Can't cancel cell NULL value set operation

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1146] opened 2020-09-03 09:18 UTC
Reproducing the bug:
1. Set NULL value to some cell using Ctrl+Shift+N .
2. Press ESC to cancel
3. Nothing happened. Expected undo action.

**Comment by WesleyM77** [comment] 2020-09-03 12:10
To get it in the format of the form. I've also confirmed that this is happening for me as well.

**Describe the bug**
When setting a cell's value to null using the keyboard shortcut and then pressing escape, it doesn't undo the action. Clicking away sets the cell's value to null.

**To Reproduce**
Steps to reproduce the behavior:
1. Click once on a cell.
2. Press Ctrl+Shift+N to set the value to null.
3. Press the ESC key. Observe no change.
4. Click away to see the value change.

**Expected behavior**
Expect the ESC key to undo setting the cell value to NULL.

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.0.0.6096 (Latest Nightly)
 - Database type and version: Maria 10.4.12

**Comment by ansgarbecker** [comment] 2020-09-03 12:27
@AlexLunyov please do not delete the issue template. Just fill it out.

@WesleyM77 thanks for the update.

Interesting though that <kbd>Esc</kbd> works again after focusing the grid cell right or left besides the edited one. Looks like an issue in the focus-changing event.

**Comment by ansgarbecker** [comment] 2020-09-03 12:36
At least in this case this was not the problem - I can see he deleted the template in the menu behind "edit". In some other cases this might be the case. Do you have a clue how to get rid of these no-template reports?

**Comment by WesleyM77** [comment] 2020-09-03 12:43
Automatically? Unfortunately not. I think GitHub will always allow blank templates. You could put something in the ReadMe asking folks to use one of the defined templates, and if they don't, you could close the issue and request they put it it properly. But I couldn't find anything about fixing the case I described.

**Comment by ansgarbecker** [comment] 2020-12-17 11:20
Cancel button (and it's Esc hotkey) should be enabled now, in the next build, when setting NULL.

**Closed** 2020-12-17 11:20 UTC
Labels: bug, confirmed
