### ISSUE TITLE
Search results unstable / freezing

### ISSUE THREAD

**Issue by webloft** [HeidiSQL/HeidiSQL#2000] opened 2024-08-07 10:58 UTC
### What where you trying to do?
Search something - results are opening multiple tabs of table data.

### What actually happened?
Tabs do not respond if you try to switch between them, overlays are laggy too - UI freezes completely. Also the results are loading very slow.

The thread `heidisql.exe!mysql_authentication_dialog_ask` has a high CPU usage.

Edit: That may be related with bigger text rows too. It also freezes by executing the standalone search result query that would display the results for a single tab.

### What did you expect to happen?
No freezes.

I never experienced that in previous versions.

### HeidiSQL version

12.8.0.6908

### Database server version

-

### Reproduction recipe

Do a database search over mutliple table results

**Comment by trthskr4** [comment] 2024-08-21 00:45
I'm having the same issue.  Search the database and click "See Results" and it takes forever to load the results and every mouse scroll click takes at least a minute to scroll to the next line.

**Comment by gorangalinec** [comment] 2024-08-22 12:46
Same here.

**Comment by ansgarbecker** [comment] 2024-09-17 18:48
Here we go. Next build disables the multi-line-per-row feature, which I suspect is the reason for that laggy performance.
May reopen other issues, but these should be edge cases.
Tests look promising to me.

**Comment by ansgarbecker** [comment] 2024-10-12 12:44
Does anyone still has this issue? I cannot reproduce it, so i would like to close this.

**Closed** 2024-10-20 10:27 UTC
Labels: bug, confirmed

**Comment by webloft** [comment] 2024-10-22 12:49
@ansgarbecker not fixed for me

In a data table with e.g. LONGTEXT data type, I can click and edit one field. If I want to edit another one it still freezes.

**Comment by ansgarbecker** [comment] 2024-10-24 10:17
@webloft you will need to post more technical details, most important the number of rows and somehow the average size of the LONGTEXT contents in that table. Easiest way would be to send an SQL export of the table in question, but I don't know if it contains sensitive information.

**Comment by webloft** [comment] 2024-10-24 11:19
@ansgarbecker

Rows: 5005
AVG length: 8658
MAX length: 4207233

The max length is 1 row only, follwed by 60 100-700k byte entries but other rows are very tiny (<1k). I think 4MB may take some seconds to load but shouldn't freeze.

**Comment by ansgarbecker** [comment] 2024-10-24 13:02
For reproducing I created a simple table with larger random text contents in it:

```
CREATE TABLE `randomcontent` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `desc` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
    `ts` TIMESTAMP NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE
)
```

Length of `desc` is between 100B and 1M, table has 1000 rows.

I cannot reproduce any slowness after editing some fields.

* Is your table perhaps missing a primary key? => Please post the CREATE TABLE code here.
* How stable is your SSH tunnel?

**Comment by webloft** [comment] 2024-10-24 13:30
This is standard wordpress table:

```
CREATE TABLE `wp_options` (
	`option_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`option_name` VARCHAR(191) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_520_ci',
	`option_value` LONGTEXT NOT NULL COLLATE 'utf8mb4_unicode_520_ci',
	`autoload` VARCHAR(20) NOT NULL DEFAULT 'yes' COLLATE 'utf8mb4_unicode_520_ci',
	PRIMARY KEY (`option_id`) USING BTREE,
	UNIQUE INDEX `option_name` (`option_name`) USING BTREE,
	INDEX `autoload` (`autoload`) USING BTREE
)
COLLATE='utf8mb4_unicode_520_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1186795
;
```

In this table, I go to data view, set a filter for the row with the biggest content and click on the field `option_value` to view/edit it and then it freezes.

The connection is fine. Import/Export table data works fine. Gigabyte of data are no problem with other operations.

It doesn't matter if tunnel was created by plink or using a forwarded port opened by a putty terminal.
