### ISSUE TITLE
Popup "wrong passphrase" appears even for correct passphrase

### ISSUE THREAD

**Issue by bst-biwac** [HeidiSQL/HeidiSQL#1838] opened 2023-08-09 09:40 UTC
**Preconditions**

* HeidiSQL version:12.5.0.6677
* Database type and version:Percona XtraDB Cluster 5.7.31-34-57-log
* OS:win10 64bit

**Describe the bug**

When connecting to a database through SSH with passphrase authentication and providing the correct passphrase, a popup appears saying "wrong passphrase", yet I'm logged in to the database.

**To Reproduce**

1. create/save DB connection with SSH tunnel (MariaDB/Mysql) and using plink.exe / SSH tunnel with a private key file that requires a passphrase (ed25519)
2. connect
3. click OK on the "wrong passphrase" popup

Expected result: no "wrong passphrase" popup OR if the passphrase was indeed wrong, no connection to the server/DB
Actual result: "wrong passphrase" popup appears even when the correct passphrase is provided

**Screenshots or Crash reports**

![09-08-_2023_11-37-10](https://github.com/HeidiSQL/HeidiSQL/assets/70888054/50f36fc3-ebb2-420b-9938-735e8a2a4120)

Log
```
/* [11:36:48.677] Verbindung zu sqlserver über MariaDB or MySQL (SSH tunnel), Benutzername ******, benutze Passwort: Yes … */
/* [11:36:48.682] Port #*** wird bereits verwendet. Teste ob *** verfügbar ist … */
/* [11:36:50.741] Versuche SSH-Prozess zu starten, warte 4s auf Antwort … */
/* [11:36:50.747] ...plink.exe -ssh *****@****** -pw "******" -P *** -i "***id_ed25519.ppk" -N -L ***:***:*** */
/* [11:36:51.161] SSH: Using username "****".
 */
[11:41:02.430] SELECT CONNECTION_ID();
[11:41:02.463] SHOW VARIABLES;
/* [11:41:02.488] Zeichensatz: utf8mb4 */
[11:41:02.512] SHOW /*!50002 GLOBAL */ STATUS;
[11:41:02.547] SELECT NOW();
/* [11:41:02.566] Verbunden. Prozess-ID: ************ */
/* [11:41:02.602] Reading function definitions from C:\Program Files\HeidiSQL\functions-mysql.ini */
[11:41:02.623] SHOW TABLES FROM `information_schema`;
[11:41:02.656] SHOW DATABASES;
```

**Comment by ansgarbecker** [comment] 2023-08-09 17:05
Will have to test this myself, with a passphrased key.

I suspect my code for reading the plink output is again buggy.

**Comment by batteryf1** [comment] 2023-11-01 08:46
Also have this problem, I have found one with symbols causing the problem: £(alt+0163)

**Comment by ansgarbecker** [comment] 2024-04-17 09:40
@batteryf1 or @bst-biwac or someone: could you please test with the next build (6831).
I believe the shown "wrong passphrase" dialog is just shown in the wrong order, which should be fixed now. I could not reproduce that here, and probably the older plink executable caused a part of the issue as well.

Note that using a key with a passphrase will only prompt you when using plink, not ssh.exe. So prefer plink at the moment.

**Closed** 2024-04-25 13:35 UTC
Labels: bug, ssh-tunnel
