### ISSUE TITLE
Why is the syntax wrong when creating a SQLSERVER stored procedure?

### ISSUE THREAD

**Issue by Ramon403** [HeidiSQL/HeidiSQL#1083] opened 2020-07-09 06:53 UTC
Why is the syntax wrong when creating a SQLSERVER stored procedure?

## Steps to reproduce this issue

Just right click the datatabase in which you want to create a procedure, then point on "Create new" 
or Edit

## Current behavior

![image](https://user-images.githubusercontent.com/2922635/87006083-a99b6000-c1f2-11ea-8816-4e4a147fd056.png)
![image](https://user-images.githubusercontent.com/2922635/87006824-e025aa80-c1f3-11ea-963c-1dd10a8f877f.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/2922635/87006295-06971600-c1f3-11ea-96d3-ffc8b816f9fa.png)

* **HeidiSQL version:** 
  11.0.0.5919
* **Database system and version:** 
  MS Sql Server 2018
* **Operating system:** 
  Win10 2004

**Comment by ansgarbecker** [comment] 2020-07-09 08:40
Duplicate of #667
This is because the routine editor was originaly made for MySQL routines.

**Closed by ansgarbecker** 2020-07-09 08:40 UTC
