### ISSUE TITLE
Installation Error (Failed to expand shell folder constant "userdocs"

### ISSUE THREAD

**Issue by reitbrud** [HeidiSQL/HeidiSQL#1334] opened 2021-03-13 08:38 UTC
Hallo i have Error on Installation.

Internal Error: Failed to expand shell folder constant "userdocs"

To Inform i have my Documents folder on network drive.

![grafik](https://user-images.githubusercontent.com/34591964/111024602-ebaf1e00-83df-11eb-9c8b-8b86855805ab.png)

**Preconditions**

* HeidiSQL version:
* Database type and version:
* OS:

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2021-03-13 09:26
Duplicate of #811

**Closed by ansgarbecker** 2021-03-13 09:27 UTC
