### ISSUE TITLE
GRANT deletion when changing a procedure

### ISSUE THREAD

**Issue by WallaceWilliam** [HeidiSQL/HeidiSQL#1039] opened 2020-05-24 09:31 UTC
First, 
grant execute on procedure proc1 to role1;
+-------------------------------------------------------------------------+
| Grants for role1                                                     |
+-------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `role1`                                        |
| GRANT EXECUTE ON PROCEDURE `db`.`proc1` TO `role1` |
+-------------------------------------------------------------------------+
Second, on HeidiSQL 11.0.0.5975 I update stored procedure proc1

after that GRANT for the procedure disappeared
+-------------------------------------------------------------------------+
| Grants for role1                                                     |
+-------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `role1`                                        |
+-------------------------------------------------------------------------+

**Comment by ansgarbecker** [comment] 2022-01-03 19:24
Duplicate of #1508

**Closed by ansgarbecker** 2022-01-03 19:24 UTC
