### ISSUE TITLE
Opening "Create Code..." or "Alter Code..." tab produces force close when using MSSQL table

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#1914] opened 2024-02-26 13:30 UTC
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/14405218/bugreport.txt)

**Preconditions**

* HeidiSQL version: 12.6.0.6803
* Database type and version: MSSQL Server 2012
* OS: Windows 10 x64 build 19045

**Describe the bug**

Opening "Create Code..." or "Alter Code..." tab produces force close when using MSSQL table. The error is with exception class **EStringListError** and exception message: **List index out of bounds (0). TStringList object range is 0..-1.** 
See the attached bug report files.

**To Reproduce**

Opening "Create Code..." or "Alter Code..." tab produces force close when using MSSQL table with error  "List index out of bounds (0). TStringList object range is 0..-1"

**Screenshots or Crash reports**

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/14405252/bugreport.txt)
![bug](https://github.com/HeidiSQL/HeidiSQL/assets/8297417/cc6ffa9e-84cc-47e4-ba11-d848a5843efa)

**Comment by ansgarbecker** [comment] 2024-11-01 07:16
Duplicate of #1939. I already fixed that in 5309787847ba7ec64f5043c2c931ed601099f5b2 for v12.7

**Closed by ansgarbecker** 2024-11-01 07:16 UTC
Labels: bug
