### ISSUE TITLE
Export as single SQL INSERT

### ISSUE THREAD

**Issue by User756675678** [HeidiSQL/HeidiSQL#1166] opened 2020-09-24 05:45 UTC
**Is your feature request related to a problem? Please describe.**
I want export table data as single SQL INSERT. Why single? It is very useful: you need edit only one place with table name, you can add ON DUPLICATE KEY UPDATE clause and so on.

**Describe the solution you'd like**
Add another item in export list - SQL INSERT.

**Describe alternatives you've considered**
It can be special option for SQL INSERTs item.

**Additional context**
Nope.

**Comment by ansgarbecker** [comment] 2020-09-24 06:28
About which export dialog are you talking - HeidiSQL has two different ones: the grid export, or the "Table tools" dialog with the option to make large exports of a whole database?

**Comment by User756675678** [comment] 2020-09-24 11:27
The grid export. When you right click on results table and choose "Export data".

**Comment by ansgarbecker** [comment] 2020-09-24 11:30
And that one does not export single `INSERT`s for you? It should, but probably you saw something different there?

#182 asks for the opposite - bulk INSERTs.

**Comment by User756675678** [comment] 2020-09-24 15:33
Nope. It is ask for same. I not find this issue when search before start this issue.

by "Single insert"  I mean one single insert for all data. Like 
`INSERT INTO table (col1, col2, ...) VALUES (row1_val1, row1_val2, ...), (row2_val1, row2_val2, ...), ...`
Not as "single insert per row".

Currently "SQL INSERTs" produce Insert per row. It is not suitable if you want change table name or add ON DUPLICATE KEY UPDATE clause.

**Comment by ansgarbecker** [comment] 2020-09-24 15:36
Ah, so I misunderstood you - you want multiple rows per singel INSERT... In that case this is indeed a duplicate of #182.

**Closed** 2020-09-24 15:36 UTC
Labels: duplicate
