### ISSUE TITLE
Access violation on sorting

### ISSUE THREAD

**Issue by Delphichem** [HeidiSQL/HeidiSQL#1902] opened 2024-01-30 16:40 UTC
**Preconditions**

* HeidiSQL version: heidisql64.r6788
* Database type and version: MariaDB 10.8.3
* OS: Windows 11

**Describe the bug**

Access violation on sorting

**To Reproduce**

1. Select a table
2. Go to 'Data' tab
3. Click on 'Sorting'
4. Click on 'Add Col'
5. Click on delete column button (the button with "X" glyph)
6. See error message: Access violation
**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/12384176/2d81515f-9599-4d7e-b8cc-952465770c99)

**Comment by ansgarbecker** [comment] 2024-01-31 05:23
Yes, this is a known crash. Unfortunately nearly impossible to fix.

Duplicate of issue #520

**Closed by ansgarbecker** 2024-01-31 05:23 UTC
