### ISSUE TITLE
HeidiSQL hangs when opening data tab of specific table

### ISSUE THREAD

**Issue by terenzif** [HeidiSQL/HeidiSQL#671] opened 2019-06-07 07:12 UTC
[heidisql_bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3264777/heidisql_bugreport.txt)

```
exception class    : EOleException
exception message  : Si sono verificati errori in un'operazione composta da più passaggi. Controllare i singoli valori di stato.

main thread ($4a1c):
00ab0532 heidisql.exe Data.Win.ADODB            TCustomADODataSet.GetFieldData
00a5f070 heidisql.exe Data.DB                   TField.GetData
00a67529 heidisql.exe Data.DB                   TDateTimeField.GetValue
00a67405 heidisql.exe Data.DB                   TDateTimeField.GetText
00a67348 heidisql.exe Data.DB                   TDateTimeField.GetAsString
00a5eb49 heidisql.exe Data.DB                   TField.GetAsAnsiString
00b0cc4d heidisql.exe dbconnection    6210  +18 TAdoDBQuery.Col
00dc6953 heidisql.exe Main            8934  +43 TMainForm.AnyGridGetText
00949d46 heidisql.exe VirtualTrees   33939   +8 TCustomVirtualStringTree.DoGetText
00948633 heidisql.exe VirtualTrees   33413   +4 TCustomVirtualStringTree.GetText
00949c63 heidisql.exe VirtualTrees   33923  +27 TCustomVirtualStringTree.DoGetNodeWidth
00939928 heidisql.exe VirtualTrees   26979  +85 TBaseVirtualTree.GetDisplayRect
00dc94c9 heidisql.exe Main            9483  +28 TMainForm.AutoCalcColWidth
00db1fdb heidisql.exe Main            5236 +174 TMainForm.DataGridBeforePaint
```

## Steps to reproduce this issue

simply opening the data tab of a table of my MSSQL database project regularly hangs HeidiSQL.
I couldn't figure out the reason or the field which generate problems.

<details>
<summary>Following the table structure:</summary>

```
CREATE TABLE [dbo].[tableXXX](
	[IdDocAltriDati] [int] IDENTITY(1,1) NOT NULL,
	[idAzienda] [int] NOT NULL,
	[idUtente] [int] NOT NULL,
	[idDocumento] [int] NOT NULL,
	[accontoImporto] [money] NULL,
	[accontoIdConto] [int] NULL,
	[accontoMezzo] [varchar](30) NULL,
	[ricambiTotale] [money] NULL,
	[ricambiPercSconto] [float] NULL,
	[ricambiSconto] [money] NULL,
	[ricambiImponibile] [money] NULL,
	[ricambiIva] [money] NULL,
	[serviziTotale] [money] NULL,
	[serviziPercSconto] [float] NULL,
	[serviziSconto] [money] NULL,
	[serviziImponibile] [money] NULL,
	[serviziIva] [money] NULL,
	[manoTariffa] [money] NULL,
	[manoTotale] [money] NULL,
	[manoPercSconto] [float] NULL,
	[manoSconto] [money] NULL,
	[manoImponibile] [money] NULL,
	[manoIvaCodice] [varchar](10) NULL,
	[manoIva] [money] NULL,
	[rifiutiPerc] [float] NULL,
	[rifiutiLimite] [money] NULL,
	[rifiutiImponibile] [money] NULL,
	[rifiutiIvaCodice] [varchar](10) NULL,
	[rifiutiIva] [money] NULL,
	[consumoPerc] [float] NULL,
	[consumoLimite] [money] NULL,
	[consumoImponibile] [money] NULL,
	[consumoIvaCodice] [varchar](10) NULL,
	[consumoIva] [money] NULL,
	[speseTrasporto] [money] NULL,
	[speseTrasportoIvaCodice] [varchar](10) NULL,
	[speseTrasportoIva] [money] NULL,
	[speseIncasso] [money] NULL,
	[speseIncassoIvaCodice] [varchar](10) NULL,
	[speseIncassoIva] [money] NULL,
	[speseAltre] [money] NULL,
	[speseAltreIvaCodice] [varchar](10) NULL,
	[speseAltreIva] [money] NULL,
	[docCausale] [varchar](100) NULL,
	[docAspetto] [varchar](50) NULL,
	[docColli] [varchar](10) NULL,
	[docPeso] [varchar](10) NULL,
	[docPorto] [varchar](3) NULL,
	[docTrasporto] [varchar](3) NULL,
	[docVettore1] [int] NULL,
	[docVettore2] [int] NULL,
	[docInizioTrasporto] [datetime] NULL,
	[accettaIdOperatore] [int] NULL,
	[accettaDataIngresso] [date] NULL,
	[accettaOraIngresso] [time](0) NULL,
	[accettaDataPrevista] [date] NULL,
	[accettaDataChiusura] [date] NULL,
	[accettaDataConsegna] [date] NULL,
	[accettaOraConsegna] [time](0) NULL,
	[accettaNoteCliente] [varchar](500) NULL,
	[accettaNoteOfficina] [varchar](500) NULL,
	[PAbolloVirtuale] [money] NULL,
	[PAesigibilitaIva] [varchar](1) NULL,
	[PAidDocumento] [varchar](20) NULL,
	[PAdataDocumento] [date] NULL,
	[PAcodiceCUP] [varchar](15) NULL,
	[PAcodiceCIG] [varchar](15) NULL,
	[PAesportato] [bit] NULL,
	[ScontoFinanziarioPercentuale] [float] NULL,
	[ScontoFinanziarioAssoluto] [money] NULL,
	[RitenutaPercentuale] [float] NULL,
	[RitenutaAssoluta] [money] NULL,
	[NotePartite] [varchar](255) NULL,
	[docNote] [varchar](255) NULL,
	[PAcausalePagamento] [varchar](2) NULL,
	[PAtipoRitenuta] [varchar](4) NULL,
	[accettaTempoStimato] [float] NULL,
	[ScontoEconomicoPercentuale] [float] NULL,
	[ScontoEconomicoAssoluto] [money] NULL,
	[ScontoEconomicoPercentualeInserito] [bit] NULL,
	[RitenutaImponibilePercentuale] [float] NULL,
	[PAriferimentoAmministrazione] [varchar](20) NULL,
	[manodoperaForzataOperatori] [bit] NULL,
	[PAnumItem] [varchar](20) NULL,
	[PAconvenzioneIdDocumento] [varchar](20) NULL,
	[idIspezione] [int] NULL,
	[accettaSoccorsoStradale] [bit] NULL,
	[accettaGaranzia] [bit] NULL,
	[accettaAirbagFunzionanti] [bit] NULL,
	[accettaRuotaScorta] [bit] NULL,
	[accettaNumeroAssegnato] [int] NULL,
	[accettaLivelloCarburante] [smallint] NULL,
 CONSTRAINT [PK_tableXXX] PRIMARY KEY CLUSTERED 
(
	[IdDocAltriDati] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tableXXX] ADD  CONSTRAINT [DF__documenti__idAzi__3EDC53F0]  DEFAULT ((1)) FOR [idAzienda]
GO
```
</details>

## Environment

* **HeidiSQL version:** 
HeidiSQL ver. 10.1.5538
* **Database system and version:** 
MSSQL 12.0
* **Operating system:** 
HeidiSQL running on Windows 10 64bit

**Comment by v4der86** [comment] 2019-06-11 09:26
I have the same problem.
Currently there are three tables where this happens.
First I could work normaly with the Data-tab but after applying a new filter HeidiSQL crashed. (before i applied several filters)
I tried to delete the registry entries, but it did not helped.
It happes with version 10.1.0.5464 and also with 10.0.5464, i also tried 10.0.0.5460 without success.
After installing 9.5.0.5196 again the problem is gone.

**Comment by timgblack** [comment] 2019-08-27 02:05
I'm seeing the same issue with `TIME` columns. Converting them (`CONVERT(VARCHAR, "TimeColumn")`) works, but it can't be done for the Data view or when exporting.

**Comment by ansgarbecker** [comment] 2019-08-27 04:43
This is a duplicate of #423

**Closed by ansgarbecker** 2019-08-27 04:43 UTC
Labels: bug, mssql
