### ISSUE TITLE
window bar not visible if you have windows start navigation on top off your monitor 

### ISSUE THREAD

**Issue by riderideride** [HeidiSQL/HeidiSQL#1413] opened 2021-07-16 10:39 UTC
**Preconditions**
* HeidiSQL version: 11.3.0.6333
* Database type and version: mysql or any db
* OS: Windows 10

**Describe the bug**
If you have 2 monitors on top of each other (Image 1) and the windows start navigation is in the top off you monitor.
If i open a HeidiSQL db on the top monitor my navigation off the window is still visibel (Image 2)
But if i minimize and maximize the window or i bring an other window on top of it the window bar is missing and i cant not move the window anymore. (Image 3)

**To Reproduce**
1/ If you have 2 monitors on top of each other (Image 1) and the windows start navigation is in the top off you monitor.

2/ If you open a HeidiSQL db **on the top monitor** the navigation off the window is still visibel (Image 2)

3/ But you minimize and maximize the window or you bring an other window on top of it the window bar is missing and you cant not move the window anymore. (Image 3)

**Screenshots or Crash reports**
Image1
![image](https://user-images.githubusercontent.com/26734428/125932904-db3a5a61-35e9-4dfa-8a0b-0da094ca6d25.png)

Image2
![image](https://user-images.githubusercontent.com/26734428/125933417-f092aa6c-9f5a-493a-a76c-1f327c7e2e92.png)

Image3
![image](https://user-images.githubusercontent.com/26734428/125932105-b70533da-f6dd-4a84-bd46-d4e53858c4ac.png)

**Preconditions**

* HeidiSQL version:
* Database type and version:
* OS:

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2021-07-16 13:03
Duplicate of #1200

**Closed by ansgarbecker** 2021-07-16 13:03 UTC
