### ISSUE TITLE
Command line connection issue to SQL Server database

### ISSUE THREAD

**Issue by LukePet** [HeidiSQL/HeidiSQL#977] opened 2020-04-08 12:49 UTC
## Steps to reproduce this issue

1. Open prompt
2. Try to connect to SQL Server instance from command line
3. Run command: heidisql.exe -n=4 -h=SERVER\INSTANCE -u=sa -p=MYPASSWORD -D=MYDATABASE

## Current behavior

SQL Server connection that works properly on HeidiSQL 11 GUI, does not behave the same from the command line.

This works:
![Connection SQL Server](https://user-images.githubusercontent.com/6470875/78785187-fa5aad00-79a6-11ea-999f-9987fbccbed1.PNG)

This does not work:
**heidisql.exe -n=4 -h=192.168.1.30\SQL2016 -u=sa -p=MYPASSWORD -D=MYDATABASE**

I also tried to set port (-P=0) but nothing.

**Important: there are multiple instances of SQL Server on the server**

## Expected behavior

I expect it to behave the same from the command line

## Environment

* **HeidiSQL version: 11.0.0.5919** 
  
* **Database system and version: SQL Server 2016** 
  
* **Operating system: Windows Server 2012**

**Comment by ansgarbecker** [comment] 2020-04-08 14:50
Just thought that the library is the cause, as it is not configurable via command line. But "MSOLEDBSQL" is the default anyway, so that's not the problem.

**Comment by ansgarbecker** [comment] 2020-04-08 15:26
Problem is the dot in the host ip address, and the regular expression parser stopping at the first dot. You can surround the whole hostname using double quotes as a workaround. Same with all other parameters, if they would contain a dot:

    heidisql.exe -n=4 -h="192.168.1.30\SQL2016"

**Comment by ansgarbecker** [comment] 2020-04-08 15:53
I have just documented that dot issue on the [help page](https://www.heidisql.com/help.php#commandline).

Please report if double quotes solved your problem.

**Comment by LukePet** [comment] 2020-04-08 16:36
Does not work.
I also tried specifying the port (-P=0), but it doesn't connect.

Could it be any special characters on the password?
I also tried to put double quotes on the password but it doesn't work.

**Comment by ansgarbecker** [comment] 2020-04-08 18:37
OK, could you please try the following: use your initial command line plus the double quotes around to get the error. Then, select any other connection of which you know it works from the upcoming session manager. In the main window, the SQL log panel should contain such a line from the first connection attempt:

    /* Connecting to .\SQLExpress via Microsoft SQL Server (named pipe), username SA, using password: Yes ... */

The hostname is the interesting part here - I want to check if it's what you entered in the command line, or if it was shortened by the command line parser.

**Comment by LukePet** [comment] 2020-04-09 07:49
I have this error:
![Errore 01](https://user-images.githubusercontent.com/6470875/78870695-d5b61200-7a46-11ea-8089-a5fc4920ca7b.PNG)

and then this log:
```
/* Connecting to 192.168.1.30\SQL2016 via Microsoft SQL Server (TCP/IP), username sa, using password: Yes ... */
/* SQL Error (0): TCP Provider: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione Timeout di accesso scaduto */
/* Connecting to 192.168.1.30\SQL2016 via Microsoft SQL Server (TCP/IP), username sa, using password: Yes ... */
SELECT @@SPID;
/* Connected. Thread-ID: 56 */
SELECT DATEDIFF(SECOND, "login_time", CURRENT_TIMESTAMP) FROM "master"."dbo"."sysprocesses" WHERE "spid"=1;
SELECT GETDATE();
SELECT @@VERSION;
SELECT SERVERPROPERTY('ProductVersion');
SET TEXTSIZE 2147483647;
USE "MYDATABASE";
/* Entering session "MYSESSIONNAME" */
SELECT *, SCHEMA_NAME("schema_id") AS 'schema' FROM "MYDATABASE"."sys"."objects" WHERE "type" IN ('P', 'U', 'V', 'TR', 'FN', 'TF', 'IF');
```

**Could not establish connection. Persistent rejection of the target computer. Login timed out.**

**Comment by ansgarbecker** [comment] 2020-04-09 09:04
Ok thanks. Then there is probably some special character in the password, which breaks the command line parser? Single or double quotes especially are problematic.

**Comment by LukePet** [comment] 2020-04-09 09:16
I honestly don't think it's the password, because with another instance it works and in any case the only special character is # (the rest are letters and numbers)

**Comment by ansgarbecker** [comment] 2020-04-09 09:47
This is correct - that # does not break the parser - I just tested that.
I will have to dive deeper here.

**Comment by ansgarbecker** [comment] 2020-04-09 09:55
I get the same "Login timeout expired" message when using the `MSOLEDBSQL` library in the session manager on a MSSQL/TCP connection. Are you sure that one works for you, or did you select the other library `SQLOLEDB`?
Btw there is no "-D" parameter (which you initially used to pass "MYDATABASE".

**Comment by LukePet** [comment] 2020-04-09 10:26
The error occurs both with the "-D" parameter and without.

MSOLEDBSQL on the GUI is correctly set; on command line I don't think there is a way to specify it.

**Comment by ansgarbecker** [comment] 2020-04-09 13:38
I have now added support for a -l/--library command line parameter, and [documented](https://www.heidisql.com/help.php#commandline) that. You could update HeidiSQL to the new build and try it this way:

    heidisql.exe -n=4 -h=192.168.1.30 -u=sa -p=MYPASSWORD -P=1433 -l=MSOLEDBSQL

At least for me this works, though I use a different network type (named pipe), the old provider and Windows authentication:

    heidisql.exe -n=3 -h=".\SQLExpress" -W=1 -l=SQLOLEDB

**Comment by LukePet** [comment] 2020-04-09 14:57
Does not work...

With this command:
`heidisql.exe -n=4 -h="192.168.1.30\SQL2016" -u=sa -p=MYPASSWORD -P=1433 -l=MSOLEDBSQL`
It connects, but to another instance! (SQLSERVER2008)

With this command:
`heidisql.exe -n=4 -h="192.168.1.30\SQL2016" -u=sa -p=MYPASSWORD -P=0 -l=MSOLEDBSQL`
I have the error.

![SQL Server](https://user-images.githubusercontent.com/6470875/78908546-87beff80-7a82-11ea-815e-51f8d7e67ca6.PNG)

In my opinion the issue is the port, because the SQL2016 instance is set up with dynamic ports; what i don't understand is what different check there is on the port between the GUI (which works) and the command line (when the port is 0).

Named pipes are disabled.

**Comment by ansgarbecker** [comment] 2020-04-09 16:15
Ok, next round. Your hint to the port was helpful. I found that "-p=0" got overridden by the default port (1433). Please update once again to the new build (should be ready in 20 minutes).

**Comment by LukePet** [comment] 2020-04-09 16:56
Ok, now it works! 
But I can't specify the database to connect to? I remember reading that by the "-D" option it was possible to specify it, but it doesn't seem to work.

**Comment by ansgarbecker** [comment] 2020-04-09 17:46
That "-D" did not exist yet. "-d" is the session name, perhaps you're mixing something up here. But it sounds reasonable to add this setting, so I will add support for a -db/--databases parameter, and close the issue afterwards.

Thanks a lot for going through this, and your consistent feedback!

**Closed** 2020-04-09 17:49 UTC
Labels: bug, nettype-mssql

**Comment by LukePet** [comment] 2020-04-10 06:36
Perfect now everything works...thanks!
