### ISSUE TITLE
Horizontal split pane changes out from under me - results pane fills 95% of screen

### ISSUE THREAD

**Issue by HerrimanCoder** [HeidiSQL/HeidiSQL#1190] opened 2020-10-17 13:45 UTC
My default view of HeidiSQL v11.0.0.6096 is as follows:

- list of servers and databases in left pane (about 10% of screen)
- right pane (90% of screen) is split horizontally: sql editor on top (50%), results view on bottom (50%)

So then I leave HeidiSQL for awhile (I don't close it) and come back later, and find that the results view has grown from 50% (where I left it) to 95%, and the horizontal divider bar is almost at the very top. So I have to grab that horizontal divider bar and pull it way back down to 50% where I left it. This same thing happens when I close the program and reopen it. This problem is 100% reproducible. It happens every time.

Prior to v11, this never happened. This is a new bug and is extremely annoying. Why does it happen? Is there a setting I can change to make this stop happening?

**Comment by ansgarbecker** [comment] 2020-10-17 14:11
Please use the issue template for bug reports.

**Comment by WesleyM77** [comment] 2020-10-20 15:27
Duplicate of #1113, possibly?

**Comment by HerrimanCoder** [comment] 2020-10-20 15:57
> Duplicate of #1113, possibly?

Yep, this appears to be the same bug.

**Comment by ansgarbecker** [comment] 2020-10-20 16:49
Duplicate of #1113

**Closed by ansgarbecker** 2020-10-20 16:49 UTC
