### ISSUE TITLE
Text not being displayed entirely 

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1499] opened 2021-12-15 11:53 UTC
**Preconditions**

* HeidiSQL version:  Version 11.3.0.6337 (64 Bit)
* Database type and version: mariadb 10.5.9
* OS: Windows 10 Pro

**Describe the bug**

I have a table that holds a php serialized object and it's not showing all of the text in the editor.

**To Reproduce**
Create the following table:
```
CREATE TABLE `ds_entity` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`table_name` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`entity_name` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`settings` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:object)' COLLATE 'utf8mb4_unicode_ci',
	`created_at` DATETIME NOT NULL,
	`updated_at` DATETIME NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
```
Insert the following data:
```
INSERT INTO `ds_entity` (`table_name`, `entity_name`, `settings`, `created_at`, `updated_at`) 
VALUES ('order', 'Order', 'O:56:"App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings":11:{s:67:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0baseClass";s:16:"App\\Entity\\Order";s:68:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0generateId";b:0;s:69:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0isIdIgnored";b:0;s:64:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0traits";a:0:{}s:71:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0isApiResource";b:1;s:86:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0collectionOperationsAllowGET";b:0;s:87:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0collectionOperationsAllowPOST";b:1;s:75:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0itemOperationsGET";b:0;s:75:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0itemOperationsPUT";b:1;s:77:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0itemOperationsPATCH";b:1;s:78:"\0App\\Service\\DynamicSchema\\Settings\\Entity\\EntitySettings\0itemOperationsDELETE";b:0;}', '2021-12-15 11:31:37', '2021-12-15 11:31:37');
```

If you try to visualize this in the editor you should see the text cut off as you do here:
![image](https://user-images.githubusercontent.com/1086401/146180833-009010a2-55d8-4fce-b4c6-a52f9b119147.png)

If you try to see in the bigger editor you'll see this:

![image](https://user-images.githubusercontent.com/1086401/146181137-dba1d335-8cfa-4359-ad32-08e10fb969b2.png)

Also, when selecting the following option "Export Grid Rows" with these settings:

![image](https://user-images.githubusercontent.com/1086401/146181331-be150188-b646-4d8b-9602-83ccfb58bd94.png)

I get this: 

```
"table_name","entity_name","settings","created_at","updated_at"
"order","Order","O:56:""App\Service\DynamicSchema\Settings\Entity\EntitySettings"":11:{s:67:""
```
Here the text is cut off again.
If you select to export as SQL Insert then you get the correct result (it's how I got the `INSERT` above)

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2021-12-15 12:27
Duplicate of #202

**Closed by ansgarbecker** 2021-12-15 12:27 UTC

**Comment by AntonioCS** [comment] 2021-12-15 12:39
@ansgarbecker is this really a duplicate? I don't see any `\0` in the serialized object. (and plus, mine has pretty screenshots)

**Comment by ansgarbecker** [comment] 2021-12-15 12:57
Definitely, your screens are nicer :)
But these serialized PHP strings have null characters at various positions, which is the cause of it being truncated by HeidiSQL. You can check that yourself:
```
select quote(settings) from ds_settings;
```
If I am right you should see a "\0" at the position where HeidiSQL cuts.

**Comment by AntonioCS** [comment] 2021-12-15 13:00
Indeed, I see them! Thanks, glad you're on the case!
