### ISSUE TITLE
Crash caused by executing a query

### ISSUE THREAD

**Issue by finappear** [HeidiSQL/HeidiSQL#359] opened 2018-10-01 15:02 UTC
## Steps to reproduce this issue

1. Performed a query:

SELECT
	T.`table_name` AS 'table',
	T.`table_type` AS 'type',
	T.`engine`,
	T.`table_comment` AS 'comment',
	T.`table_rows` AS 'count',
	C.`ordinal_position` AS 'ordinal',
	C.`column_name` AS 'column',
	C.`column_type` AS 'coltype',
	C.`is_nullable` AS 'nullable',
	C.`column_default` AS 'default',
	C.`extra`,
	GROUP_CONCAT(DISTINCT(F.`constraint_type`)) AS 'constraints',
	MAX(CONCAT(U.`referenced_table_name`, '.', U.`referenced_column_name`)) AS 'references'
FROM `information_schema`.`TABLES` T
	LEFT JOIN information_schema.COLUMNS C ON (C.`table_schema`=T.`table_schema` AND C.`table_name`=T.`table_name`)
	LEFT JOIN information_schema.KEY_COLUMN_USAGE U ON (U.`table_schema`=T.`table_schema` AND U.`table_name`=T.`table_name` AND U.`column_name`=C.`column_name`)
	LEFT JOIN information_schema.TABLE_CONSTRAINTS F ON (F.`table_schema`=T.`table_schema` AND F.`table_name`=T.`table_name` AND F.`constraint_name`=U.`constraint_name`)
WHERE T.`table_schema`=database()
GROUP BY `table`, `ordinal`

## Current behavior

Caused a crash, giving the option to continue using the application or restart it.
Unable to reproduce. See attached crash report.

## Expected behavior

Not crash.

## Environment
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2434413/bugreport.txt)

* **HeidiSQL version:** 
  9.4.0.5125
* **Database system and version:** 
  MariaDB 10.3.9
* **Operating system:** 
  Windows 7 x64 Service Pack 1 build 7601

**Comment by ansgarbecker** [comment] 2018-10-01 18:08
This is a duplicate of #57 

Not directly related to the query itself, or the results of it.

**Closed by ansgarbecker** 2018-10-01 18:08 UTC
