### ISSUE TITLE
Unable to set unsigned flag

### ISSUE THREAD

**Issue by MRLBEL** [HeidiSQL/HeidiSQL#647] opened 2019-05-12 12:30 UTC
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by MRLBEL** [comment] 2019-05-12 12:33
Hi,

If I have a default value of 000000 then I cannot turn off the unsigned flag i.e. I want the field to be signed. If I set the default value to -1 all is ok.

I want the field to default to zeros but to be signed
Thks,
Mike

**Comment by ansgarbecker** [comment] 2019-05-12 14:19
Is this now still an issue? If yes, did you accidentally close it?

**Comment by MRLBEL** [comment] 2019-05-13 03:39
It is still an issue … must have closed it by mistake … thks.

 

Mike

**Comment by rentalhost** [comment] 2019-05-13 04:15
I am reopening it, but I could not understand what you are saying here.

I did some tests with `ZEROFILL` and it really will enable `UNSIGNED`. But it came from MySQL and [MariaDB](https://mariadb.com/kb/en/library/numeric-data-type-overview/) numeric data type (_which I'm assuming you're using_). So basically, any `ZEROFILL` column MUST BE too `UNSIGNED`.

So the following `CREATE TABLE` (without `UNSIGNED`):

```sql
CREATE TABLE `test` ( `column` INT(1) ZEROFILL NULL DEFAULT 0 );
#                                     ⤷ no UNSIGNED
```

Will be interpreted as (it will includes automatically the `UNSIGNED`):

```sql
CREATE TABLE `test` ( `column` INT(1) UNSIGNED ZEROFILL NULL DEFAULT 0 );
#                                     ↑↑↑↑↑↑↑↑
```

But, you said that when you are using `-1` as default value it will works. But it is incompatible with `ZEROFILL` that will not allow `-1` as default. So I am confusing here.

And if you are not using `ZEROFILL`, so you can't default value to `000000`.

Could you provide a step-by-step to I try to reproduce here?

Thanks!

**Comment by MRLBEL** [comment] 2019-05-15 02:29
Hi David,

 

Thank you for your fast response.

 

I want a field to be initialised to 0 but the field to be signed. HeidiSQL does not let me create a field with this unsigned attribute if the initial field value is 0.

 

As a test I set the field to be initialised to -1 .. this allowed me to create an unsigned field. 

 

“any ZEROFILL column MUST BE too UNSIGNED” … I really can’t accept this. If I have to set each individual field (345 of them) my code will be a kilometre long.

 

Thanks,

 

Mike

**Comment by rentalhost** [comment] 2019-05-15 04:25
Ok, I still can't reproduce it on **r5464** and **r5560**.

Could you provide a step-by-step to I try to reproduce here? Like "first you should click on X, then you click on Y, so you save", so on.

You are in MySQL/MariaDB or other DBMS? If yes, which?

And please check if you are running the last nightly version available.

**Comment by ansgarbecker** [comment] 2020-01-21 11:08
Assuming user wants to use unsigned + zerofill, which is [not supported in MariaDB](https://mariadb.com/kb/en/numeric-data-type-overview/#signed-unsigned-and-zerofill)

**Closed by ansgarbecker** 2020-01-21 11:08 UTC
Labels: needs-info
