### ISSUE TITLE
Access-Violation on editing a binary value

### ISSUE THREAD

**Issue by keydon** [HeidiSQL/HeidiSQL#1513] opened 2022-01-11 10:25 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6392 (64 bit)
* Database type and version: MariaDB Docker Container (10.5.8)
* OS: Windows/Docker

**Describe the bug**

Goal: Editing/Inserting a binary uuid value into a existing/new record
Expected: No Access-Violation-Dialog
Actual: It gets applied properly but you always have to click away this annoying access-violation dialog.

The bug is there for ages, but I recently got into the mood of actually reporting it :D

**To Reproduce**

1. double-click the target cell of type `BINARY (16)` -> a  "binary-editor" opens
2. paste in a uuid like `ABAB3DFF94204A9CACC51E0EC2E11531`
3. click apply -> Access-Violation

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/2421541/148924353-e071d2ee-d7f8-4a24-b9db-8449666641a6.png)

date/time          : 2022-01-11, 11:14:53, 892ms
computer name      : CAS-N00000
user name          : keydon <admin>
registered owner   : Setup
operating system   : Windows 10 x64 build 19042
system language    : German
system up time     : 21 days 16 hours
program up time    : 2 minutes 55 seconds
processors         : 12x Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
physical memory    : 56791/81662 MB (free/total)
free disk space    : (C:) 44,53 GB
display mode       : 1920x1080, 32 bit
process id         : $3adc
allocated memory   : 129,93 MB
largest free block : 131025,95 GB
executable         : heidisql.exe
exec. date/time    : 2022-01-11 11:11
version            : 11.3.0.6392
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.1
callstack crc      : $586c79bc, $e1bbfa39, $e1bbfa39
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000E93096 in module 'heidisql.exe'. Write of address 0000000000000080.

main thread ($5258):
00e93096 heidisql.exe grideditlinks    277  +2 TBaseGridEditorLink.Destroy
00e93be4 heidisql.exe grideditlinks    479  +1 THexEditorLink.Destroy
0041ad92 heidisql.exe System                   TInterfacedObject._Release
00418f7b heidisql.exe System                   @IntfClear
00981ee8 heidisql.exe VirtualTrees   20057 +28 TBaseVirtualTree.DoEdit
0097d406 heidisql.exe VirtualTrees   18053  +7 TBaseVirtualTree.WMTimer
0040f0a2 heidisql.exe System                   TObject.Dispatch
006df68d heidisql.exe Vcl.Controls             TControl.WndProc
006e68eb heidisql.exe Vcl.Controls             TWinControl.WndProc
00990aa3 heidisql.exe VirtualTrees   25876 +32 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes           StdWndProc
7ff819fc USER32.dll                            DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                TApplication.Run
01186f38 heidisql.exe heidisql         105 +41 initialization
7ff81a82 KERNEL32.DLL                          BaseThreadInitThunk
7ff81bbc ntdll.dll                             RtlUserThreadStart

**Comment by ansgarbecker** [comment] 2022-04-15 07:16
Duplicate of #1349

**Closed by ansgarbecker** 2022-04-15 07:16 UTC

**Comment by keydon** [comment] 2022-04-15 14:49
Always glad to be a duplicate of an one year old bug :)
