### ISSUE TITLE
[sqlite] Incorrect syntax for indexing

### ISSUE THREAD

**Issue by kinekt4** [HeidiSQL/HeidiSQL#1304] opened 2021-02-04 12:31 UTC
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: SQLite3
* OS: Windows 10 (64bit)

**Describe the bug**

The syntax for adding and deleting indexes on SQLite3 databases is incorrect

**To Reproduce**

1. Create new SQLite database
2. Open database
3. Add a table with multiple columns
4. Go to table tab
5. Add new index
6. Drag columns towards index
7. Click Save
8. Error

**Screenshots or Crash reports**

*Unique Multi column index*

    -- Heidisql (Incorrect)
    ALTER TABLE "table" ADD UNIQUE INDEX "my_index" ("col_1", "col_2", "col_3");
    -- SQLite (Correct)
    CREATE UNIQUE INDEX my_index on table (col_1, col_2, col_3);

*Drop Index*

    -- Heidisql (Incorrect)
    ALTER TABLE "table" DROP INDEX "my_index";
    -- SQLite (Correct)
    DROP INDEX "my_index"

**Comment by ansgarbecker** [comment] 2024-06-21 12:44
Duplicate of #1604.

Dropping index is discussed in #1605.

**Closed by ansgarbecker** 2024-06-21 12:44 UTC
Labels: bug, nettype-sqlite
