### ISSUE TITLE
Status panel readabily improvment

### ISSUE THREAD

**Issue by albertotn** [HeidiSQL/HeidiSQL#803] opened 2019-11-12 08:59 UTC
## Steps to reproduce this issue

1. Step 1; start heidiSQL
2. Step 2; look status panel on program's bottom of main windo

## Current behavior

Status information is cut on bottom part (dark gray is windows 10 application bar)

![immagine](https://user-images.githubusercontent.com/12526457/68656824-d5b2f400-0532-11ea-994d-af7f5ada8f88.png)

## Expected behavior

Status information shoul be readable

## Possible solution

A small "padding" should be used

## Environment

Windows 10

* **HeidiSQL version:** 
  

10.2.0.5745

**Comment by ansgarbecker** [comment] 2019-11-12 12:27
Duplicate of #483

**Closed by ansgarbecker** 2019-11-12 12:27 UTC
