### ISSUE TITLE
 The tree view closes all open branches after deleting an entry

### ISSUE THREAD

**Issue by patrick-fischer-hirschstein** [HeidiSQL/HeidiSQL#2028] opened 2024-10-04 06:12 UTC
**Is your feature request related to a problem? Please describe.**
The tree view closes all open branches after deleting an entry. I use the grouped view. So removing a view, Removing a view closes everything and I lose focus.

**Describe the solution you'd like**
The tree view retains the open branches and the scroll position does not change.

**Comment by ansgarbecker** [comment] 2024-10-04 06:40
Duplicate of #16

**Closed by ansgarbecker** 2024-10-04 06:40 UTC
