### ISSUE TITLE
Creating and handling generated columns fails

### ISSUE THREAD

**Issue by user7415** [HeidiSQL/HeidiSQL#778] opened 2019-10-24 10:06 UTC
## Steps to reproduce this issue

In table editor if you just modify a column in order to make it generated (changing the values of expression and virtuality from "" to some expression and "VIRTUAL")

## Current behavior

brings an error of 

SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS ... VIRTUAL AFTER `...`' at line 2

## Expected behavior

just works fine altering the table columns

## Possible solution

It seems that MODIFY COLUMN is the right syntax to use with 10.4.8-MariaDB versions

## Environment

10.4.8-MariaDB

* **HeidiSQL version:** 
  
* **Database system and version:** 
 10.4.8-MariaDB
* **Operating system:** 
 windows x64

**Comment by ansgarbecker** [comment] 2019-10-30 15:16
On my MariaDB 10.3 installation this works, and the query fired by HeidiSQL looks like this:

```sql
ALTER TABLE `foo`
	ADD COLUMN `virt` INT AS (1+2) VIRTUAL AFTER `lang`;
```

Please post what you entered in the expression field.

**Comment by sbiedrzycki** [comment] 2020-09-30 13:56
I believe I've encountered the same issue and narrowed down the root cause.  HeidiSQL version 11.0.0.6099, MariaDB 10.5.4.

The error seems to be in virtual columns defaulting to null but adding / modifying virtual columns does not support a default value.  The default must be explicitly marked as 'No Default' in the table editor before saving.

I created the following table with a virtual column with no default without issue.
```
CREATE TABLE `table_virtual_test` (
	`A` DOUBLE NULL DEFAULT NULL,
	`B` DOUBLE NULL DEFAULT NULL,
	`Virtual_C` DOUBLE AS (A + B) VIRTUAL
)
COLLATE='latin1_swedish_ci';
```
Once created, the table editor shows the virtual column as having a NULL default value so if you try to edit it the SQL to save generates this
```
ALTER TABLE `table_virtual_test`
	CHANGE COLUMN `Virtual_C` `Virtual_C` DOUBLE DEFAULT NULL AS (`A` + `B`) virtual COMMENT 'test' AFTER `B`;
```
and throws the OPs error.

Manually changing the NULL default back to No Default issues the correct SQL without the default and saves successfully.
```
ALTER TABLE `table_virtual_test`
	CHANGE COLUMN `Virtual_C` `Virtual_C` DOUBLE AS (`A` + `B`) virtual COMMENT 'test' AFTER `B`;
```
It would be preferable if the table presented the default as 'No Default' for virtual columns or otherwise excluded the default value when adding or editing virtual columns as it isn't supported.

**Comment by vituri** [comment] 2020-10-23 16:41
I confirm this bug. Any kind of editing in generated columns (or even copying a table with generated columns) will fail because of the default null. I'm using the newest Heidisql version, MariaDB 10.4.8.

If I select "no default value" when creating the column, it changes to NULL again. The create table code generated is this:
```CREATE TABLE test (
	`int1` INT(11) NULL DEFAULT NULL,
	`int2` INT(11) NULL DEFAULT NULL,
	`label` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sum` INT(11) DEFAULT NULL AS (`int1` + `int2`) stored
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB ```

**Comment by vituri** [comment] 2020-10-23 16:50
Some more details:
I deleted the column "sum" above and saved. Then, added a new column "sum" and this was the alter table code:

![image](https://user-images.githubusercontent.com/56522687/97031051-10d8e800-1536-11eb-9e59-49c0abf9b915.png)

After saving the column, the create table code is the following, with the default null:

```
CREATE TABLE `test` (
	`int1` INT(11) NULL DEFAULT NULL,
	`int2` INT(11) NULL DEFAULT NULL,
	`label` TEXT NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`sum` INT(11) DEFAULT NULL AS (`int1` + `int2`) stored
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
```

If I try to move up the column (to the third position instead of the forth) I get the following error:

![image](https://user-images.githubusercontent.com/56522687/97031198-4a115800-1536-11eb-8928-0624657479a9.png)

**Comment by ansgarbecker** [comment] 2020-10-24 09:59
Just wanted to make sure we're talking about the latest HeidiSQL build, not the last stable release?

**Comment by vituri** [comment] 2020-10-26 15:01
> Just wanted to make sure we're talking about the latest HeidiSQL build, not the last stable release?

I tried with both of them. Now I am using this version:

![image](https://user-images.githubusercontent.com/56522687/97189037-f0ea3400-1782-11eb-9f86-c4c560f4ef1b.png)

**Comment by lukinhaspm** [comment] 2020-10-26 15:18
I always have difficulties with these calculated columns, but I never know if it’s a syntax problem or if it’s Heidi, I’ve already noticed both, but I don’t have examples now.

**Comment by lukinhaspm** [comment] 2021-04-01 16:35
Today I tried again to see wy this problem, my test case:

```
CREATE TABLE `teste` (
	`Coluna 1` INT NULL,
	`Coluna 2` INT UNSIGNED AS (1+1) VIRTUAL
)
COLLATE='latin1_swedish_ci';
```
--------------------------------
Altering column.... Heidi generate this - error........:
```
ALTER TABLE `teste`
	CHANGE COLUMN `Coluna 2` `Coluna 2` INT(10) UNSIGNED DEFAULT NULL AS (1 + 1 + 1) virtual AFTER `Coluna 1`;
```
--------------------------------
I tried this form, and it's works fine
```
ALTER TABLE `teste`
	MODIFY `Coluna 2` INT(10) UNSIGNED AS (1 + 1 + 1) virtual AFTER `Coluna 1`;
```

Other softwares drop the virtual column and create again...

MariaDB 10.2.37
Heidi last build (6251)

**Comment by ansgarbecker** [comment] 2021-12-11 12:12
I think this is a duplicate of #1210 which I just fixed

**Closed by ansgarbecker** 2021-12-11 12:12 UTC
Labels: bug, needs-info, nettype-mysql
