### ISSUE TITLE
SSH Access for PostgreSQL

### ISSUE THREAD

**Issue by hvdboo** [HeidiSQL/HeidiSQL#254] opened 2018-04-27 10:42 UTC
Why is SSH to access a PostgreSQL database not an option?
The SSH part should be common, no?

**Comment by ansgarbecker** [comment] 2018-04-27 13:34
Because noone asked for it? And noone thought of it probably.

No reason for deleting the whole issue template, man!

**Comment by hvdboo** [comment] 2018-04-28 08:51
Which template? New to github, so if I did something wrong, tell me because I'm not aware.
Do you intend to add SSH access for PostgreSQL?
Thanks

**Comment by fnkr** [comment] 2019-02-20 21:15
I think this issue is a duplicate of #78.

**Comment by ansgarbecker** [comment] 2019-02-21 20:40
Indeed.

**Comment by ansgarbecker** [comment] 2019-06-08 06:57
I didn't get any feedback in #78 . So I thought I just ask here for someone who tries out the latest build with SSH/plink support for PostgreSQL?

**Comment by fnkr** [comment] 2019-06-08 08:18
Hi @ansgarbecker. Apparently I forgot to subscribe to the other issue. I've tested the build and it works for me. The only odd thing I've noticed is that when I changed the network type from "PostgreSQL (TCP/IP)" to "PostgreSQL (SSH tunnel)" the "User" field was reset to the default value "postgres". I can live with that, it just came unexpected and I had to look up the username again. Thanks for all your efforts, HeidiSQL is great, even on Linux!

**Comment by ansgarbecker** [comment] 2019-06-08 11:41
Ok, I just looked after that username switch. It's actually meant to change for a new connection, which is a MySQL/MariaDB session by default, so when you set it to PostgreSQL, HeidiSQL tries to be clever and use the DBMS's default user name. That's not right for existing connections, so I'm going to change that.

**Comment by ansgarbecker** [comment] 2019-06-09 07:30
Related pull request: #377

Next build should do that more clever: bda7b932d15ae2e20e310b6c3f2419c2d9b25583
Default username and port is now defined for MSSQL also, and applied only if the selected server type is not just a different sub type of the previously selected one.

**Closed by ansgarbecker** 2019-06-09 07:30 UTC
Labels: duplicate, enhancement

**Comment by fnkr** [comment] 2019-06-11 07:06
I tried build 10.1.0.5594 and it still happens if I change the network type of an existing connection from "PostgreSQL (TCP/IP)" to "PostgreSQL (SSH tunnel)".

**Comment by ansgarbecker** [comment] 2019-06-11 15:22
Hm, I cannot reproduce that here. Are you sure you did not change it from a non-Postgres connection?

**Comment by fnkr** [comment] 2019-06-19 12:43
Yes. I can reproduce the problem with this server config:

```
Servers\myservername\Comment<|||>1<|||>
Servers\myservername\Compressed<|||>3<|||>0
Servers\myservername\ConnectCount<|||>3<|||>3
Servers\myservername\Databases<|||>1<|||>mydbname
Servers\myservername\FullTableStatus<|||>3<|||>1
Servers\myservername\Host<|||>1<|||>127.0.0.1
Servers\myservername\KeepAlive<|||>3<|||>20
Servers\myservername\LastConnect<|||>1<|||>2019-05-23 16:45:06
Servers\myservername\lastUsedDB<|||>1<|||>public
Servers\myservername\LocalTimeZone<|||>3<|||>0
Servers\myservername\LoginPrompt<|||>3<|||>0
Servers\myservername\NetType<|||>3<|||>8
Servers\myservername\Password<|||>1<|||>786977784
Servers\myservername\Port<|||>1<|||>5432
Servers\myservername\QueryTimeout<|||>3<|||>30
Servers\myservername\ServerVersion<|||>3<|||>90516
Servers\myservername\ServerVersionFull<|||>1<|||>PostgreSQL 9.5.16 on amd64-portbld-freebsd11.2, compiled by FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0), 64-bit
Servers\myservername\SessionCreated<|||>1<|||>2019-04-02 15:28:54
Servers\myservername\SSHtunnelHost<|||>1<|||>
Servers\myservername\SSHtunnelHostPort<|||>3<|||>22
Servers\myservername\SSHtunnelPassword<|||>1<|||>2
Servers\myservername\SSHtunnelPort<|||>3<|||>10057
Servers\myservername\SSHtunnelPrivateKey<|||>1<|||>
Servers\myservername\SSHtunnelTimeout<|||>3<|||>4
Servers\myservername\SSHtunnelUser<|||>1<|||>
Servers\myservername\SSL_Active<|||>3<|||>0
Servers\myservername\SSL_CA<|||>1<|||>
Servers\myservername\SSL_Cert<|||>1<|||>
Servers\myservername\SSL_Cipher<|||>1<|||>
Servers\myservername\SSL_Key<|||>1<|||>
Servers\myservername\StartupScriptFilename<|||>1<|||>
Servers\myservername\TreeBackground<|||>3<|||>536870911
Servers\myservername\User<|||>1<|||>myusername
Servers\myservername\WindowsAuth<|||>3<|||>0
```
