### ISSUE TITLE
Display scaling messes up window

### ISSUE THREAD

**Issue by libeco** [HeidiSQL/HeidiSQL#424] opened 2018-12-04 09:48 UTC
## Steps to reproduce this issue

1. Step 1; Open HeidiSQL on my 4k laptop display with display scaling (all looks perfect).
2. Step 2; Drag it to secondary display (non 4k).
4. Then I get a HeidiSQL window where all text and buttons are too large. Only the window title looks correct.

## Current behavior

I get a HeidiSQL window where all text and buttons are too large. Only the window title looks correct.

## Expected behavior

This happens with releases since about two months. The September releases worked perfectly fine.

## Environment

* **HeidiSQL version:** 
  
Exists in at least 9.5.0.5313 until 9.5.0.5362
* **Operating system:** 
  
Windows 10 build 17134

**Comment by ansgarbecker** [comment] 2018-12-04 16:06
Duplicate of #378

**Closed by ansgarbecker** 2018-12-04 16:06 UTC
