### ISSUE TITLE
Opening user manager on a MS SQL 2017 server fails cause of missing stored procedure FLUSH

### ISSUE THREAD

**Issue by CrazyOrange** [HeidiSQL/HeidiSQL#1531] opened 2022-02-09 18:40 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6408
* Database type and version: MS SQL Server 14.0.2027.2
* OS: Windows 10

**Describe the bug**
I get the following error when trying to opening the user manager:
SQL Error (2812): Could not find stored procedure "FLUSH"

**To Reproduce**
Open the user manager

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/7329437/153267809-30d42df1-3f57-4a37-8133-509f32a71313.png)

**Comment by ansgarbecker** [comment] 2022-02-09 19:36
Duplicate of #17

**Closed by ansgarbecker** 2022-02-09 19:36 UTC
