### ISSUE TITLE
exception: remove the last sorting entry in in sorting dropdown dialog in table tab

### ISSUE THREAD

**Issue by waldmeisterx** [HeidiSQL/HeidiSQL#1909] opened 2024-02-20 14:56 UTC
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MySQL 8.0.18 and 8.0.31 (tested), maybe more 8.x versions)
* OS: Windows 11 x64 build 22621

**Describe the bug**

An exception occurs when removing the last sorting entry in the sorting dropdown dialog in table tab.
Removing other sorting entries than the last one works fine.

**To Reproduce**

1. select any table
2. select data tab
3. add 2 or more ssortings to the table (e.g. with table headers)
4. open sorting dropdown on top of data tab
5. remove the sortings with the "X" one by one
6. on removing of the last soring the exception occurs

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/2168391/a624e945-c815-484b-bcf8-c3dd0fe00fe7)
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/14346056/bugreport.txt)

**Comment by ansgarbecker** [comment] 2024-02-20 20:13
Duplicate of #520

Already fixed that some weeks ago. Please update to the latest build or wait for the next official release.

**Closed by ansgarbecker** 2024-02-20 20:13 UTC
