### ISSUE TITLE
Ctrl + Backspace in Textboxes: delete whole word, not add rectangle

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#144] opened 2018-02-18 21:46 UTC
## Steps to reproduce this issue

1. type two search terms in database or table filter
2. separate them with some regex (I often use `pipe`)
3. remove the filter with `Ctrl + backspace` to delete entire word

## Current behavior

at present `Ctrl + backspace` will write a rectangle ``

## Expected behavior

the entire word in front of the cursor is removed
this works well in the query editor or quick filters (multi line text boxes)

### Other areas
this could be applied in most textboxes but won't be as relevant. See table tabs in Basic, Options, Indexes and Foreign keys. I suppose it's the same issue as in Win Forms; all Textboxes show this behaviour. If it only deleted one letter but adding a box is just weird. 

## Possible solution

* I know this from WinForms where I have to check the keys typed and then remove the last word manually up and including the next non-letter and non-digit character from the end
* see [answer by Patrick McDonald](https://stackoverflow.com/a/1125081) to get some idea how this could be fixed manually

## Environment

* **HeidiSQL version:** 
  9.5.0.5253
* **Operating system:** 
  Win 10 1709

**Comment by WesleyM77** [comment] 2019-02-06 16:13
I don't think this is an issue anymore in the latest version.  Can you still recreate it?

**Comment by penCsharpener** [comment] 2019-02-07 14:06
yes, I'm always using the latest nightly and it's still there. It's not in the Query tab textbox but all the text fields like search.
![2019-02-07_15-05-30 heidisql](https://user-images.githubusercontent.com/26190934/52416438-df15b880-2ae9-11e9-859b-f9e24a94de18.gif)

**Comment by okneloper** [comment] 2019-05-14 08:18
Still an issue in 5565. It would be a nice little enhancement!

**Comment by decadence** [comment] 2019-09-25 08:59
Same for me.
And I want to add that `Ctrl+Delete` doesn't work in Query tab (but works in other inputs). It should delete word from the right side of a cursor.

**Comment by ansgarbecker** [comment] 2019-09-25 11:43
> And I want to add that Ctrl+Delete doesn't work in Query tab (but works in other inputs)

How can it be you're experiencing the exact opposite than the other reporters here? Maybe on Wine?

**Comment by decadence** [comment] 2019-09-25 11:45
No, I'm on Windows 10.
Seems like you misread my message. I told about `Ctrl+Delete`. `Ctrl+Backspace` issue is still there for me.

**Comment by ansgarbecker** [comment] 2019-09-25 14:54
Yes, I misread that. Indeed, I can confirm that <kbd>Ctrl+Backspace</kbd> does not work in single line edit-boxes, and <kbd>Ctr+Delete</kbd> does not work in SQL areas.

**Comment by ansgarbecker** [comment] 2019-09-25 14:58
Though SynEdit supports that "delete next word" - by default it has <kbd>Ctrl+Shift+Delete</kbd>. You can change that in Tools > Preferences > Shortcuts > SQL editing:
![grafik](https://user-images.githubusercontent.com/7986591/65613083-ab729a80-dfb5-11e9-8805-2118b7a3eaf7.png)

**Comment by decadence** [comment] 2019-09-25 15:22
Thanks.
But it's strange default shortcut because all text editors use Ctrl+Delete.

**Comment by ansgarbecker** [comment] 2019-09-25 15:32
According to the [relevant line in SynEdit](https://github.com/SynEdit/SynEdit/blob/0b43ec1a701ddafd85eff858ee63b4a3083ce602/Source/SynEditKeyCmds.pas#L853) this is by default <kbd>Ctrl+T</kbd>, which is overridden by HeidiSQL for "new tab". I'm scratching my head where this <kbd>Ctrl+Shift+Delete</kbd> comes from.

**Comment by decadence** [comment] 2019-09-25 15:45
Is there any chance to make Ctrl+Delete default for consistency with other editors?

**Comment by ansgarbecker** [comment] 2019-09-25 18:17
Yes, I can try to initialize it by default to that.

**Comment by decadence** [comment] 2019-09-25 18:19
Thanks 👏

**Comment by ansgarbecker** [comment] 2019-09-25 18:43
I just pushed a few changes, which should enable <kbd>Ctrl+Backspace</kbd> on most (if not all) edit boxes in HeidiSQL. This implements a workaround I found [here](https://stackoverflow.com/questions/10305634/ctrlbackspace-in-delphi-controls), though it works very good for me here. For those who want to check, please wait half an hour and download the next build.

**Comment by penCsharpener** [comment] 2019-09-25 18:55
yes, it works. Thanks so much.

**Comment by ansgarbecker** [comment] 2019-09-26 17:20
New default shortcut for "delete next word" in the next build is changed from ~~Ctrl+T~~ to <kbd>Ctrl+Del</kbd>.

No complaints so far, so I'll close this issue. Please shout if I am missing something.

**Comment by ansgarbecker** [comment] 2019-09-27 13:35
Shit: The popup text editor now does not accept the <kbd>Enter</kbd> key - instead it selects the text.

**Comment by ansgarbecker** [comment] 2019-09-28 14:45
Next build leaves that hack away for multi-line memos, for which the Enter key was broken. I have no clue how to fix that Ctrl+Backspace for these.

**Comment by decadence** [comment] 2019-10-03 13:37
@ansgarbecker I found another strange default hot key: why default key for Undo is `Alt+Backspace` and not `Ctrl+Z` as in all programs in the world? :)
In Query tab `Ctrl+Z` cancels only few steps. `Alt+Backspace` works normal.

**Comment by ansgarbecker** [comment] 2019-10-08 17:28
Unfortunately, I had to revert my previous solution for supporting <kbd>Ctrl+Backspace</kbd>. This introduced too many new bugs. I will have to find a better one.

**Comment by ansgarbecker** [comment] 2019-10-19 12:14
Just pushed a new attempt to support <kbd>Ctrl+Backspace</kbd>, using an application wide `OnShortCut` event:
* works in all one-line edit controls, multi-line editors and editable comboboxes
* does not break <kbd>Enter</kbd> key in multi-line editors
* does not break <kbd>Tab</kbd> key in grid field editors
* new issue: breaks undo history :/

Works well enough for me. No clue how to fix the undo issue though.

Could someone please test the new build?

**Comment by ansgarbecker** [comment] 2019-10-19 15:01
* undo works, now that i delete the word via `EM_REPLACESEL` message

**Closed by ansgarbecker** 2019-10-19 15:01 UTC
Labels: bug, confirmed
