### ISSUE TITLE
plink.exe wrong passphrase although session started

### ISSUE THREAD

**Issue by Pomodorka3** [HeidiSQL/HeidiSQL#1932] opened 2024-04-02 11:56 UTC
**Preconditions**

* HeidiSQL version: 12.1.0.6537 (64 bit)
* Database type and version: 10.11.7-MariaDB-1:10.11.7+maria~deb11
* OS: Windows 11 (64 bit)

**Describe the bug**

I am using SSH tunnel to connect to remote DB. SSH executable plink.exe is used win my private key. I click on saved configured session and passphrase is promted. Aftery typing correct passphrase, I receive error window "Wrong passphrase" although after closing that error window, I am successfully logged into my remote DB.

**To Reproduce**

1. Configure session via SSH Tunnel with private key.
2. Click 'open' in session manager window.
3. Enter your passphrase.
4. You get error window, although your session was successfully set up.

**Screenshots or Crash reports**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/43012626/c58b76a0-eccd-4835-b151-831bf64a1336)

**Comment by ansgarbecker** [comment] 2024-04-16 14:38
Duplicate of #1838

**Closed by ansgarbecker** 2024-04-16 14:38 UTC
