### ISSUE TITLE
utf8mb4_unicode_ci converts to utf8mb4_general_ci

### ISSUE THREAD

**Issue by MarcTCruz** [HeidiSQL/HeidiSQL#1176] opened 2020-09-29 20:45 UTC
**Describe the bug**
If flag **Convert data** is set when using utf8mb4_unicode_ci, data is saved to utf8mb4_general_ci instead.
It converts correctly if **Convert data** flag is not used.

**To Reproduce**
Table > Options I select utf8mb4_unicode_ci and flag **Convert data**
Heidi converts everything to utf8mb4_general_ci instead.

**Expected behavior**
Expected table and columns to be utf8mb4_unicode_ci.

**Environment:**
 - OS: [e.g. Windows 10]
 - HeidiSQL version [e.g. 11.0.0.6099]
 - Database type and version [MariaDB 10.5.4]

**Comment by ansgarbecker** [comment] 2020-09-30 06:06
Please paste a part of the SQL log queries here, so we can find out what's wrong.

**Comment by MarcTCruz** [comment] 2020-09-30 19:31
`SHOW CREATE TABLE `test`.`usuario`;
ALTER TABLE `usuario`
	COLLATE='SHOW CREATE TABLE `test`.`usuario`;
ALTER TABLE `usuario`
	COLLATE='utf8mb4_unicode_ci',
	CONVERT TO CHARSET utf8mb4;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='test';
SHOW TABLE STATUS FROM `test`;
SHOW FUNCTION STATUS WHERE `Db`='test';
SHOW PROCEDURE STATUS WHERE `Db`='test';
SHOW TRIGGERS FROM `test`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='test';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='test' AND TABLE_NAME='usuario' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `usuario` FROM `test`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='test'   AND TABLE_NAME='usuario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='test'   AND TABLE_NAME='usuario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* Entering session "Unnamed" */
SHOW CREATE TABLE `test`.`usuario`;',
	CONVERT TO CHARSET utf8mb4;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='test';
SHOW TABLE STATUS FROM `test`;
SHOW FUNCTION STATUS WHERE `Db`='test';
SHOW PROCEDURE STATUS WHERE `Db`='test';
SHOW TRIGGERS FROM `test`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='test';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='test' AND TABLE_NAME='usuario' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `usuario` FROM `test`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='test'   AND TABLE_NAME='usuario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='test'   AND TABLE_NAME='usuario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* Entering session "Unnamed" */
SHOW CREATE TABLE `test`.`usuario`;`

**This is what is logged when I flag the _Convert Data_ checkbox makes data utf8mb4_general_ci instead of utf8mb4_unicode_ci**

**Before save**
https://ibb.co/CHH9mWT

**After save:**
https://ibb.co/0B0QMz4

**Comment by ansgarbecker** [comment] 2024-11-19 09:51
Duplicate of #1586 which I solved in 4c07c3641175eb599a406a6db825b18940cd99f3 for v12.7

**Closed by ansgarbecker** 2024-11-19 09:51 UTC
