### ISSUE TITLE
HeidiSQL doesn't support/advertise TLS 1.1 / 1.2 with MS SQL Server connection

### ISSUE THREAD

**Issue by SilmorSenedlen** [HeidiSQL/HeidiSQL#237] opened 2018-04-19 18:24 UTC
## Steps to reproduce this issue

1) On the server side disable support TLS 1.1 and TLS 1.2 for server role in SCHANNEL(Windows Crypto) via registry:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
"Enabled"=dword:ffffffff
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
"Enabled"=dword:00000000
"DisabledByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
"Enabled"=dword:00000000
"DisabledByDefault"=dword:00000001
```
2)  Reboot OS
3) Try to connect to MS SQL Server via HeidiSQL

## Current behavior

HeidiSQL only advertiseTLS version 1.0 (0x0301) for MS SQL Server connection and therefore can't connect to SQL Server when only more secure protocol versions are supported in server side(TLS 1.1 and/or TLS 1.2).

(Can't upload files to github because of mad russian's government, which blocked 0,4% of all Internet IPs in stupid attempt to block Telegram. >>wall  Sorry for links on sreenshots)

> SQL Error (18): [DBNETLIB][ConnectionOpen (SECDoClientHandshake()).]SSL Security error.

[TLS_over_TDS_(HeidiSQL)](https://vats-on.bitrix24.ru/~C3zQu)

## Expected behavior

HeidiSQL should advertise maximum supported TLS version 1.2 (0x0303) for MS SQL Server connection.

******

Connection successful established when using SQL Server Management Studio 17.6 via TLS 1.2 (0x0303)

[TLS_over_TDS_(SSMS_17.6)](https://vats-on.bitrix24.ru/~0Egs4)

## Possible solution

It is suspected that the component that HeidiSQL uses to connect to MS SQL Server only supports TLS version 1.0.
The most similar description of this error, that specifying the reasons I have found in the last message on this[link](https://forums.iis.net/t/1233674.aspx?connecing+SQL+server+DB+issue+after+installingTLS1+2+in+SQL+srver+with+classic+asp+application+).
If this is the case, it should upgraded or replaced with component that support TLS 1.2, if it possible.

## Environment

* **HeidiSQL version:** 
9.5.0.5196 (x86) & 9.5.0.5277 (x64)

* **Database system and version:** 
Microsoft SQL Server 2016 (SP1-CU8) (KB4077064) - 13.0.4474.0 (X64) 
Feb 24 2018 13:53:17 
Express Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

* **Operating system:** 
Windows 7 Professional SP1 (x64)

**Comment by lipnitsk** [comment] 2018-04-25 17:03
See https://support.microsoft.com/en-us/help/3135244/tls-1-2-support-for-microsoft-sql-server

The old provider is no longer supported by Microsoft - see [here](https://docs.microsoft.com/en-us/sql/ado/guide/appendixes/microsoft-ole-db-provider-for-sql-server?view=sql-server-2017):
```
NOTE: It is not recommended to use this driver for new development. The new OLE DB provider is called the Microsoft OLE DB Driver for SQL Server (MSOLEDBSQL) which will be updated with the most recent server features going forward.
```

New driver is available [here](https://docs.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server?view=sql-server-2017).

https://github.com/HeidiSQL/HeidiSQL/blob/8202e76b928516a3264a3598cbeecf3305ff8d0c/source/dbconnection.pas#L1861

**Comment by lipnitsk** [comment] 2018-07-03 23:31
@ansgarbecker any chance on looking at this issue? Can't use HeidiSQL at all on TLS 1.2 enabled MS SQL connections..

**Comment by SilmorSenedlen** [comment] 2018-07-04 09:24
Really need this change : /

**Comment by njbelf** [comment] 2018-10-30 20:07
Would like to add my 2 cents to this.  HeidiSQL cannot connect to any TLS 1.2 enabled MS SQL.

**Comment by lipnitsk** [comment] 2018-10-30 21:05
@ansgarbecker If the issue is testing, maybe you could provide a test build with the change from #256 and we can test it in this thread?

**Comment by ansgarbecker** [comment] 2018-10-31 06:32
Sorry for the long delay.
I just accepted your pull request. Please test after updating to the new build (will be ready in ~30 minutes)

**Comment by igitur** [comment] 2018-11-02 09:54
This change broke my connectivity. I now get this when attempting to connect to any MS SQL server. 
![image](https://user-images.githubusercontent.com/145854/47908493-f9f6e200-de95-11e8-8cd9-01106df6a45a.png)

Am I supposed to install some other driver on my own?

**Comment by igitur** [comment] 2018-11-02 09:59
Solved this by installing https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730

I suggest a friendlier error message to inform the users. I don't think it's correct to assume that everyone has this new driver pre-installed.

**Comment by ansgarbecker** [comment] 2018-11-03 11:41
Ok, then I need to detect that special error message, which most likely gets translated into the user's OS language. This, and the fact that there is no error number, makes it impossible to detect it, in order to show a more helpful message. But probably I can track the error down to a certain exception type. Will check that.

**Comment by ansgarbecker** [comment] 2018-11-03 11:48
Is there some way to detect which provider is installed and which is not, on the user's OS?

**Comment by igitur** [comment] 2018-11-03 12:01
@ansgarbecker Try this: https://stackoverflow.com/a/51738240/179494

**Comment by igitur** [comment] 2018-11-03 12:07
Alternatively you can check the registry, but you'll have to get the GUIDs for each provider. https://stackoverflow.com/a/154559/179494

**Comment by ansgarbecker** [comment] 2018-11-03 17:18
Just committed an automatic fallback to SQLOLEDB when MSOLEDBSQL is not available.
For such cases, I also added a notice to the log panel, with a link to the OLE DB driver.

**Closed by ansgarbecker** 2018-11-03 17:18 UTC

**Comment by ScottRFrost** [comment] 2019-01-24 18:51
FYI this error still exists (my SQL servers are set to TLS 1.2 only) on the new 10.0 version, but https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730 still fixes it.

Perhaps list this link on the HeidiSQL download page or automatically suggest it when the error occurs?

**Comment by ansgarbecker** [comment] 2019-01-26 18:21
Fair nuff - just placed that note on the download page.

**Comment by igitur** [comment] 2019-03-26 12:44
@ansgarbecker After the change to the new driver, I can't connect to SQL Express databases anymore, e.g. typically the host name is `localhost\sqlexpress`. Has anyone else mentioned this?

**Comment by SilmorSenedlen** [comment] 2019-03-26 12:52
@igitur 
I think that, first it's need at least an error code and its description.

**Comment by igitur** [comment] 2019-03-26 13:02
![image](https://user-images.githubusercontent.com/145854/54998995-0e1fb500-4fd8-11e9-8a9a-88fa2f531cf0.png)

![image](https://user-images.githubusercontent.com/145854/54999021-1677f000-4fd8-11e9-9c83-3e704d6704b3.png)

Worked perfectly up until v9.5 as far as I can tell.

**Comment by igitur** [comment] 2019-03-26 13:06
@ansgarbecker Let me know if I must log a full new issue.

**Comment by ansgarbecker** [comment] 2019-03-26 19:37
@igitur please file a new issue.

**Comment by igitur** [comment] 2019-03-29 10:00
I created #587  to address this.

**Comment by warrenlbrown** [comment] 2019-06-24 17:32
Ditto. I continue to have problems also.

**Comment by ansgarbecker** [comment] 2019-06-24 18:49
@warrenlbrown did you install the updated [OLE DB driver for SQL Server](https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730), like stated on the download page? If yes, you should probably file a new issue so we can discuss this from the scratch.

**Comment by ansgarbecker** [comment] 2019-07-28 10:29
I moved the new "Library" setting up and provide available + compatible ADO providers in that dropdown box. Default is the new MSOLEDB provider, but the use may also select the old one, which then issues a warning dialog when connecting:

![grafik](https://user-images.githubusercontent.com/7986591/62005410-1a0cb680-b133-11e9-9ffb-9a8e3f0570ef.png)

Previously, this warning was burried in the log panel, so even I did not realize it.

**Comment by gitowiec** [comment] 2020-01-02 11:31
I am on Linux (Ubuntu 18.04) with Wine stable (4.0.3) 32bit. How I can install this provider?

**Comment by wflorentino** [comment] 2023-07-26 14:48
Bom dia! Para corrigir somente instalar "msoledbsql" link https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730 Fechar o HeidiSQL e abrir novamente.

PROBLEMA:
![Arquivo01  problema](https://github.com/HeidiSQL/HeidiSQL/assets/66322305/6de0a452-ded3-4e72-bc31-890bedae600f)

SOLUÇÃO:
![Arquivo02  Solução](https://github.com/HeidiSQL/HeidiSQL/assets/66322305/8e5becd2-e53e-4c70-9629-d58bb0739e63)

**Comment by patelriki13** [comment] 2025-04-17 06:26
> Bom dia! Para corrigir somente instalar "msoledbsql" link https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730 Fechar o HeidiSQL e abrir novamente.


New link: https://learn.microsoft.com/en-us/sql/connect/oledb/oledb-driver-for-sql-server?view=sql-server-ver16
