### ISSUE TITLE
Format JSON in column popup editor

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#1679] opened 2022-10-07 09:38 UTC
**Is your feature request related to a problem? Please describe.**
When open a JSON field in popup editor, it is difficult to edit the unformatted JSON value.

**Describe the solution you'd like**
It would be nice to have a button to re-format the JSON value.

**Describe alternatives you've considered**
Similar to popup editor, there could be a "view popup" button or menu item in the right click menu, that opens a viewer, with a reformat button or automatically reformats.

**Additional context**
Auto formatting feature also can be added, if the column type is JSON and in the settings user turns on that feature, then popup editor reformats the value immediately after open.

![image](https://user-images.githubusercontent.com/840604/194520328-dd0d36b5-83a6-4d77-8b41-210de3ca60d8.png)

**Comment by ansgarbecker** [comment] 2022-10-07 12:01
Duplicate of #1669
Please update to the latest nightly build - it already has exactly what you describe here, for JSON and XML as well:

![grafik](https://user-images.githubusercontent.com/7986591/194548155-1d415249-b67c-40f4-8bdc-58f543e12efd.png)

**Closed by ansgarbecker** 2022-10-07 12:01 UTC

**Comment by ansgarbecker** [comment] 2022-10-07 12:03
Please note: you need to select the JSON highlighter to give Heidi a hint to the right reformatter.

**Comment by endo64** [comment] 2022-10-10 07:17
Thanks, updated to nightly build, JSON formatter works!
