### ISSUE TITLE
SQLServer incompatible query when include LEFT

### ISSUE THREAD

**Issue by VikIborra** [HeidiSQL/HeidiSQL#1170] opened 2020-09-25 17:28 UTC
**Describe the bug**
1. connect sqlserver
2. show structure a table
![image](https://user-images.githubusercontent.com/12858394/94297507-e4e13b80-ff64-11ea-9b0b-ab3112ce6611.png)
3. show data of table
When browse data table, shows a query SELECT TOP 1000  "PART_Id",  "PART_CLIE_Id",  "PART_Nombre",  "PART_Inquiero_Id", **LEFT**("PART_Observaciones", 256)   FROM "CORE_Partners";
but produce an error.
![image](https://user-images.githubusercontent.com/12858394/94297272-8ae07600-ff64-11ea-98de-4d1aa378ca97.png)

LEFT is incompatible and not show data in tab. 

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.0.0.6098
 - Database type: Microsoft SQL Server 2012 (SP4-GDR) (KB4532098) - 11.0.7493.4 (X64) 
	Dec 24 2019 19:33:24 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by ansgarbecker** [comment] 2020-09-25 17:36
Duplicate of #1136

**Closed by ansgarbecker** 2020-09-25 17:36 UTC
