### ISSUE TITLE
DATETIME field - ON UPDATE CURRENT_TIMESTAMP disappears after altering table

### ISSUE THREAD

**Issue by tencrocs** [HeidiSQL/HeidiSQL#336] opened 2018-08-29 06:28 UTC
## Steps to reproduce this issue

1. Step 1; Right click then Edit any table that has a datetime field.
2. Step 2; Set a default custom value 0000-00-00 00:00:00.
3. Step 3; Check ON UPDATE CURRENT_TIMESTAMP.
4. Step 4; Hit Save button.
4. Then I get...

## Current behavior

Editing default value
![screenshot_1](https://user-images.githubusercontent.com/9224421/44769146-39ebd100-ab96-11e8-889f-13c42d662637.png)

Before hitting Save button
![screenshot_2](https://user-images.githubusercontent.com/9224421/44769158-453efc80-ab96-11e8-9852-c7f124223f17.png)

After hitting Save button 
![screenshot_3](https://user-images.githubusercontent.com/9224421/44769417-1f662780-ab97-11e8-93ca-7066aeaba09e.png)

## Expected behavior

The ON UPDATE CURRENT_TIMESTAMP should not disappear as it will create an issue if not noticed.

## Environment

* **HeidiSQL version:** 
  9.5.0.5289
* **Database system and version:** 
  MariaDB 10.1.26-MariaDB-0+deb9u1
* **Operating system:** 
  Windows 7 32Bit

**Comment by ansgarbecker** [comment] 2019-04-22 12:36
I recently added support for expressions in the column default editor, and tested various scenarios. Could you please update to the latest build and report back whether the issue persists.

**Comment by ansgarbecker** [comment] 2019-04-22 12:38
See issue #74

**Comment by ansgarbecker** [comment] 2019-05-01 06:24
Cannot reproduce this issue with the latest build.
Definition stays the same with an ON UPDATE clause:

    `ts` TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE current_timestamp()

Closing due to no feedback.

**Closed by ansgarbecker** 2019-05-01 06:24 UTC
Labels: bug, mysql, needs-info
