### ISSUE TITLE
Heidy - show column define as XML

### ISSUE THREAD

**Issue by ZUFMON** [HeidiSQL/HeidiSQL#691] opened 2019-06-25 16:08 UTC
I'm using the MS SQL Database
 In management studio create column in table define as XML.
insert xml data into column.

When is showing  data from table in Heidy the application crash.

This is the crash log from HeidySQL

date/time          : 2019-06-25, 17:59:22, 238ms
computer name      : DESKTOP-KKSSA
user name          : BUBLA
registered owner   : Windows User
operating system   : Windows 10 x64 build 17134
system language    : English
system up time     : 5 hours 45 minutes
program up time    : 57 seconds
processors         : 8x Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
physical memory    : 17998/32403 MB (free/total)
free disk space    : (C:) 47,89 GB
display mode       : 3072x1728, 32 bit
process id         : $4e2c
allocated memory   : 208,66 MB
largest free block : 131021,96 GB
executable         : heidisql.exe
exec. date/time    : 2019-06-11 11:14
version            : 10.1.0.5594
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $ade57f98, $580ac76e, $f013efc0
exception number   : 1
exception class    : EOleException
exception message  : Multiple-step operation generated errors. Check each status value.

main thread ($1cf4):
00ab07e2 heidisql.exe Data.Win.ADODB            TCustomADODataSet.GetFieldData
00a5f360 heidisql.exe Data.DB                   TField.GetData
00a67819 heidisql.exe Data.DB                   TDateTimeField.GetValue
00a676f5 heidisql.exe Data.DB                   TDateTimeField.GetText
00a67638 heidisql.exe Data.DB                   TDateTimeField.GetAsString
00a5ee39 heidisql.exe Data.DB                   TField.GetAsAnsiString
00b0f65d heidisql.exe dbconnection    6299  +18 TAdoDBQuery.Col
00dcfd83 heidisql.exe Main            9011  +43 TMainForm.AnyGridGetText
0094a036 heidisql.exe VirtualTrees   33939   +8 TCustomVirtualStringTree.DoGetText
00948923 heidisql.exe VirtualTrees   33413   +4 TCustomVirtualStringTree.GetText
00949f53 heidisql.exe VirtualTrees   33923  +27 TCustomVirtualStringTree.DoGetNodeWidth
00939c18 heidisql.exe VirtualTrees   26979  +85 TBaseVirtualTree.GetDisplayRect
00dd28d9 heidisql.exe Main            9562  +28 TMainForm.AutoCalcColWidth
00dbb33b heidisql.exe Main            5295 +174 TMainForm.DataGridBeforePaint
00926969 heidisql.exe VirtualTrees   19330   +2 TBaseVirtualTree.DoBeforePaint
0094008b heidisql.exe VirtualTrees   30276   +5 TBaseVirtualTree.PaintTree
00931887 heidisql.exe VirtualTrees   23761  +23 TBaseVirtualTree.Paint
006b2096 heidisql.exe Vcl.Controls              TCustomControl.PaintWindow
006a8e73 heidisql.exe Vcl.Controls              TWinControl.PaintHandler
006a9b8f heidisql.exe Vcl.Controls              TWinControl.WMPaint
006b2028 heidisql.exe Vcl.Controls              TCustomControl.WMPaint
009228fd heidisql.exe VirtualTrees   17509   +8 TBaseVirtualTree.WMPaint
0040e9d2 heidisql.exe System                    TObject.Dispatch
006a1f2d heidisql.exe Vcl.Controls              TControl.WndProc
006a8bea heidisql.exe Vcl.Controls              TWinControl.WndProc
00936478 heidisql.exe VirtualTrees   25582  +32 TBaseVirtualTree.WndProc
006a7e1a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0055c623 heidisql.exe System.Classes            StdWndProc
7ffbbfac ntdll.dll                              KiUserCallbackDispatcher
7ffbbd8d USER32.dll                             DispatchMessageW
0084e16e heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0084e1e3 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0084e631 heidisql.exe Vcl.Forms                 TApplication.Run
00deed75 heidisql.exe heidisql          86  +27 initialization
7ffbbcf8 KERNEL32.DLL                           BaseThreadInitThunk
7ffbbfaa ntdll.dll                              RtlUserThreadStart

main thread ($1cf4), inner exception level 1:
>> EOleException, Multiple-step operation generated errors. Check each status value
00ab07e2 heidisql.exe Data.Win.ADODB        TCustomADODataSet.GetFieldData
7ffbbd8e USER32.dll                         GetMessageW
004ef878 heidisql.exe madExcept             HandleException
004fb7e1 heidisql.exe madExcept             InterceptAHandleExcept
006a7e3e heidisql.exe Vcl.Controls          TWinControl.MainWndProc
0055c623 heidisql.exe System.Classes        StdWndProc
7ffbbfac ntdll.dll                          KiUserCallbackDispatcher
7ffbbd8d USER32.dll                         DispatchMessageW
0084e16e heidisql.exe Vcl.Forms             TApplication.ProcessMessage
0084e1e3 heidisql.exe Vcl.Forms             TApplication.HandleMessage
0084e631 heidisql.exe Vcl.Forms             TApplication.Run
00deed75 heidisql.exe heidisql       86 +27 initialization
7ffbbcf8 KERNEL32.DLL                       BaseThreadInitThunk
7ffbbfaa ntdll.dll                          RtlUserThreadStart

**Comment by ansgarbecker** [comment] 2019-06-25 20:57
I highly suppose this is a duplicate of #423 . Please read that and probably attach the crash report there, if it's not already the same.

**Closed by ansgarbecker** 2019-06-25 20:57 UTC
