### ISSUE TITLE
Some buttons don't render properly (in Wine), and appear blank.

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#767] opened 2019-10-09 23:05 UTC
## Steps to reproduce this issue

1. Install Heidi in MacOS using Wine
2. Open Heidi
3. Open Session Manager

## Current behavior

Some buttons at the bottom don't render properly and show like empty spaces:

![image](https://user-images.githubusercontent.com/13773388/66525912-9a994d00-eabc-11e9-9839-9cf98bc6a4e4.png)

## Expected behavior

All buttons should render properly.
I found this image showing the correct rendering:

![image](https://user-images.githubusercontent.com/13773388/66526005-ddf3bb80-eabc-11e9-9c9f-252ca065800f.png)

## Possible solution

Those particular buttons have a drop-down icon, so that may be the reason they not render properly in Wine.

---

Note that despite the buttons themselves don't render properly, clicking on them (or the area they should be in) do have effect:

Clicking on the New (leftmost) button, immediately adds a new entry in the sessions list. I don't remember if that is the intended behavior, or if it should show a drop-down menu. I kindda remember there was a 'clone' or 'copy' option, but I'm not sure.

On the other hand, clicking on the More (rightmost) button, it does show the contextual menu:

![image](https://user-images.githubusercontent.com/13773388/66526137-3f1b8f00-eabd-11e9-8796-06a3558e8d13.png)

Also I don't know since when this bug started happening, because it is an option I don't use frequently, but I am almost sure it worked fine in 9.x versions of heidi

## Environment

* **HeidiSQL version:** 10.2.0.5703
  
* **Operating system:** MacOS 10.13.6 (High Sierra)
  

* **Wine version:** wine-1.8.3

Also, I am using the default 'Windows' theme, because all others seem to simply not work in Wine.

**Comment by ansgarbecker** [comment] 2019-10-10 04:39
This was reported and attempted to work around several times already.

* related issue: #94 
* related commits:
  * becd4bdd0e3845f9ad7845fe7637460914878afa
  * 61202be058cc135f938a131207f47f9546efff26
  * f7b4d0c0b82f12e948d2c56df859243f1334a80c

**Comment by ansgarbecker** [comment] 2019-10-10 06:46
Are you sure about your Wine version? I thought Wine is at 4.x already? Perhaps update Wine to see if that makes a difference.

**Comment by yphastos** [comment] 2019-10-10 14:20
Yes, I'm sure about Wine version, but had no idea I was so behind!

I see they are in fact at 4.x, and that it doesn't currently work in Catalina, glad I'm still at High Sierra.

I'll try to update it and see if it works, although it could take me a few days to get to it.
I'll let you know.

Thanks!

**Comment by yphastos** [comment] 2019-10-11 15:00
Update.

I've updated my Wine to the latest stable version (v4.0.2), and now the buttons show text correclty, but still don't show the little dropdown triangle:

![image](https://user-images.githubusercontent.com/13773388/66661097-06d69680-ec0c-11e9-9514-5f71ff49cfb1.png)

BUT, now some of the icons on the main toolbar appear blank:

![image](https://user-images.githubusercontent.com/13773388/66661023-dbec4280-ec0b-11e9-9624-d42849fcf14e.png)

I've noticed that if the buttons are enabled, depending on the actions, they do show a correct colored icon:

e.g. when selecting any cell in a result set:
before (no cell selected):
![image](https://user-images.githubusercontent.com/13773388/66661666-ff63bd00-ec0c-11e9-97cd-f39cb9769b1f.png)

after:
![image](https://user-images.githubusercontent.com/13773388/66661690-08ed2500-ec0d-11e9-9ad5-9818597b9ab6.png)

So I guess the problem is just for 'disabled' icons, which instead of showing a greyed out icon, they show a blank square.

Note that I tried with both the `Icons8` and `Silk` icon packs, both are showing the same blank icons:

![image](https://user-images.githubusercontent.com/13773388/66662101-ced05300-ec0d-11e9-8879-0415a42933c9.png)

It seems to only happen in the main toolbar.
All other icons and buttons on menus and the dialogs I've tested seem to show correctly.

**Comment by ansgarbecker** [comment] 2019-10-12 06:56
Thanks for all the screenshots. I just can't do much here, seems like a Wine bug to me. No related report in [their tracker](https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=STAGED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=RESOLVED&bug_status=CLOSED&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f6=status_whiteboard&f7=content&f8=CP&f9=CP&j1=OR&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&query_format=advanced&short_desc=heidisql&short_desc_type=allwordssubstr&v2=heidisql&v3=heidisql&v4=heidisql&v5=heidisql&v6=heidisql&v7=%22heidisql%22) yet, at least not with the keyword "heidisql", and "bsSplitButton". Maybe we should file a new issue there.

**Comment by ansgarbecker** [comment] 2019-10-13 14:31
This is a duplicate of issue #560

**Closed by ansgarbecker** 2019-10-13 14:31 UTC
Labels: bug, wine

**Comment by PriyankMotivaras** [comment] 2021-02-23 15:03
Everything is works fine for me i change theme from Tools->Preferences -> style theme to windows10
