### ISSUE TITLE
Clear data tab sort

### ISSUE THREAD

**Issue by snuggeman** [HeidiSQL/HeidiSQL#1594] opened 2022-05-23 20:48 UTC
**Is your feature request related to a problem? Please describe.**
When choosing sort options to a table tab, they are remembered.
If that sort is causing a very long response time, there is no way of (after killing the query) re-entering the tab without the same sort occurring again.

**Describe the solution you'd like**
Add a context menu item for the table; "Clear data tab sort" next to the existing "Clear data tab filter" to remove any saved sort options

**Comment by snuggeman** [comment] 2023-04-25 14:23
I return to this bug everytime I get bitten by it.

**Comment by ansgarbecker** [comment] 2024-04-29 05:27
Duplicate of #1868

**Closed by ansgarbecker** 2024-04-29 05:27 UTC
