### ISSUE TITLE
add a  name filter when export Database talbes to sql

### ISSUE THREAD

**Issue by techyang** [HeidiSQL/HeidiSQL#1871] opened 2023-11-16 04:00 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add a  name filter when export Database talbes to sql, for example , if there are 10 tables in the database, some tables's name begin with 'user_', when  tabed  'user_' in th filter , only the tables with names  begin with 'user_' show in the view. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment] 2023-11-20 07:40
Duplicate of #178

**Closed by ansgarbecker** 2023-11-20 07:40 UTC
