### ISSUE TITLE
Make the filter window height adjustable

### ISSUE THREAD

**Issue by marcovtwout** [HeidiSQL/HeidiSQL#1700] opened 2022-11-09 14:18 UTC
**Is your feature request related to a problem? Please describe.**
I often use the filter function in the Data-tab for both basic and advanced filtering. When the filters get more lengthy, for example when specifying large ID lists or subqueries, the window quickly gets too small and a scrollbar appears. This happens even faster when you are using an increased font size.

**Describe the solution you'd like**
It would be great if the filter window height could be dragged and expanded.

**Describe alternatives you've considered**
I could use a normal query tab and full select, but then the other great features of the Data tab are not available (such as quick filters or edits)

**Additional context**
Visual example:
![image](https://user-images.githubusercontent.com/438046/200853567-32ccacec-735b-4c2b-8ae1-1067e6e51bf3.png)

**Comment by ansgarbecker** [comment] 2022-11-09 18:50
Duplicate of #1536

I just placed that on the next release milestone.

**Closed by ansgarbecker** 2022-11-09 18:50 UTC
