### ISSUE TITLE
[wine?] Wrong format string on THttpDownload

### ISSUE THREAD

**Issue by gcarreno** [HeidiSQL/HeidiSQL#1215] opened 2020-11-11 21:17 UTC
Hey @ansgarbecker 

https://github.com/HeidiSQL/HeidiSQL/blob/bae514d147c980060feb3cfa51b8ac0d704a4383/source/apphelpers.pas#L3336

As you can see above, the string you have is:
```pascal
'Could not open %s (%s) - trying again without SSL...'
```
but it should be:
```pascal
'Could not open %s (%d) - trying again without SSL...'
```

![HeidiSQL-FormatError](https://user-images.githubusercontent.com/81799/98865370-2f5e3f00-2463-11eb-885e-e46b29c60420.png)

Sorry for making this break with my constant nagging on #1209 !!

Cheers,
Gus

**Comment by ansgarbecker** [comment] 2020-11-11 21:29
Ah, thanks for the hint - I was thinking GetLastError gives me a message string, but it doesn't. Should be fixed in the next build.

**Closed** 2020-11-11 21:28 UTC

**Comment by gcarreno** [comment] 2020-11-11 21:55
Hey @ansgarbecker 

No probs! I would probably make the same assumption coming from a Pascal Background.

Those C guys are all byte and integer based. You know about their string aversion right? :smile: 

Cheers,
Gus

**Comment by ansgarbecker** [comment] 2020-11-12 07:58
Ok, apart from that fixed format bug - neither https nor http is now working here, right? Or what does the log panel say with the new build?

**Comment by gcarreno** [comment] 2020-11-13 00:16
Hey @ansgarbecker 

This was I got from Build 6120:
![HeidiSQL-NoMessageGetLastError](https://user-images.githubusercontent.com/81799/98872893-499e1a00-246f-11eb-8311-27a0f3ab0272.png)
This is the same image I posted on #1216 

So it looks like it gives up after trying `HTTPS` and doesn't test `HTTP` if you judge from the error message.
But looking at the code, the only explanation for that message to have `HTTPS` is if the `ReplaceRegExpr()` didn't work, right?

Cheers,
Gus

**Comment by ansgarbecker** [comment] 2020-11-13 16:21
That error message just used an outdated variable, forget that. I just fixed that for the next build.

But that still does not help for wininet not being capable of opening http(s) urls. Did you find something about the cause of that in Wine 5?

**Comment by gcarreno** [comment] 2020-11-14 01:34
Hey @ansgarbecker 

> Did you find something about the cause of that in Wine 5?

I posted a bug on their [bugzilla (id 50122)](https://bugs.winehq.org/show_bug.cgi?id=50122), and had an immediate reply with some basic questions, and how to better frame the issue with their options, as you can see from the exchange on the issue page.

Nothing from that day further.

The immediate tip for solving it to upgrade to either `wine-develop` or `wine-stagging`, which is ludicrous since that leaves all users of Ubuntu 20.04 LTS AND 20.10 with a very troubling issue for any app that uses `wininet`.
Not all Ubuntu users have 20+ years of Linux experience and can just open a terminal and presto done!
So, I'm waiting for them to get back on it.

> That error message just used an outdated variable, forget that. I just fixed that for the next build.

Confirmed: 
![HeidiSQL-Message-rev6121](https://user-images.githubusercontent.com/81799/99135009-2c587f80-2618-11eb-9afe-8b261acf162f.png)
