### ISSUE TITLE
Hotkey ampersand in session name prevents entering the key after the ampersand in grids

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#1992] opened 2024-07-24 13:21 UTC
**Preconditions**
* HeidiSQL version: current nightly
* Database type and version: don't care
* OS: don't care

**Describe the bug**
See title

**To Reproduce**
Example:
1. Connect to a profile that contains an ampersand in its name
2. Go to any grid
3. Bring up any grid field's edit box and press the key that follows the ampersand
4. The key is ingored and it takes you to the server object list instead

Notes:
* There are cases when the bug does not occur
* The bug did not exist in earlier 12.7 nightlys (March) and in 12.6.
* Only occurs with grid field edit boxes, not with any other control

**Solution**
Sanitize user input and escape ampersands in UI!

**Comment by ansgarbecker** [comment] 2024-07-25 04:38
I can't either reproduce that, or I don't understand your description. I have a session with an ampersand in its name, but I can easily edit grid values:

![grafik](https://github.com/user-attachments/assets/626e6fe1-81b3-4525-96e9-bd83df978c06)

**Comment by nummacway** [comment] 2024-07-25 09:58
In your case, this would affect the 2 key. There is no 2 in the entered text.

It is nonetheless important to sanitize user input. The profile name is displayed in the first tab. In Heidi 12.6, the hostname was displayed there. This causes the error.

**Comment by ansgarbecker** [comment] 2024-07-25 18:27
Thanks for the clarification. Didn't recall the host tab uses the session name. Even more: when connecting through the dropdown of the connect button, the ampersand gets stripped and then causes an access violation, because the ampersand is not passed internally:

![grafik](https://github.com/user-attachments/assets/6dbc11ab-9665-41bc-8628-958a72cf0b38)

**Comment by ansgarbecker** [comment] 2024-07-25 18:37
Same as 11 years ago :) https://www.heidisql.com/forum.php?t=14032

**Comment by ansgarbecker** [comment] 2024-09-27 12:14
Also happens with ampersand in database names, and probably table names, as reported in [the forum](https://www.heidisql.com/forum.php?t=43601):

![2-2024-09-27_10-03-41](https://github.com/user-attachments/assets/8e8997e2-6ba0-4f47-91fb-338c3c2ff854)

**Comment by ansgarbecker** [comment] 2024-10-12 13:40
Should be fixed in the next build, supporting ampersands where you like.

In Delphi, the `&` is escaped by a second `&` if you want to disable hotkey accelerators. That was indeed new to me.
Additionally, I had to strip that duplicated `&` when reading such escaped captions. Although you cannot see it, there is a "hidden" one in the string then.

Menus should also not crash with such session names:

![grafik](https://github.com/user-attachments/assets/1fe81120-2c70-4fb0-ab5d-d53b5accbf3c)

![grafik](https://github.com/user-attachments/assets/fee7f9de-dadc-4dd4-b748-90fcc76ec4f7)

**Closed by ansgarbecker** 2024-10-12 13:40 UTC
Labels: bug, confirmed
