### ISSUE TITLE
Crash after trying to remove a sorting filter from a table

### ISSUE THREAD

**Issue by anselal** [HeidiSQL/HeidiSQL#568] opened 2019-03-12 09:19 UTC
## Steps to reproduce this issue

The software crashed after trying to remove a sorting filter from a table. No clue why this happens.

## Current behaviour

Crashes

## Expected behaviour

Don't crash, just remove the sorting filter

## Possible solution

No clue.

## Environment

date/time          : 2019-03-12, 11:11:28, 596ms
operating system   : Windows 10 x64 build 17763
system up time     : 12 days 20 hours
program up time    : 14 seconds
processors         : 4x Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
physical memory    : 19206/31682 MB (free/total)
free disk space    : (C:) 180,00 GB (D:) 345,59 GB
display mode       : 1600x900, 32 bit
process id         : $38c4
allocated memory   : 96,36 MB
largest free block : 131025,96 GB
executable         : heidisql.exe
exec. date/time    : 2019-03-12 09:00
version            : 10.1.0.5492
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $321d0205, $b1df58de, $b1df58de
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00000000006A8242 in module 'heidisql.exe'. Read of address 0000000000000010.

main thread ($378c):
006a8242 heidisql.exe Vcl.Controls          TWinControl.WndProc
006d8df0 heidisql.exe Vcl.StdCtrls          TButtonControl.WndProc
006a78fa heidisql.exe Vcl.Controls          TWinControl.MainWndProc
0055c293 heidisql.exe System.Classes        StdWndProc
7ff879c7 USER32.dll                         DispatchMessageW
0084e09e heidisql.exe Vcl.Forms             TApplication.ProcessMessage
0084e113 heidisql.exe Vcl.Forms             TApplication.HandleMessage
0084e561 heidisql.exe Vcl.Forms             TApplication.Run
00ddf37a heidisql.exe heidisql       85 +26 initialization
7ff87a01 KERNEL32.DLL                       BaseThreadInitThunk
7ff87c5e ntdll.dll                          RtlUserThreadStart

**Comment by JulianRaya** [comment] 2019-04-16 23:14
I have this problem too. It only happens when you try to remove the last sorting filter. 
If I have many sorting filters, removing them works fine, until I try to remove the last one.
When I remove the last one, it crashes. 

**To Reproduce**
1. open a table and view the data. 
2. Add a sort filter by clicking the header of one of the columns. Note the arrow icon in the header. 
3. Try to remove the sort filter by opening the "Sorting" dropdown and clicking the X.  If there are more than one sort filters, remove all of them by clicking all the Xs. Removing the final sort filter will crash the program.

**Workaround**
remove the sort filter by clicking the header of the sorted column until the arrow icon is no longer in the header. This removes the sort filter without crashing, but is inconvenient when trying to find the correct header to click on tables with lots of columns.

**bugreport.txt**
date/time          : 2019-04-16, 15:53:34, 117ms
computer name      : DESKTOP-29NNVT3
user name          : Julian
registered owner   : Julian
operating system   : Windows 10 x64 build 17763
system language    : English
system up time     : 5 days 3 hours
program up time    : 1 day 5 hours
processors         : 12x AMD Ryzen 5 2600 Six-Core Processor
physical memory    : 7701/16335 MB (free/total)
free disk space    : (C:) 145.57 GB
display mode       : 1920x1080, 32 bit
process id         : $b88
allocated memory   : 152.34 MB
largest free block : 131025.94 GB
executable         : heidisql.exe
exec. date/time    : 2019-01-26 07:17
version            : 10.1.0.5464
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $321d0205, $b1df58de, $b1df58de
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00000000006A8222 in module 'heidisql.exe'. Read of address 0000000000000010.

main thread ($f4):
006a8222 heidisql.exe Vcl.Controls          TWinControl.WndProc
006d8dd0 heidisql.exe Vcl.StdCtrls          TButtonControl.WndProc
006a78da heidisql.exe Vcl.Controls          TWinControl.MainWndProc
0055c293 heidisql.exe System.Classes        StdWndProc
7ff82e11 USER32.dll                         DispatchMessageW
0084e07e heidisql.exe Vcl.Forms             TApplication.ProcessMessage
0084e0f3 heidisql.exe Vcl.Forms             TApplication.HandleMessage
0084e541 heidisql.exe Vcl.Forms             TApplication.Run
00dd74ba heidisql.exe heidisql       85 +26 initialization
7ff82f9c KERNEL32.DLL                       BaseThreadInitThunk
7ff82fb1 ntdll.dll                          RtlUserThreadStart

**Comment by JulianRaya** [comment] 2019-04-16 23:15
this is actually a duplicate of bug #520

**Closed** 2019-04-17 05:37 UTC
Labels: duplicate
