### ISSUE TITLE
Dark theme for nightly coding sessions

### ISSUE THREAD

**Issue by RAYs3T** [HeidiSQL/HeidiSQL#8] opened 2017-11-09 23:11 UTC
Adding a "dark theme" would be super nice. The white skin is pretty eye straining in some conditions.

You know, for the night operators. ;)

**Comment by ansgarbecker** [comment] 2017-11-10 13:07
Theming is normally done in Windows design settings. And I guess just making background colors dark would make HeidiSQL really ugly. That also implies light font colors, different grey scales in borders and disabled buttons etc.

Did you try to set a dark theme in your Windows settings?

See this forum thread: https://www.heidisql.com/forum.php?t=23756

**Comment by ansgarbecker** [comment] 2017-11-11 17:11
See attached screeny from a quick color assignment. Ugly. I guess real theming needs some dedicated theming component.
![grafik](https://user-images.githubusercontent.com/7986591/32691680-a8880ce8-c70b-11e7-9a03-fe4750898af6.png)

**Comment by oliveru** [comment] 2017-11-13 08:56
Right - like the Jetbrains IDEs, e.g. PHPStorm and so on.

**Comment by ansgarbecker** [comment] 2017-11-13 14:50
PHPStorm is Java-based, while HeidiSQL uses the Windows API for painting dialogs and other controls.

What about changing colors in your Windows design settings?

**Comment by oliveru** [comment] 2017-11-21 12:21
For me no problem, don't know about the thread creator, just wanted to give some input.

**Comment by draknyte1** [comment] 2017-12-11 09:14
> What about changing colors in your Windows design settings?

Is never really a valid solution.
While I've never had an issue with the colour scheme in Heidi, a simple solution to implement that gives users freedom isn't too hard.

New UI screen in settings, Have  maybe 10 boxes which contain the default colours for certain components, allow changing them. Then just have BG/Borders/etc get their colours from there. Simple reset to default button and you're done. While I am not familiar with Delphi, I'd assume that it lets you do styling of windows to some basic extent.

**Comment by ansgarbecker** [comment] 2017-12-11 19:47
Of course with Delphi you can style some basic things, while it was never designed to implement its own style including border colors and some other minor things. You can see that in the screenshot above.

**Comment by ansgarbecker** [comment] 2018-10-18 19:13
This is a high-dpi screeny of a sample program created in Rad Studio 10 (trial), with an applied "carbon" theme. That's one from many, I guess 30 or 40, supported by RS10. Looks nice, doesn't it?
![rx10-sample-program](https://user-images.githubusercontent.com/7986591/47178133-965ba900-d31a-11e8-9d83-a4eea1614d09.png)

**Comment by RAYs3T** [comment] 2018-10-19 13:31
@ansgarbecker Looks for sure better then the white skin. But the icons seems to be a little bit too large? (Like the icon in the title-bar).

What about tables?

**Comment by ansgarbecker** [comment] 2018-10-19 14:08
The icons are large because my Windows was in 150% mode. That was another thing I wanted to test with the new Rad Studio.
I will try to load Heidi's sources into that trial version, compile and make a screenshot to see how many new issues I have then :)

**Comment by ansgarbecker** [comment] 2018-10-19 17:50
Here we go: HeidiSQL compiled with Rad Studio 10.2 and Carbon Style selected.

Glitches I can most probably fix easily:
* white SQL editors
* lightgrey column on listings

Issues which I have no idea about yet:
* broken main menu items - nothing visible, but space reserved
* white background / non transparent icons on buttoned edit controls

![tokyo-carbon-data](https://user-images.githubusercontent.com/7986591/47234888-92419100-d3d7-11e8-88e6-68afa02de61b.png)
![tokyo-carbon-database](https://user-images.githubusercontent.com/7986591/47234889-92419100-d3d7-11e8-9457-e750712182eb.png)
![tokyo-carbon-export](https://user-images.githubusercontent.com/7986591/47234890-92da2780-d3d7-11e8-98ca-cb2512ab4683.png)
![tokyo-carbon-gridexport](https://user-images.githubusercontent.com/7986591/47234891-92da2780-d3d7-11e8-9426-85b0f408b93c.png)
![tokyo-carbon-mainmenu](https://user-images.githubusercontent.com/7986591/47234892-92da2780-d3d7-11e8-9279-60a6e769fc93.png)
![tokyo-carbon-query](https://user-images.githubusercontent.com/7986591/47234894-92da2780-d3d7-11e8-8963-4ed6287793ba.png)
![tokyo-carbon-rightclickmenu](https://user-images.githubusercontent.com/7986591/47234895-9372be00-d3d7-11e8-90ad-1af6ae2283a2.png)
![tokyo-carbon-sessions](https://user-images.githubusercontent.com/7986591/47234896-9372be00-d3d7-11e8-858c-f2e9fe83d8c7.png)
![tokyo-carbon-table](https://user-images.githubusercontent.com/7986591/47234897-9372be00-d3d7-11e8-83f4-eb94a8eb7e9b.png)

**Comment by ansgarbecker** [comment] 2018-10-26 09:48
Some code hints for myself:

Adding styles is doable via .rc file:
`Carbon VCLSTYLE "Redist\Styles\Vcl\Carbon.vsf"`

Listing included styles via style manager:
`TStyleManager.StyleNames`

Apply style to application:
`TStyleManager.TrySetStyle('Carbon');`

**Comment by ansgarbecker** [comment] 2018-10-26 15:04
Tada, here we go: The newest HeidiSQL build has 39 selectable style themes. You can set it in Tools > Preferences > General, at the very bottom.

Though there are a few new issues with this now. So be warned! We are still in the nightly builds here.
* all themes I tested lead to empty text in first level of main menu
* some listings have a light grey background in one or two columns, which is quite unreadable if the theme's font color is white (only a problem in dark themes)
* SQL editors always have a hardcoded white background
* various colored text does not work well with many themes, e.g. the data types (numbers=blue, text=green, etc.)

**Comment by ansgarbecker** [comment] 2018-10-27 14:58
.vsf styles can be created and edited with the integrated BitmapStyleDesigner.exe. Not sure if that's available separately from Delphi or RAD Studio.

**Comment by ansgarbecker** [comment] 2018-10-27 15:54
Various foreground/background colors are now "locked" to the active theme, so we don't have a light background on dark themes any more.

Though the SQL editors are still hardcoded white. They have many different font colors which are quite incompatible to dark themes, so it's not optimal to just adapt the background to the active theme. But I'll start over doing exactly that. Selecting better fitting SQL font colors may be left up to the user then.

**Comment by ansgarbecker** [comment] 2018-10-27 18:11
This is how it looks like, with some issues fixed:

![grafik](https://user-images.githubusercontent.com/7986591/47607752-6734ee00-da24-11e8-937d-9323fa66f25a.png)

**Comment by chrysler5798** [comment] 2018-10-29 08:33
Hi,

A little display issue related to this new theme feature I think :
![2018-10-29_09-16-56](https://user-images.githubusercontent.com/7657777/47637254-694d9880-db5b-11e8-9b26-80e7d56668e4.gif)

There is an empty space on the left of main menu buttons.

HeidiSQL version : 9.5.0.5314
Theme : Windows (default)
Language : french

**Comment by ansgarbecker** [comment] 2018-10-29 12:58
> A little display issue related to this new theme feature I think, there is an empty space on the left of main menu buttons for the default theme (Windows) :

Yes, I can confirm that, although sporadically only. I have no clue about the reason, and no clue how to fix that.

> EDIT : Another issue, buttons between "SQL help" and "Load a SQL file" are transparents when you select another theme than Windows (default one).

Yes, these are disabled buttons. This is intentionally done by the underlying library. Ok, they could look more stylish, yes, but I have very few to no influence on that look.

**Comment by ansgarbecker** [comment] 2018-11-15 19:10
I think we are complete at this point with themes. At least for the obvious stuff. So I'll close this issue now.

If anyone finds more issues with theming, then please report that in a new issue. Thanks!

**Closed by ansgarbecker** 2018-11-15 19:10 UTC
Labels: enhancement

**Comment by anselal** [comment] 2018-12-06 08:33
Using version 9.5.0.5371 my left panel (database tables) still shows up with a white background
on all themes

**Comment by cookieguru** [comment] 2018-12-06 08:34
@anselal Works great for me; have you tried clearing your settings?

**Comment by anselal** [comment] 2018-12-06 08:36
@cookieguru thanks, clearing the settings did the job !!!!!

**Comment by anselal** [comment] 2018-12-06 08:38
@cookieguru is there a specific like I can remove from my settings file to get the work done ? Don't wanna lose all of my settings

**Comment by cookieguru** [comment] 2018-12-06 08:39
@anselal No idea.  I would clear the settings, copy them, change the theme, then diff those, and go from there.

**Comment by anselal** [comment] 2018-12-06 10:36
I found that yo must set the TreeBackground option like:

```sh
Servers\Unnamed\TreeBackground<|||>3<|||>536870911
```

this is for the Carbon theme.

**Comment by kapitannwel** [comment] 2019-04-26 06:40
really like this, thank you!
