### ISSUE TITLE
File Changed Dialog box to only open once regardless of number of file changes

### ISSUE THREAD

**Issue by JD-aus** [HeidiSQL/HeidiSQL#1370] opened 2021-05-06 03:54 UTC
**Preconditions**

* HeidiSQL version: 11.2.0.6213 (any many previous versions)
* Database type and version: ALL
* OS: Windows 7 & 10

**Describe the bug**
The Dialog box saying that the file has been updated, do you want to reload, pops up as many times as the files are changed, this is an issue on a corporate network that uses multiple network storage devices to store the users profile, in this situation, the file changes approx every hour. if I leave the app running over a weekend, I can have several hundred popup dialog boxes for a few tabs open.
**To Reproduce**
Change the file externally multiple times

**Screenshots or Crash reports**
Its should be easily reproduced.

**Comment by ansgarbecker** [comment] 2021-05-06 05:20
Duplicate of #821

**Closed by ansgarbecker** 2021-05-06 05:20 UTC
