### ISSUE TITLE
MSSQL trimming first statements on StoreProcedure

### ISSUE THREAD

**Issue by NeV3rKilL** [HeidiSQL/HeidiSQL#1644] opened 2022-08-17 12:18 UTC
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: MSSQL 2012 SP4
* OS: Windows

StoreProcedure is trimming first characters.

The StoreProcedure is:
![image](https://user-images.githubusercontent.com/1600127/185116140-82771daf-f80f-4440-adf6-32293ef008c9.png)

while Routine Body shows:
![image](https://user-images.githubusercontent.com/1600127/185116205-67a40f38-e361-48d3-b79c-54cc0ac8eb59.png)

I don't know why HeideSQL clipped the first parameter giving a wrong statement.

**To Reproduce**
1. Just click on the SP (SP is Wrong)

It happens with all the SP that starts by defining the parameters. The first one is always trimmed.

**Comment by ansgarbecker** [comment] 2022-08-18 04:39
Duplicate of #667

**Closed by ansgarbecker** 2022-08-18 04:39 UTC
