### ISSUE TITLE
Artefacts in query tab

### ISSUE THREAD

**Issue by mftun** [HeidiSQL/HeidiSQL#410] opened 2018-11-26 07:23 UTC
## Steps to reproduce this issue

1. put two separate queries to query tab and run

## Current behavior

see pic.

![default](https://user-images.githubusercontent.com/45350519/48998287-1a981c00-f164-11e8-8da1-11aba4ddf2df.png)

## Expected behavior

no artefacts

## Environment

* **HeidiSQL version:** 
Revision 5340 (yours: 5340)
Compiled: 2018-11-25 (yours: 2018-11-26)

**Comment by fifonik** [comment] 2018-11-26 22:48
I can confirm the issue.

When I'm executing long query (even a single one), scroll bars are flashing for a moment:
`SELECT * FROM TableWithManyRecords LIMIT 10000;`

**Comment by mftun** [comment] 2018-11-27 11:29
Artifacts flash on the local host. With remote access (RDP) these artifacts remain on the screen. They do not respond to clicks. When a window is moved or resized, they behave like a control tied to a tab bar.

Perhaps this is an RDP bug. However, versions prior to r5305 are not affected.

It looks like a stub to display a dataset. They must be hidden. With remote access, they disappear if you click on the inactive header of the data set.

**Comment by mftun** [comment] 2018-11-27 11:53
I ran 10 requests and found out that this is a TVirtualStringTree. The coordinates of the upper left corner of all 10 coincide with TTabSheet.

If you click on each result of the query, the coordinates change.

**Comment by fifonik** [comment] 2018-11-28 21:04
Any particular reason to close the issue?

**Comment by mftun** [comment] 2018-11-29 07:50
missclick

**Comment by ansgarbecker** [comment] 2018-11-29 07:59
> Perhaps this is an RDP bug. However, versions prior to r5305 are not affected.

r5305 added themes to HeidiSQL. Also, the screenshot in the first post here shows a themed scrollbar. Another user on the forum reported [similar stuff](https://www.heidisql.com/forum.php?t=25952#p26035). So I suppose the issue is related to the new themes in Heidi.

For testing purposes, you should apply the default "Windows" theme to HeidiSQL, and see if the artifacts still show up.

**Comment by ansgarbecker** [comment] 2018-11-29 08:01
Ah, and you should definitely update HeidiSQL to the latest build. I worked a lot on theming during the recent weeks, so one or another glitch may already be fixed, magically.

**Comment by mftun** [comment] 2018-11-29 08:47
In 9.5.0.5355 is still present with remote connection (RDP). Windows theme without artifacts.

**Comment by ansgarbecker** [comment] 2018-11-30 13:00
Ok, I have no clue what's exactly causing the flashing of scrollbars, or the artefacts mftun mentioned.

**Comment by ansgarbecker** [comment] 2018-12-04 19:11
I experienced some artefacts after selecting a theme, in the same HeidiSQL session where I did that. So the next build will show an information dialog the user should restart Heidi after changing critical settings.

I suppose you already restarted HeidiSQL to get rid of these artefacts?

**Comment by fifonik** [comment] 2018-12-04 22:49
I never changed the theme (well, I did once long time ago just to check what is this) so restart was not needed.
Also, I downloaded build 5304 (with no themes support) and the thing is still flashing on query execution.

**Comment by fifonik** [comment] 2018-12-25 02:00
Updated to build 5422 and still see the same glitches on my home PC (100% scale, Windows 10 1809):
Screen capture with demo (re-encoded, can supply sources, but they are bigger): https://www.dropbox.com/s/z91qfqo75dncham/Heidi.mp4?dl=1

**Comment by fifonik** [comment] 2018-12-25 10:30
Hm, yes. This is what I said from the beginning: "scroll bars are flashing for a moment"

**Comment by ansgarbecker** [comment] 2018-12-25 11:15
Oh, in that case I misunderstood, sorry. Though it's a really minor issue then, and probably not fixable.

**Comment by vr0ck** [comment] 2019-02-05 14:33
In my case, the artifacts are persistent (and highly annoying) with two or more queries on the same tab, separated by semicolon.
![persistent_artifact](https://user-images.githubusercontent.com/13688706/52279974-e732f400-2941-11e9-9679-fe5a092d5ca5.PNG)
The same two queries united by UNION clause, only generate flickering artifacts.
![flickerartifact](https://user-images.githubusercontent.com/13688706/52279975-e732f400-2941-11e9-9d37-c2dac8e3c69c.PNG)

**Comment by ieuanmeredith** [comment] 2019-03-07 02:13
I'm also getting persisting scroll bar artifacts as per @vr0ck latest post here. Only occurring when running 2 or more queries in sequence. If multiple are present but only one is selected and run via Ctrl+F9 then the artifacts do not occur.

**Comment by ansgarbecker** [comment] 2019-03-07 09:10
I suppose this and most of the other theme related issues here cannot be solved by code in HeidiSQL. The implementation of themes is just buggy. Even it does not work out of the box, for which reason I added a lot of code from https://github.com/RRUZ/vcl-styles-utils . But still quite a few issues are left, and I have no clue how to fix these. I can just recommend to use the default Windows theme instead.

**Comment by JamieAzure** [comment] 2019-03-15 14:57
I get the artifact nearly everytime I move Heidi from one monitor to another, but it's particularly frequent when moving from monitor to monitor when they have differing DPI or scaling settings (4K -> 1080p) 
![image](https://user-images.githubusercontent.com/841771/54440398-e2c8da80-473a-11e9-8206-702e1ef5244a.png)

Once it show up, there's not an obvious way to get rid of it with restarting Heidi.

**Comment by JamieAzure** [comment] 2019-03-15 15:21
Here's a video of the rendering working but you can clearly see what the default theme is 'erasing' that all the other themes leave as artifacts.
[![Screenshot from Gyazo](https://gyazo.com/4586c9abfbaff7400028d3d3cd4b8c80/raw)](https://gyazo.com/4586c9abfbaff7400028d3d3cd4b8c80)

**Comment by adipose** [comment] 2019-04-08 16:03
I have this bug.  Nothing to do with RDP, just regular windows and the dark theme.

**Comment by adipose** [comment] 2019-04-08 16:07
I have some more info on this bug.  It presents itself when running multiple queries, as noted by others.  However, it appears to resolve itself when switching to the second resultset (and back).  This may be a clue.  Perhaps the form is trying to erase those extra scrollbars, but only does so on the last resultset, then the first resultset is shown and still has the artifact.  When switching resultsets manually it appears to trigger a refresh and fix the issue.  No restart required!

**Comment by MrBitsHub** [comment] 2019-04-08 19:29
I also have this bug since the themes thing.  I'm using dark theme too and I have confirmed what @adipose  just said, and would like to extend it:  if you have 'n' queries:  you have to navigate by the 'n' resultsets to get rid of it (at least there is a way).   In the meantime, maybe you (we) could automate this by making a macro on the execute query command to trigger also the all tabs navigation hassle.

**Comment by kapitannwel** [comment] 2019-05-06 06:27
that's a nice hint @JamieAzure and @adipose , guess sir @ansgarbecker has something to start with now. more power!

**Comment by ansgarbecker** [comment] 2019-05-07 18:10
The artefact is the result grid, which is created with a default alignment, before this gets fixed:

![grafik](https://user-images.githubusercontent.com/7986591/57322576-24a34b00-7104-11e9-8b2d-e06134aabd79.png)

I will check what happens when clicking the result tabs, which may indeed by a good hint.

**Closed** 2019-05-07 18:17 UTC
Labels: themes

**Comment by ansgarbecker** [comment] 2019-05-07 18:19
I found that the just created grid is made invisible before it gets aligned correctly. So I am now hiding the grid _after_ the alignment is finished, and suddenly I have no artefacts any more.

Please also test with the upcoming nightly build, and give feedback. Thanks!

**Comment by kapitannwel** [comment] 2019-05-08 00:51
installed the latest update and i confirmed that the artefacts is hiding after the queries had finished. thank you very much!

**Comment by MrBitsHub** [comment] 2019-05-08 05:33
Dark theme confirmed as fixed here (10.1.0.5559) !! Big thank you!
