### ISSUE TITLE
Crash in load SQL file form

### ISSUE THREAD

**Issue by arielvsp** [HeidiSQL/HeidiSQL#1509] opened 2022-01-03 19:54 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MySQL 5.6.10
* OS: Windows 11

**Describe the bug**

Open new query tab 
Open File -> Load SQL File 
Click inside the folder selection field -> Crash

**To Reproduce**

1. Open new query tab 
2. Open File -> Load SQL File 
3. Click inside the folder selection field
4. App crashes

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2022-01-03 20:20
I am unable to reproduce that crash. Probably Win11 related. Isn't there a crash report, or how does it crash?

**Comment by arielvsp** [comment] 2022-01-03 20:41
No crash report I can see (where should I be looking for it)?
Just crashes... very consistent. Would be happy to help to debug/test.

**Comment by ansgarbecker** [comment] 2022-01-06 06:52
I cannot do anything here without more details.
Is it an official Win11 version or some early access?
Are you using a non-default style/theme in HeidiSQL?
Does the Windows event logger show some details about the crash?

**Comment by arielvsp** [comment] 2022-01-06 07:37
I cannot do anything here without more details.
-- Clear, I'll be happy to provide more stuff, let me know what else you
need.

Is it an official Win11 version or some early access?
-- Win 11 Pro, version 10.0.22000. This is the current official and latest
version.

Are you using a non-default style/theme in HeidiSQL?
-- Nope.

Does the Windows event logger show some details about the crash?
-- Nope. The app just closes up. No relevant events are in the event logger
and no exception is presented. Is there any way to run HeidiSQL so that it
creates some log?

**Comment by arielvsp** [comment] 2022-01-06 07:43
The attached screenshot shows exactly where I click to crash the app:

![Screenshot 2022-01-06 093930](https://user-images.githubusercontent.com/6899480/148346929-ac2b3041-7b7b-406c-be55-54e398612ae6.png)

**Comment by ansgarbecker** [comment] 2024-06-21 11:37
This is still not reproducible in Windows 10 and 11. So I'm closing it right now. Please shout if you can still reproduce it on a modern system.

@pribeirojtm your description sounds as if Wine pretends an older Windows version, not Win10. That issue is definitely different.

**Closed by ansgarbecker** 2024-06-21 11:37 UTC
Labels: needs-info
