### ISSUE TITLE
Issue with table comment on TokuDB

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#196] opened 2018-03-16 17:12 UTC
## Steps to reproduce this issue

1. Add a comment on a tokudb table
2. Save
3. Reload table
4. Then I get... [my comment]' `compression`='tokudb_zlib

## Current behavior

compression= is added to the comment view in heidisql
![screenshot from 2018-03-16 13-12-26](https://user-images.githubusercontent.com/3911428/37534610-b65f67e0-291b-11e8-95fe-ce2df88b7b1b.png)

## Expected behavior

only seeing my comment

## Environment

* **HeidiSQL version:** 
latest nightly
* **Database system and version:** 
mariadb 10.1.x
* **Operating system:** 
ubuntu 17.10 w/ wine

**Comment by ansgarbecker** [comment] 2018-03-17 08:26
Weird. Please provide the result of `SHOW CREATE TABLE push_sent` here, so I can probably reproduce that.

**Comment by sirber** [comment] 2018-03-17 11:08
heidi gives me:

CREATE TABLE `push_sent` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'pour le datamart seulement',
	`push_notification_id` INT(10) UNSIGNED NOT NULL,
	`mobile_app_token_id` INT(10) UNSIGNED NOT NULL,
	`read_on` DATETIME NULL DEFAULT NULL,
	`language` ENUM('fr','en') NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `push_token_idx` (`mobile_app_token_id`, `push_notification_id`),
	INDEX `push_sent_read_on_IDX` (`read_on`) USING BTREE
)
COMMENT='calculated by importPush task\' `compression`=\'tokudb_zlib'
COLLATE='latin1_swedish_ci'
ENGINE=TokuDB
AUTO_INCREMENT=1800253979

a create table would look like:
CREATE TABLE `t_zlib` (
  `x` int(11) DEFAULT NULL,
  `y` int(11) DEFAULT NULL
) ENGINE=TokuDB DEFAULT CHARSET=latin1 `compression`=tokudb_zlib

**Comment by sirber** [comment] 2019-01-03 16:31
HeidiSQL: 9.5.0.5382

Percona MySLQ 5.6.x
```
CREATE TABLE `push_sent` (
	`push_notification_id` INT(10) UNSIGNED NOT NULL,
	`mobile_app_token_id` INT(10) UNSIGNED NOT NULL,
	`read_on` DATETIME NULL DEFAULT NULL,
	`language` ENUM('fr','en') NULL DEFAULT NULL,
	UNIQUE INDEX `push_token_idx` (`mobile_app_token_id`, `push_notification_id`),
	INDEX `push_sent_read_on_IDX` (`read_on`) USING BTREE
)
COMMENT='calculated by importPush task'
COLLATE='latin1_swedish_ci'
ENGINE=TokuDB
ROW_FORMAT=
;
```

MariaDB 10.0.x:
```
CREATE TABLE `push_sent` (
	`push_notification_id` INT(10) UNSIGNED NOT NULL,
	`mobile_app_token_id` INT(10) UNSIGNED NOT NULL,
	`read_on` DATETIME NULL DEFAULT NULL,
	`language` ENUM('fr','en') NULL DEFAULT NULL,
	UNIQUE INDEX `push_token_idx` (`mobile_app_token_id`, `push_notification_id`),
	INDEX `push_sent_read_on_IDX` (`read_on`) USING BTREE
)
COMMENT='calculated by importPush task\' `compression`=\'tokudb_zlib'
COLLATE='latin1_swedish_ci'
ENGINE=TokuDB
;
```

**Comment by sirber** [comment] 2019-01-03 16:33
"compression" is not handled, while "row_format" is.

**Comment by ansgarbecker** [comment] 2019-01-03 18:30
Hm, I don't know where you got the MariaDB command from, but it has escaped quotes \' which are normally part of the string itself. So the "compression=..." is part of the comment. Maybe you already overwrote that table?

**Comment by sirber** [comment] 2019-01-03 18:32
ALTER TABLE `push_sent`
	COMMENT='calculated by importPush task';

comment back at "calculated by importPush task' `compression`='tokudb_zlib" in heidisql.

**Comment by sirber** [comment] 2019-01-03 18:34
You need a linux server to be able to use tokudb. it doesn't work on windows (nor in windows linux subsystem).

**Comment by ansgarbecker** [comment] 2019-01-03 18:59
When you fire `SHOW TABLE STATUS LIKE 'push_sent'`, does the "Comment" contain the compression clause?

I have no TokuDB, and am not able to set up one, so I will need your exact input here.

**Comment by sirber** [comment] 2019-01-03 19:00
```
"Name"	"Engine"	"Version"	"Row_format"	"Rows"	"Avg_row_length"	"Data_length"	"Max_data_length"	"Index_length"	"Data_free"	"Auto_increment"	"Create_time"	"Update_time"	"Check_time"	"Collation"	"Checksum"	"Create_options"	"Comment"
"push_sent"	"TokuDB"	"10"	"Fixed"	"274828"	"18"	"4946904"	"9223372036854775807"	"1747608"	"18446744073705728004"	NULL	"2019-01-03 13:31:31"	"2019-01-03 13:31:42"	NULL	"latin1_swedish_ci"	NULL	"`compression`='tokudb_zlib'"	"calculated by importPush task"

```

**Comment by ansgarbecker** [comment] 2019-01-03 19:45
Yes, that's quite inconsistent.

I guess I need to set up a server myself, or access that by myself, so I can analyze that.

**Comment by sirber** [comment] 2019-01-03 20:53
I don't see the inconsistence since the SHOW CREATE TABLE and SHOW TABLE STATUS shows that the 'compression' flag _is not_ in the comment section.

**Comment by ansgarbecker** [comment] 2019-03-10 07:14
This compression clause should be out of the comment in the next HeidiSQL build. Reason was a loose `.*` in a regular expression, going over the closing single quote of the table comment, up to the closing single quote for "compression".

I only don't have a field for editing create options like that "compression" clause. Probably because it's a rare case and noone asked for it yet. I have to create such a field, and I suppose it can contain other strings apart from "compression", so it may be a good idea to just have plain text in it. Please file another issue if you'd like to see these create options in a new field.

**Closed by ansgarbecker** 2019-03-10 07:14 UTC
Labels: mysql, question
