### ISSUE TITLE
Erroneous queries to MSSQL server

### ISSUE THREAD

**Issue by UrsusArctos** [HeidiSQL/HeidiSQL#2039] opened 2024-10-21 10:56 UTC
### Description

This is the query:
```
DECLARE @x FLOAT = 1.0;
SELECT SIN(2 * @x) + COS(3 * @x) + 4 - POWER(85, 3) AS f_value;
```

If run through MS SQL Server Management Studio, the query completes successfully:
![зображення](https://github.com/user-attachments/assets/8bfa0f88-e648-4f04-9920-8b20a0ebad86)

If, however, this same query on that same server is run through HeidiSQL, it results in an error:
![зображення](https://github.com/user-attachments/assets/6450cd09-38d1-46b9-a894-c20e93d53fd9)

I've run some traces using SQL Server Profiler and found out that HeidiSQL is a bit dishonest in the query log it shows. What it shows is this:
```
DECLARE @x FLOAT = 1.0;
SELECT SIN(2 * @x) + COS(3 * @x) + 4 - POWER(85, 3) AS f_value;
/* SQL Error (137): Must declare the scalar variable "@x". */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 of 2 queries: 0.000 sec. */
```
But what it actually does is this:
![зображення](https://github.com/user-attachments/assets/3249d511-ab38-4d8e-9ef4-eed9cbcfe3eb)
I guess that HeidiSQL does multiline queries line-by-line and, for reasons unknown, inserts `SELECT 1` in between, which, apparently, drops the variable context for the server and it believes the variable is not declared anymore.

### HeidiSQL version

12.8.0.6945

### Database server version

Microsoft SQL Server 2022 Express

### Reproduction recipe

Run the query in MS SQL Management Studio and in HeidiSQL
```
DECLARE @x FLOAT = 1.0;
SELECT SIN(2 * @x) + COS(3 * @x) + 4 - POWER(85, 3) AS f_value;
```
It is 100% valid query and it should not return an error.

### Error/Backtrace

```shell
/* SQL Error (137): Must declare the scalar variable "@x". */
```

**Comment by ansgarbecker** [comment] 2024-10-21 11:38
Duplicate of #262

**Closed by ansgarbecker** 2024-10-21 11:38 UTC
Labels: bug

**Comment by UrsusArctos** [comment] 2024-10-21 11:43
> Duplicate of #262

It may be a duplicate, but I provided a trace of why the error only pops up in HeidiSQL. Because of those `SELECT 1` that drops variable context. It is HeisiSQl problem still, is it not?

**Comment by ansgarbecker** [comment] 2024-10-21 11:46
No that does not work, I just tested that, by disabling that `SELECT 1` ping/query. It still raises me that SQL error 137. I can probably make that ping query optional, but that won't help here.
