### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by savoym** [HeidiSQL/HeidiSQL#1391] opened 2021-06-22 13:14 UTC
I just downloaded the HeidiSQL_11.3.0.6295_Setup.exe file from your website for Windows 10. After clicking the INSTALL button I got the error below.  Any suggestions/direction would be appreciated.  Thanks.

![image](https://user-images.githubusercontent.com/1749357/122930606-bea0ce80-d331-11eb-86ac-84895b8af329.png)

**Comment by ansgarbecker** [comment] 2021-06-22 13:17
Duplicate of #811

**Closed by ansgarbecker** 2021-06-22 13:17 UTC
