### ISSUE TITLE
Text-editor:  partial content shown for PHP serialized content in LONGTEXT

### ISSUE THREAD

**Issue by tvdijen** [HeidiSQL/HeidiSQL#476] opened 2019-01-08 20:32 UTC
## Steps to reproduce this issue

1. Put a JSON-string in a LONGTEXT-field
2. Try and manually edit the value of the field
3. Only part of the content is shown in the text-editor (see screenshot)

## Current behavior

![afbeelding](https://user-images.githubusercontent.com/841045/50856834-06168880-138c-11e9-8c84-125877adf932.png)

## Expected behavior

Full content of the field should be shown in the text-editor.

## Environment

* **HeidiSQL version:** 
  Nightly 9.5.0.5444 (64-bit)
* **Database system and version:** 
  MariaDB 10.3.12
* **Operating system:** 
  Windows Server 2012R2

**Comment by routinet** [comment] 2020-09-09 16:43
Can confirm this is still a problem on Heidi v11.0.0.5919

![image](https://user-images.githubusercontent.com/5899388/92627786-dd017600-f299-11ea-99b9-8725d0b6a2d2.png)

![image](https://user-images.githubusercontent.com/5899388/92627895-015d5280-f29a-11ea-8ef0-b019b6ca7d33.png)

![image](https://user-images.githubusercontent.com/5899388/92627933-10dc9b80-f29a-11ea-80ce-bed51adcd491.png)

**Comment by rentalhost** [comment] 2020-09-09 17:13
I believe that it is related to `\x00` that was reported here #202.

**Comment by ansgarbecker** [comment] 2022-04-17 07:46
Duplicate of #202 , which I fixed recently:

* text editor now auto-replaces NUL characters with a space, and activates read-only mode in such cases
* copying values does the same

**Closed by ansgarbecker** 2022-04-17 07:46 UTC
