### ISSUE TITLE
connect to clickhouse via mysql protocol failed

### ISSUE THREAD

**Issue by guillaume-lin** [HeidiSQL/HeidiSQL#1979] opened 2024-07-15 01:40 UTC
**Preconditions**

* HeidiSQL version: 12.7.0.6850
* Database type and version:  clickhouse  local version 24.5.1.1564
* OS: windows 10

**Describe the bug**

when connect to clickhouse with mysql protocol, hedisql issue a status command, and this command cause
clickhouse report error, thus connection failed.   even I specify a empty content start up script, the 'status' command still been
issued, cause clickhouse to report error.

**To Reproduce**

open hedisql session manager, and connect to clickhouse 9004 port, will reproduce the error
**Screenshots or Crash reports**

![1721007629581](https://github.com/user-attachments/assets/ab921c34-68ea-4879-bfb6-39cf564eea21)

**Comment by guillaume-lin** [comment] 2024-07-15 01:41
I think when user specify a custom startup script, hedisql should not issue the 'status' command when connected.

**Comment by ansgarbecker** [comment] 2024-07-15 04:23
Duplicate of #135

**Closed by ansgarbecker** 2024-07-15 04:23 UTC
