### ISSUE TITLE
[wine] Backspace on edit controls show Host tab(SQL edit is fine)

### ISSUE THREAD

**Issue by gcarreno** [HeidiSQL/HeidiSQL#1248] opened 2020-12-06 11:40 UTC
**Describe the bug**
When editing on a grid or in an Edit control, *Backspace* will not delete the previous char, but will display the Host tab.

**To Reproduce**
1. Go to a table's data
2. Double click, or trigger edit of any data
3. Press *Backspace*

**Expected behavior**
It should delete the previous char, not display the Host tab.

The only place where *Backspace* is relevant and works is in the SQL editors.

**Edit**: Forgot to mention that I had a thorough looks at all the shortcuts under preferences and nothing is assigned.

**Environment:**
 - OS: Ubuntu/Wine5.0
 - HeidiSQL version 11.1.0.6144

**Comment by ansgarbecker** [comment] 2020-12-06 12:12
Looks like a duplicate of #723, or?

**Closed by ansgarbecker** 2020-12-06 12:12 UTC
Labels: keyboard

**Comment by gcarreno** [comment] 2020-12-06 15:52
Hey @ansgarbecker 

It is a duplicate of #723 and it's my fault I didn't search before I posted.

I'm sorry!!

Cheers,
Gus
