### ISSUE TITLE
Optimize existing formatting script functions

### ISSUE THREAD

**Issue by tianmingxing** [HeidiSQL/HeidiSQL#1368] opened 2021-05-05 02:03 UTC
**Is your feature request related to a problem? Please describe.**
The current code formatting function is too difficult to use, and the result after formatting is not what I want.

**Describe the solution you'd like**
I hope that the formatted effect will be more visualized, which is easier for humans to read. I tried to compare a variety of tools, and found that some software did a good job, I think I can refer to them.

**Describe alternatives you've considered**
To be honest, I still like to use HeidiSQL, even if it has some shortcomings, but I think I will continue to use it. I now completely rely on manual formatting of the code, because the results of software formatting are unreliable.

**Additional context**

![image](https://user-images.githubusercontent.com/5615719/117089766-0b801400-ad89-11eb-8907-a8669feb4e71.png)

**Comment by ansgarbecker** [comment] 2021-05-05 06:15
Duplicate of #750

**Closed by ansgarbecker** 2021-05-05 06:15 UTC
