### ISSUE TITLE
Refresh button does not detect change in table structure

### ISSUE THREAD

**Issue by Eddcapone** [HeidiSQL/HeidiSQL#1844] opened 2023-08-29 09:59 UTC
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: MySQL, InnoDB
* OS: Ubuntu 20.04.2 LTS

**Describe the bug**

Refresh does not change table structure if it is changed externaly.

**To Reproduce**

1. Start HeidiSQL
2. Connect to your database
3. Open your test table
4.  Create a script e.g. PHP script to add a new column to the test table and execute it now.
5. Click on Refresh to see the changes in the table structure.

Expected:

New column should show after refresh

Actual Result

New column is not showing unless HeidiSQL is restarted.

**Screenshots or Crash reports**

https://github.com/HeidiSQL/HeidiSQL/issues/1628#issuecomment-1696255107

**Comment by ansgarbecker** [comment] 2023-08-29 10:22
I just exactly followed your reproduction recipe, but the new column appeared as expected in the table editor.

Probably I am doing something different, and your recipe is meant differently. What exactly is on the screen after your step 3 (open your test table) ? I was on the "Table: mytable" tab, and the table editor's selected tab is "Basic". Pressing F5 revealed the new column.

**Comment by ansgarbecker** [comment] 2023-11-20 07:43
Closing due to no feedback.

**Closed by ansgarbecker** 2023-11-20 07:43 UTC
Labels: needs-info
