### ISSUE TITLE
"Export Database as SQL" doesn't respect Avg_row_length with "group objects" in tree

### ISSUE THREAD

**Issue by bchanudet** [HeidiSQL/HeidiSQL#1907] opened 2024-02-12 10:06 UTC
**Preconditions**

* HeidiSQL version: 12.6.0.6799 (latest nightly build available at this time)
* Database type and version: MySQL 8.0.35
* OS: Windows Server 2022 Standard

**Describe the bug**
I have a table named `document` containing binary data (8411 rows, 7GB in size). 

When trying to copy the table to another database using the "Export Database as SQL" tool, HeidiSQL tries to fetch 10486 records (so the complete table data), but as it's over 7GB, it fails most of the time with a OOM error. I found this [thread on the forum](https://www.heidisql.com/forum.php?t=40058) explaining where this 10486 number comes from. 

Here's what I've looked at: 
- In the session manager, "Get full table status" is checked.
- `SHOW TABLE STATUS LIKE 'document';` works as expected. `Avg_row_length` shows `917116`. 
- According to the [calculation in the code](https://github.com/HeidiSQL/HeidiSQL/blob/8e3eed57cb0771c5116fcd89d17987246eb0dba0/source/tabletools.pas#L1955), HeidiSQL should have tried to fetch 1170 records (1024 * 1024 * 1024 / 917116).
- It looks like HeidiSQL considers Avg_row_length to be 0, but I haven't found why.
- Short of having a Delphi license I don't think I can investigate further, but I'll be happy to give any details necessary.

**To Reproduce**

1. Open a connection to a MySQL Database
2. Export a table as SQL
3. Everytime HeidiSQL tries to fetch 10486 records, no matter what the `Avg_row_length` is

**Comment by bchanudet** [comment] 2024-02-19 18:41
Hello,

It seems this bug is more random that I'd thought. 

I have two similar servers, only the MySQL version is different by only one patch version:

- Production system: Windows Server 2022 Standard, HeidiSQL 12.6.0.6799, and MySQL **8.0.34**
- Test system: Windows Server 2022 Standard, HeidiSQL 12.6.0.6799, and MySQL **8.0.35**

My reproduction case as of now: 
- Open the connection to the MySQL Server as root user
- Right-click on the `document` table, choose `Export Database as SQL`
- For **Table**, select options **Drop!!** and **Create**
- For **Data**, select **Insert**
- For **Max INSERT Size**, leave 4096 as default
- As target, select another Database on the same server and connection.

#### Production system

- `SHOW TABLE STATUS LIKE 'document';` shows `935921` for `Avg_row_length`
- The SQL logs show `SELECT * FROM document LIMIT 112;`
- Batchs seems to be 112, that seems correct according to what is computed in the code.

#### Test system

- `SHOW TABLE STATUS LIKE 'document';` shows `984525` for `Avg_row_length`
- The SQL logs show `SELECT * FROM document LIMIT 10486;`
- Batchs seems to be 10486, so it didn't use the Avg_row_length value.


The only difference I've found until now is the MySQL server version, but the changelog between the two version doesn't show any meaningful impact on the `SHOW TABLE STATUS` command.

Is there something else I can test to help investigate this further?

**Comment by marcelhaase** [comment] 2024-08-11 05:50
Hello,
I have the same problem with a mySQL 5.5 server. I have a 19GB table and Avg_row_length is 769, but the export does only use 10486 as limit (the value if the full table status is not ticked).

"Get full table status" is ticked, so the full table status should be available and the limit should be much more higher.

Best regards, Marcel

**Comment by ansgarbecker** [comment] 2024-08-11 10:08
I can reproduce that `LIMIT 10486` when "Get full table status" is not checked. The assumed average row length is then 10000 rows.

Note the cause is the unchecked "Get full table status" option. Please activate it, so HeidiSQL has the values for a better limit calculation.

**Comment by marcelhaase** [comment] 2024-08-11 10:10
@ansgarbecker I have checked / ticked the "Get full table status" all the time, but limit stays at 10486.
Do you need more information?

**Comment by ansgarbecker** [comment] 2024-08-11 11:22
Ok, I understood the opposite out of your previous comment.

You could please post the result of `SHOW TABLE STATUS LIKE 'name-of-your-table'` here.

**Comment by marcelhaase** [comment] 2024-08-11 11:24
@ansgarbecker 
Yes, no problem:

![image](https://github.com/user-attachments/assets/19ad8a5f-6d54-4018-b3e4-5e696edb4580)

**Comment by ansgarbecker** [comment] 2024-08-11 12:00
I just built up a similar table like yours, with ~17mio rows and an `Avg_row_length` of 219. The SQL export calculates a limit of 569878 rows - far beyond your 10486. The export was finished after ~4 minutes.

![grafik](https://github.com/user-attachments/assets/9aa91a82-1fd6-4f49-808d-69676f12a1c3)

Export log:
```sql
SELECT * FROM `test11`.`manyrows` LIMIT 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 569878, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 1139756, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 1709634, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 2279512, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 2849390, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 3419268, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 3989146, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 4559024, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 5128902, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 5698780, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 6268658, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 6838536, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 7408414, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 7978292, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 8548170, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 9118048, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 9687926, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 10257804, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 10827682, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 11397560, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 11967438, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 12537316, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 13107194, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 13677072, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 14246950, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 14816828, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 15386706, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 15956584, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 16526462, 569878;
SELECT * FROM `test11`.`manyrows` LIMIT 17096340, 569878;
```

Please make sure you use HeidiSQL v12.8 for the export, and double-check that "Get full table status" is activated.

**Comment by marcelhaase** [comment] 2024-08-11 14:05
Option "Get full table status" is activated:
![image](https://github.com/user-attachments/assets/74470e86-3750-4faa-a4a3-139a2617eae5)

I have locally a smaller database / table with this output:
![image](https://github.com/user-attachments/assets/583c2d24-6609-4e77-b344-11ced52ddc3e)

If I do a normal export to SQL file with this settings:
![image](https://github.com/user-attachments/assets/4dc9814a-e03c-44e1-9246-4b1974054541)

the limit is still 10486:
<details>
<summary>Export-Log</summary>

SELECT * FROM `lomas`.`results` LIMIT 10486;

SELECT * FROM `lomas`.`results` LIMIT 10486, 10486;

SELECT * FROM `lomas`.`results` LIMIT 20972, 10486;

SELECT * FROM `lomas`.`results` LIMIT 31458, 10486;

SELECT * FROM `lomas`.`results` LIMIT 41944, 10486;

SELECT * FROM `lomas`.`results` LIMIT 52430, 10486;

SELECT * FROM `lomas`.`results` LIMIT 62916, 10486;

SELECT * FROM `lomas`.`results` LIMIT 73402, 10486;

SELECT * FROM `lomas`.`results` LIMIT 83888, 10486;

SELECT * FROM `lomas`.`results` LIMIT 94374, 10486;

SELECT * FROM `lomas`.`results` LIMIT 104860, 10486;

SELECT * FROM `lomas`.`results` LIMIT 115346, 10486;

SELECT * FROM `lomas`.`results` LIMIT 125832, 10486;

SELECT * FROM `lomas`.`results` LIMIT 136318, 10486;

SELECT * FROM `lomas`.`results` LIMIT 146804, 10486;

SELECT * FROM `lomas`.`results` LIMIT 157290, 10486;

SELECT * FROM `lomas`.`results` LIMIT 167776, 10486;

SELECT * FROM `lomas`.`results` LIMIT 178262, 10486;

SELECT * FROM `lomas`.`results` LIMIT 188748, 10486;

SELECT * FROM `lomas`.`results` LIMIT 199234, 10486;

SELECT * FROM `lomas`.`results` LIMIT 209720, 10486;

SELECT * FROM `lomas`.`results` LIMIT 220206, 10486;

SELECT * FROM `lomas`.`results` LIMIT 230692, 10486;

SELECT * FROM `lomas`.`results` LIMIT 241178, 10486;

SELECT * FROM `lomas`.`results` LIMIT 251664, 10486;

SELECT * FROM `lomas`.`results` LIMIT 262150, 10486;

SELECT * FROM `lomas`.`results` LIMIT 272636, 10486;

SELECT * FROM `lomas`.`results` LIMIT 283122, 10486;

SELECT * FROM `lomas`.`results` LIMIT 293608, 10486;

SELECT * FROM `lomas`.`results` LIMIT 304094, 10486;

SELECT * FROM `lomas`.`results` LIMIT 314580, 10486;

SELECT * FROM `lomas`.`results` LIMIT 325066, 10486;

SELECT * FROM `lomas`.`results` LIMIT 335552, 10486;

SELECT * FROM `lomas`.`results` LIMIT 346038, 10486;

SELECT * FROM `lomas`.`results` LIMIT 356524, 10486;

SELECT * FROM `lomas`.`results` LIMIT 367010, 10486;

SELECT * FROM `lomas`.`results` LIMIT 377496, 10486;

SELECT * FROM `lomas`.`results` LIMIT 387982, 10486;

SELECT * FROM `lomas`.`results` LIMIT 398468, 10486;

SELECT * FROM `lomas`.`results` LIMIT 408954, 10486;

SELECT * FROM `lomas`.`results` LIMIT 419440, 10486;

SELECT * FROM `lomas`.`results` LIMIT 429926, 10486;

SELECT * FROM `lomas`.`results` LIMIT 440412, 10486;

SELECT * FROM `lomas`.`results` LIMIT 450898, 10486;

SELECT * FROM `lomas`.`results` LIMIT 461384, 10486;

SELECT * FROM `lomas`.`results` LIMIT 471870, 10486;

SELECT * FROM `lomas`.`results` LIMIT 482356, 10486;

SELECT * FROM `lomas`.`results` LIMIT 492842, 10486;

SELECT * FROM `lomas`.`results` LIMIT 503328, 10486;

SELECT * FROM `lomas`.`results` LIMIT 513814, 10486;

SELECT * FROM `lomas`.`results` LIMIT 524300, 10486;

SELECT * FROM `lomas`.`results` LIMIT 534786, 10486;

SELECT * FROM `lomas`.`results` LIMIT 545272, 10486;

SELECT * FROM `lomas`.`results` LIMIT 555758, 10486;

SELECT * FROM `lomas`.`results` LIMIT 566244, 10486;

SELECT * FROM `lomas`.`results` LIMIT 576730, 10486;

SELECT * FROM `lomas`.`results` LIMIT 587216, 10486;

SELECT * FROM `lomas`.`results` LIMIT 597702, 10486;

SELECT * FROM `lomas`.`results` LIMIT 608188, 10486;

SELECT * FROM `lomas`.`results` LIMIT 618674, 10486;

SELECT * FROM `lomas`.`results` LIMIT 629160, 10486;

SELECT * FROM `lomas`.`results` LIMIT 639646, 10486;

SELECT * FROM `lomas`.`results` LIMIT 650132, 10486;

SELECT * FROM `lomas`.`results` LIMIT 660618, 10486;

SELECT * FROM `lomas`.`results` LIMIT 671104, 10486;

SELECT * FROM `lomas`.`results` LIMIT 681590, 10486;

SELECT * FROM `lomas`.`results` LIMIT 692076, 10486;

SELECT * FROM `lomas`.`results` LIMIT 702562, 10486;

SELECT * FROM `lomas`.`results` LIMIT 713048, 10486;

SELECT * FROM `lomas`.`results` LIMIT 723534, 10486;

SELECT * FROM `lomas`.`results` LIMIT 734020, 10486;

SELECT * FROM `lomas`.`results` LIMIT 744506, 10486;

SELECT * FROM `lomas`.`results` LIMIT 754992, 10486;

SELECT * FROM `lomas`.`results` LIMIT 765478, 10486;

SELECT * FROM `lomas`.`results` LIMIT 775964, 10486;

SELECT * FROM `lomas`.`results` LIMIT 786450, 10486;

SELECT * FROM `lomas`.`results` LIMIT 796936, 10486;

SELECT * FROM `lomas`.`results` LIMIT 807422, 10486;

SELECT * FROM `lomas`.`results` LIMIT 817908, 10486;

SELECT * FROM `lomas`.`results` LIMIT 828394, 10486;

SELECT * FROM `lomas`.`results` LIMIT 838880, 10486;
</details>


Version:
![image](https://github.com/user-attachments/assets/42b994a3-cc3d-40b1-8275-d9b198607404)

**Comment by marcelhaase** [comment] 2024-08-11 14:08
More Details:

Connection:
![image](https://github.com/user-attachments/assets/679f9fb2-dbfe-4bf3-83fe-a41455d4ba92)

Tested with mySQL 5.5 and MariaDB 10.1.21. (Both same result)

**Comment by ansgarbecker** [comment] 2024-08-12 10:10
Very strange, I still cannot reproduce that here.

Can you please paste the whole content of the log panel here? Best would be you just open HeidiSQL, do the export and then copy the log lines. And please remove sensitive details if any.

**Comment by marcelhaase** [comment] 2024-08-12 10:14
Hey @ansgarbecker,

because I don't understand the problem. I have now downloaded the 12.8 portable version and extract it to a fully different folder.
After set up the connection details and check for "get full table status is activated" the export is running correctly with the correct calculated LIMIT.

If I copy the old portable_settings.txt into the extracted folder the LIMIT is 10486 for each table.
If I delete the settings file and let the program create a new one, it works with the correct LIMIT.

So, It looks like that there is a problem with reusability of the settings file.

I will come back to you shortly with more details.

**Comment by marcelhaase** [comment] 2024-08-12 10:59
> Very strange, I still cannot reproduce that here.
> 
> Can you please paste the whole content of the log panel here? Best would be you just open HeidiSQL, do the export and then copy the log lines. And please remove sensitive details if any.

Hello @ansgarbecker ,

I have taken another table "reports_transfer_log" where only some rows / data is included for your export log.
Here the "show table status" of that table:
![image](https://github.com/user-attachments/assets/092c39eb-fc9e-4c3b-a8f0-a963aa220c66)

Export-Log of Export with upgraded version:
[20240812_1250_static_limit.log](https://github.com/user-attachments/files/16580570/20240812_1250_static_limit.log)

Export-Log of Export with new downloaded portable version:
[20240812_1250_correct_limit.log](https://github.com/user-attachments/files/16580573/20240812_1250_correct_limit.log)

Best regards, Marcel

**Comment by bchanudet** [comment] 2024-08-13 06:57
Hello,

Thank you @marcelhaase for your investigation, you might be on something with the way the saved settings are used. 

I downloaded too the portable version, imported the settings from the then-installed version, and this time the export used the "avg_row_length" value, as the limit used was 118 records instead of 10486. 

So I uninstalled completely HeidiSQL via Windows settings, cleaned out the HeidiSQL registry entry that stores all the configuration, and reinstalled it from scratch. Unfortunately, after reimporting the connection settings, the limit used was still 10486.

I will try today with a "completely from scratch" install, without using the import settings feature, but by filling manually all the connection parameters to see if there's anything different.

**Comment by ansgarbecker** [comment] 2024-08-17 10:39
Good find @marcelhaase ! And quite strange, as there are even more values empty, in the database tab:
Disabled "Group objects by type":
![grafik](https://github.com/user-attachments/assets/574100f4-36eb-445e-903a-1709e9f0656e)

Enabled "Group objects by type":
![grafik](https://github.com/user-attachments/assets/c9a259b1-ea56-4bca-8362-352494be04ca)

**Comment by ansgarbecker** [comment] 2024-08-17 11:03
Fixed in the next build.

**Closed by ansgarbecker** 2024-08-17 11:03 UTC
Labels: bug, confirmed
