### ISSUE TITLE
[12.1.0.6537] Crash when closing Query-TAB

### ISSUE THREAD

**Issue by Commifreak** [HeidiSQL/HeidiSQL#1640] opened 2022-08-15 09:55 UTC
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: MySQL 5.7
* OS: Win10

**Describe the bug**

I just upgraded to the new version, started it and just wanted to close one single Query tab (which was left open last time). Just after hit the X a crash appeared:
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/9336448/bugreport.txt)

**To Reproduce**

Close any Query tab in new version

**Screenshots or Crash reports**

**Comment by Commifreak** [comment] 2022-08-15 09:58
Not always reproducible. With current new tabs, it works. Maybe an issue with query tabs from older stable release?

**Comment by ansgarbecker** [comment] 2022-08-15 18:01
The callstack points towards some `MouseUp` event, but the close button on it does not call any of the contained methods. Scratching my head.

**Comment by jbrunette** [comment] 2022-08-23 20:49
I can reproduce this. It's related to the width of SQL editor panel in some way.

On my 4K monitor, I can trigger the issue if the SQL editor panel is between 3048 and 3326 pixels wide (approximately, not sure exactly where the panel UI element starts/ends). Any skinnier/wider and the issue doesn't occur.

I'm assuming it's the SQL editor panel because the issue can be triggered by adjusting either the left gripper (separating the tree from the rest of the UI) or the right gripper (separating the SQL editor panel from the "helper" panel that has "Columns", "SQL functions", etc).

So, a work around is to adjust the widths of either the left panel or the right helper panel until the problem no longer happens.

**Comment by jbrunette** [comment] 2022-08-24 13:36
Also, it only happens if the X is clicked on the tab. Double-clicking or middle-clicking the tab doesn't trigger the error.

**Comment by ansgarbecker** [comment] 2022-08-27 09:33
I am not able to reproduce it here, even not with a very wide editor panel, with a click on the X of a previously opened tab.

**Comment by ansgarbecker** [comment] 2023-10-23 17:34
Still happening for some users, in the latest builds. And still I have no clue what's happening.

```
006b2836 heidisql.exe Vcl.Controls           TControl.GetClientWidth
008761a7 heidisql.exe Vcl.Buttons            TCustomSpeedButton.MouseUp
006b6822 heidisql.exe Vcl.Controls           TControl.DoMouseUp
006b68e6 heidisql.exe Vcl.Controls           TControl.WMLButtonUp
0040f621 heidisql.exe System                 TObject.Dispatch
006b5aad heidisql.exe Vcl.Controls           TControl.WndProc
006b55b0 heidisql.exe Vcl.Controls           TControl.Perform
006bc48a heidisql.exe Vcl.Controls           TWinControl.IsControlMouseMsg
006bcd17 heidisql.exe Vcl.Controls           TWinControl.WndProc
006bc09a heidisql.exe Vcl.Controls           TWinControl.MainWndProc
005d43f3 heidisql.exe System.Classes         StdWndProc
7ffd776e USER32.dll                          DispatchMessageW
00857a4e heidisql.exe Vcl.Forms              TApplication.ProcessMessage
00857ac3 heidisql.exe Vcl.Forms              TApplication.HandleMessage
00857f1a heidisql.exe Vcl.Forms              TApplication.Run
011c5e98 heidisql.exe heidisql       115 +41 initialization
7ffd7906 KERNEL32.DLL                        BaseThreadInitThunk
7ffd7960 ntdll.dll                           RtlUserThreadStart
```

**Comment by ansgarbecker** [comment] 2023-10-23 19:12
Hopefully fixed in the current build... crossing finger.

**Closed by ansgarbecker** 2023-10-23 19:12 UTC
Labels: bug

**Comment by jbrunette** [comment] 2023-10-24 13:50
Looks good. I was able to reliably reproduce it but I cannot with heidisql64.r6744.exe.
