### ISSUE TITLE
Error while creating table copy

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#1244] opened 2020-12-02 08:02 UTC
The problem is that when database field is `varchar`,  the size is missing, so the `create` SQL code is syntactically incorrect. This was not the case a couple of versions back.

![2020-12-02_095908](https://user-images.githubusercontent.com/8297417/100845080-58cc2280-3485-11eb-8cbf-f1a724862a47.png)

**Comment by ansgarbecker** [comment] 2020-12-02 17:21
Please use the template for issue reports, and especially include the server version.

From first sight I'd say this is the same as #1245

**Comment by budiony** [comment] 2020-12-02 18:13
The server version is Maria DB 10.4.13

**Comment by ansgarbecker** [comment] 2020-12-03 07:06
Which length do these VARCHAR's have when you run `SHOW FULL COLUMNS FROM xyz`?

**Comment by ansgarbecker** [comment] 2020-12-03 20:57
I'm closing this, as I suppose this is a duplicate of issue #1245. If you retry with the latest build and the problem persists, please shout.

**Closed by ansgarbecker** 2020-12-03 20:57 UTC
Labels: needs-info, nettype-mysql

**Comment by budiony** [comment] 2020-12-04 09:37
![1111](https://user-images.githubusercontent.com/8297417/101147443-0d507a80-3625-11eb-95ab-e17694e32641.png)

**Comment by ansgarbecker** [comment] 2020-12-04 09:39
Please re-check the SQL code in the table designer.
