### ISSUE TITLE
Unable to create BIT fields (invalid SQL code quotes escaping)

### ISSUE THREAD

**Issue by IgorTimofeev** [HeidiSQL/HeidiSQL#1211] opened 2020-11-09 12:32 UTC
Bug happens every time on creating/modifying table fields with BIT value type. As result, 11.1.0.6116 version is just impossible to be used with DBs with lots of BIT fields

**How to reproduce:**

1. Create any BIT field

![image](https://user-images.githubusercontent.com/11760002/98540914-b19e0600-229f-11eb-92af-056ff19defda.png)

2. Click "Save"

3. See error:

![image](https://user-images.githubusercontent.com/11760002/98540969-c4b0d600-229f-11eb-9f0b-0b54a586b7a7.png)

Reason is just inadequate quotes escaping:

```sql
ALTER TABLE `settings` ADD COLUMN `test` BIT(1) NOT NULL DEFAULT 'b\'0\'' AFTER `pdf_orientation`;
/* Ошибка SQL (1067): Invalid default value for 'test' */
```

**Expected behavior**:

It would be great if the table viewer can show BIT fields default values as **b'0'** and not **b'\\'0\\''**, because it's slightly unreadable:

![image](https://user-images.githubusercontent.com/11760002/98541397-7223e980-22a0-11eb-8f8b-97a05ddc1272.png)

**Environment:**
 - Windows 10
 - HeidiSQL 11.1.0.6116
 - Database  MySQL 8.0.21

**Comment by Alamei** [comment] 2021-03-01 02:49
It looks like this is the same bug as #1037, which means it's been outstanding for at least 10 months now. Is there anything we can do to provide additional information to help track this down if it's only occurring for some of us and not others, or is the behavior universal? As @IgorTimofeev notes, this bug does currently make Heidi non-functional when editing tables with BIT fields through the GUI.

**Comment by ansgarbecker** [comment] 2024-06-21 11:28
Duplicate of #1663. Should be fixed in the latest build.

**Closed by ansgarbecker** 2024-06-21 11:28 UTC
