### ISSUE TITLE
copy-as >SQL INSERTs generate wrong SQL-Code, if datacolumns are hidden  [Export-As >SQL INSERTs works fine]

### ISSUE THREAD

**Issue by Padina42** [HeidiSQL/HeidiSQL#1358] opened 2021-04-18 09:35 UTC
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version:  Database type and version: mysql Ver 15.1 Distrib 10.2.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* OS: OS: Windows 10 (/ Docker/ddev

**Describe the bug**

Second try, because it was closed without testing the bug.
The **Copy-as** > SQL INSERTs-Option use everytime the short form for full-row-insert.
That syntax will fail, if you copy only a selected subset of columns from a table.

The *Export-as*-function works fine. The settings from the export-as-function won't be used in the Copy-as- SQL-INSERTs-Function.

**To Reproduce**

1.    Data-view of a table and hide some colum
2.    Mark rows and do action 'copy as > SQL INSERTs'
3.   You get a list of INSERT-SQL in this style 'INSERT INTO tx_simpledataedittest_domain_model_child VALUES (1618082987, 3, ...'
    (The hidden values are missing, (good), The list of selected column-names after the table-name is missing too. (bad) )
4.    You paste the copy in the query-window and let it run. I got the error-Message: "SQL Fehler 1136: Column count doesn't match value count at row 1."

**Screenshots or Crash reports**

![2021-04-18 11_31_43-dueddelei – ResetDatasForTestUpgrade php](https://user-images.githubusercontent.com/8037773/115140858-b67a9900-a039-11eb-82c1-1a304c0fc144.png)
![2021-04-18 11_29_18-Window](https://user-images.githubusercontent.com/8037773/115140860-b7132f80-a039-11eb-95aa-05c9c3e4d037.png)
![2021-04-18 11_19_57-Window](https://user-images.githubusercontent.com/8037773/115140861-b7132f80-a039-11eb-80e4-8e966777a930.png)

**Comment by Padina42** [comment] 2021-04-18 14:04
@ansgarbecker Thanks for your patience and your hints.

This is not a function-bug, but an UI-bug. 
I made two mistakes.
1. I don't get the idea, that the settings for the context-sensitve 'Copy-As' are locatend in the context-sensitive menu of 'export-as'.
2. I don'r realize, that the settings of 'export-as' and 'copy-as' different. You have to override the settings for 'copy-as' with the settings from the form in the 'export-as'-form throup pressing the button 'Kopieren-Einstellungen' 

There is no bug in the functionality.  
Buut the UI (unser-interface) for the context-sensitive settings are not intuitivly usable, 

I would suggest to refactor the UI for this part.

P.S. A simliar UI was described by Mike-Krüger in a German Schlager 'Der Nippel': https://www.youtube.com/watch?v=H4qT0asSD1M
translate by google: "You just have to pull the nipple through the tab
and turn it all the way up with the little crank
an arrow appears immediately
and then you press it
and the tube opens! "

**Comment by ansgarbecker** [comment] 2021-04-18 15:37
Duplicate of #1357

**Closed by ansgarbecker** 2021-04-18 15:37 UTC
