### ISSUE TITLE
Snippet Management

### ISSUE THREAD

**Issue by Screaminlean** [HeidiSQL/HeidiSQL#1720] opened 2022-12-07 13:54 UTC
Love the application but it would be nice if the snippet window supported subdirectories for better organisation.
I have seen this asked for on the forum post [here](https://www.heidisql.com/forum.php?t=19070#p38112) 7 years ago.

**Comment by ansgarbecker** [comment] 2022-12-07 14:26
Duplicate of #1399

**Closed by ansgarbecker** 2022-12-07 14:26 UTC
