### ISSUE TITLE
String-Escape Sequence actually ends string on Copy, Export and TextEditor

### ISSUE THREAD

**Issue by styler2go** [HeidiSQL/HeidiSQL#191] opened 2018-03-13 15:33 UTC
## Steps to reproduce this issue

1. Save a long string with \0 in it into a TEXT-column
2. Open Data View and try to preview/edit the string
3. The string will only be visible until \0

## Current behavior

![9535942](https://p.styler2go.de/9535942)

The preview / edit window will only show the string until the \0 string (excluding the \0)

Exporting the string as SQL INSERT is a workaround to get the full value out of the database.

## Expected behavior

HeidiSQL should escape user texts and ignore the \0.

## Environment

Windows 10 on multiple Versions and PCs.

* **HeidiSQL version:** 
Bug is existing since many versions. Current: 9.5.0.5261
* **Database system and version:** 
MySQL 5.7.10
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment] 2022-04-13 05:07
Duplicate of #202

**Closed by ansgarbecker** 2022-04-13 05:07 UTC
