### ISSUE TITLE
Organize tables in folder or tags

### ISSUE THREAD

**Issue by EliezerSolinger** [HeidiSQL/HeidiSQL#1287] opened 2021-01-20 19:03 UTC
I have hundreds of tables in my database. It would be nice if there was a way to organize them by folders or tags. I imagine it would be very useful for users like me. thanks in anyway.

**Comment by ansgarbecker** [comment] 2021-01-20 20:00
Please do not remove the issue template.

Duplicate of #502

**Closed by ansgarbecker** 2021-01-20 20:00 UTC
