### ISSUE TITLE
Hide default tab

### ISSUE THREAD

**Issue by Tezei** [HeidiSQL/HeidiSQL#1310] opened 2021-02-11 11:19 UTC
Hiya guys! Heidi SQL is my favorite tool for sql development. It will be very useful to be able to close default query tab not to change script when I need to change something. It is very uncomfortable to stay always 1 tab opened if there is no need. For example when you have a script file opned and you start HeidiSQL and you need to use the same you should press ctrl+A and delete, especially when an important file is in default tab. Thanks in advance.

**Comment by ansgarbecker** [comment] 2021-02-11 20:55
Do not delete the issue template. That leads to closing the issue.

This particular request is also a duplicate of #365 . Please search for the same request before you write one.

**Closed by ansgarbecker** 2021-02-11 20:55 UTC
