### ISSUE TITLE
EEncodingError

### ISSUE THREAD

**Issue by Commifreak** [HeidiSQL/HeidiSQL#597] opened 2019-04-04 07:31 UTC
## Steps to reproduce this issue

1. Step 1; Run sql file
2. Step 2; Error occurs

## Current behavior
When I try to run a specific sql, i get an `EEncodingError`. I have absolutely no idea whats wrong here. Unfortunately I cant directly post the file contents here, maybe we can break it down more?

## Expected behavior
Run SQL succeed

## Environment

* **HeidiSQL version:** HeidiSQL 10.1.0.5464
  
* **Operating system:** Win10x64 1809 17763.379
  

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3042172/bugreport.txt)

**Comment by ansgarbecker** [comment] 2019-04-07 09:16
Duplicate of #515

**Closed by ansgarbecker** 2019-04-07 09:16 UTC
