### ISSUE TITLE
SSL connection error: no cipher match.Error 0x80090331(SEC_E_ALGORITHM_MISMATCH)

### ISSUE THREAD

**Issue by aljqiang** [HeidiSQL/HeidiSQL#1843] opened 2023-08-28 08:09 UTC
**Preconditions**

* HeidiSQL version: 12.5.0.6685
* Database type and version: MySQL 5.7.42-enterprise-commercial-advanced-log
* OS: Window 10

**Describe the bug**

We're unable to connect via Use SSL option under windows 10 to MySQL 5.7.42 server. It's complaining about cipher. We've tried using different libraries, however no luck.

**To Reproduce**

1.Go to connection SSL tab, browse correct certificates
2.Try to connect to MySQL 5.7.42 server

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/11271202/361cc26c-69ea-49bb-bf34-84db4a5d60fa)

**Comment by sambenne** [comment] 2023-09-07 09:07
I am getting this issue, it is rather annoying. It seems HeidiSQL does not work with SSL at all. Even trying to update the user accounts does not work as it resets back to No SSL

![image](https://github.com/HeidiSQL/HeidiSQL/assets/363734/4976fce1-dce4-4855-bbe0-2d5fe0a3d55a)

**Comment by Lotendan** [comment] 2023-09-22 10:56
Duplicate of https://github.com/HeidiSQL/HeidiSQL/issues/1426 ?

**Comment by ansgarbecker** [comment] 2024-05-29 05:44
Definitely a duplicate of issue #1426  and #1768 .
By the way, the latest nightly built installer has a fix for this, including a libmysql from MySQL 8.

**Closed by ansgarbecker** 2024-05-29 05:44 UTC
Labels: bug, ssl
