### ISSUE TITLE
Blank Themes / White Text on Windows 11

### ISSUE THREAD

**Issue by DoomChryz** [HeidiSQL/HeidiSQL#1465] opened 2021-10-18 07:53 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: not in use
* OS: Windows 11 Pro 10.0.22000 Build 22000

**Describe the bug**

When using HeidiSQL, changing the theme causes Text to disappear, unable to change it back.

**To Reproduce**

1. Install HeidiSQL on Windows 11
2. Change Theme
3. Changing Theme Back to regular one doesnt fix
4. Deinstalling and Reinstalling doesnt fix

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/19556660/137690155-4e39fd3a-2d45-48ad-967e-f1917dfa554a.png)

**Comment by DoomChryz** [comment] 2021-10-19 09:53
> I suspect the particular theme you selected to have this issue. Do you remember which theme it was?

I think ive choosen the Windows 11 Dark at first? I can check later the day. The Dropdownbuttons where able to display text. Inside them.

**Comment by ansgarbecker** [comment] 2022-06-22 05:17
I just did the same on Win11 (build 22000.556 21H2 Enterprise) with the latest Heidi build. Either that was fixed by the newer libraries, or the Windows build you were using had an issue. I can't reproduce this here. Can you still reproduce this issue with HeidiSQL v12.0?

**Closed** 2024-07-10 08:37 UTC
Labels: bug, themes
