### ISSUE TITLE
Runtime Exception when trying to modify MSSQL 2019 database

### ISSUE THREAD

**Issue by replydev** [HeidiSQL/HeidiSQL#1495] opened 2021-12-07 08:58 UTC
# **Preconditions**

* HeidiSQL version: **11.3.0.6373**
* Database type and version: **Microsoft SQL Server 2019 15.0.2080.9** - Hosted in a Windows Server 2019 Machine
* OS: **Windows 10 Enterprise x64 20H2 Build 19042.1237**

# **Describe the bug**

When i try to modify databases the program goes in an runtime error. It's not possible to find the stored procedure SHOW.

 # **To Reproduce**

1. Connect to your MSSQL 2019 server
2. Right click in a database
3. Click Modify

# **Screenshots or Crash reports**

## [bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/7666890/bugreport.txt)
![error](https://user-images.githubusercontent.com/43727434/144997203-dc0ad347-d548-4f84-9c7e-06d11159eb1d.png)

**Comment by ansgarbecker** [comment] 2021-12-07 09:03
Relevant part of the crash callstack:
```
exception class    : EDbError
exception message  : Errore SQL (2812): Non è stato possibile trovare la stored procedure 'SHOW'.

main thread ($640):
00cdf7d1 heidisql.exe dbconnection    3505 +45 TAdoDBConnection.Query
00d05200 heidisql.exe dbconnection    7649  +3 TAdoDBQuery.Execute
00ce90e6 heidisql.exe dbconnection    4640 +19 TDBConnection.GetResults
00ceb4dc heidisql.exe dbconnection    5073  +1 TDBConnection.GetVar
00f5a7b7 heidisql.exe createdatabase    84 +26 TCreateDatabaseForm.FormShow
```

I suppose the problematic query (shown in the log panel) is something like `SHOW CREATE DATABASE xyz`?

**Comment by ansgarbecker** [comment] 2021-12-07 09:04
Duplicate of #95

**Closed by ansgarbecker** 2021-12-07 09:04 UTC
