### ISSUE TITLE
Image Preview "No image detected"

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#421] opened 2018-12-03 12:58 UTC
Just discovered that HeidiSQL has image preview feature https://www.heidisql.com/forum.php?t=5883

However it did not work for 9.5.0.5196 (64bit) version

It always says:  "No image detected"

All images are .jpg content

**Comment by ansgarbecker** [comment] 2018-12-03 18:49
You should not delete the whole issue template. As written, these will normally be ignored. Please post an `INSERT` query with one jpg content here.

**Comment by ansgarbecker** [comment] 2018-12-04 16:43
Works here:
![grafik](https://user-images.githubusercontent.com/7986591/49457896-03080580-f7ec-11e8-9f29-ae2829c194f2.png)
Likely a problem with the content, which nay not be supported by Heidi's image previewer.

**Comment by paulvi** [comment] 2018-12-05 03:01
Is there description of limitation of that previewer?

Because my impression is that imagepreview gets data, but than something prevents from actually showing (the view control seems to blink)

I can only assure that saved data in db is correct, I can export and import with Java code.
Also other db tool can preview.

```java
            byte[] image = p.getPhoto();
            String path = ....);
            if (image == null){
                logger.warn("{} image == null", path);
                continue;
            }
            try (RandomAccessFile file = new RandomAccessFile(path, "rw") ) {
                file.write(image);
            } catch (IOException e1) {
                logger.warn("{} {}", path, e1.getMessage());
                continue;
            }
```

**Comment by paulvi** [comment] 2018-12-05 03:11
I checked, this is not related to image size 64K barrier, 
as some images are up to 100K.

The MySQL field type is `MEDIUMBLOB` that is up to 16MBytes
Can this specific  field type be issue?

**Comment by ansgarbecker** [comment] 2018-12-05 07:05
`MEDIUMBLOB` is perfect for storing images, as long as they're smaller than 16m.

But as said, HeidiSQL supports a limited number of file formats here: jpg, gif, bmp and png. Also, some sub formats seem to be not supported, although I'm quite unsure here. All I can do is test that with your image, and examine the file, and probably add support for that format to HeidiSQL if it's some of these sub formats.

**Comment by paulvi** [comment] 2018-12-05 11:10
I can assure that db content is correct as we are exporting and can use other tools to see image.

The problem seems to be #428 - size of BLOB is shown incorrectly by HeidiSQL 9.5.0.5196.

Maybe there other way to conveniently observe BLOB size,  
if not here it is #429 show BLOB size in image preview.

**Comment by ansgarbecker** [comment] 2019-01-03 16:54
I assume you still get that "No image detected" on some?
I have just tested with 45 images PNG and JPG files, without a problem. So I don't have anything to reproduce the issue. Can you provide an image which fails to show? I guess I have to close this otherwise.

What you could also do while testing is to press or unpress the "binary data as text" button:
![grafik](https://user-images.githubusercontent.com/7986591/50650389-8ef28600-0f80-11e9-9a66-c464f93dc675.png)

**Comment by paulvi** [comment] 2019-01-20 11:32
I don't have db that I could share,
but we are having this issue for all instances.

Let me try to do new db with just one test image, so that I could export that db to reproduce this issue.  

TODO

P.S. Nice to know about one more feature

**Comment by paulvi** [comment] 2019-03-01 02:11
Hopefully image detection is not running when this view is not visible,  
other wise it could slow down Heidi like in #548

**Comment by ansgarbecker** [comment] 2019-05-01 06:45
@paulvi could you please attach a test image or an export so we can proceed here?

**Comment by paulvi** [comment] 2019-05-05 03:46
![15889583899_20181205110655](https://user-images.githubusercontent.com/1614482/57188059-2bc33100-6f2b-11e9-878f-2a546f9577d1.jpg)

Images are taken from Android client.

I guess this issue is actually JPG format support, as what most people have as `.jpg` files can actually be different variations.  
And possibly the lib for that wihtin HeidiSQL needs update.

**Comment by paulvi** [comment] 2019-05-05 05:25
P.S. I can say that it is not only because of specific Android JPG library,  
as there are other images coming from different other sources, 2KB to 1MB.    
But default now is 360x480 witch gives about 16KB file size.

**Comment by ansgarbecker** [comment] 2019-05-05 13:51
That specific image works here, without problems:

![grafik](https://user-images.githubusercontent.com/7986591/57194967-79e92c00-6f4d-11e9-9522-96f6e179437c.png)

So you will need to attach or even better link one or more jpg files which don't work for you.

**Comment by paulvi** [comment] 2019-05-06 06:58
TODO for me

**Comment by ansgarbecker** [comment] 2024-02-09 07:35
Closing due to missing feedback.

**Closed by ansgarbecker** 2024-02-09 07:35 UTC
Labels: needs-info
