### ISSUE TITLE
Cant clear query history

### ISSUE THREAD

**Issue by G3ph4z** [HeidiSQL/HeidiSQL#168] opened 2018-02-28 13:56 UTC
## Steps to reproduce this issue

1. Go to query tab
2. Open the Query History
3. Right Click and select -> Clear Query history

## Current behavior
An error occurred in the application
`No path set, won't delete root key Software\HeidiSQL\.`

## Expected behavior

Clearing history

## Possible solution

-

## Environment

* **HeidiSQL version:** 
  9.5.0.5255
* **Database system and version:** 
  MariaDB-10.2.9
* **Operating system:** 
  Windows 10 x64

**Comment by ansgarbecker** [comment] 2018-02-28 16:34
Ok, I could just successfully clear the history, without getting the above error. So you must have done something different than I did. Perhaps there was an error before, and this is some follow up error?
Can you reproduce that?

**Comment by G3ph4z** [comment] 2018-02-28 16:39
We reproduced it on 4 PCs in the office. I get this error after I clicked to the button. But I can clear today's history, just cant delete the old ones.

**Comment by rentalhost** [comment] 2018-02-28 16:50
Same here: can't reproduce. 

Instead of that, I found two possible bugs related to Query History tree: #170 and #171.

**Comment by G3ph4z** [comment] 2018-02-28 17:02
#170 It's very similar to my problem

**Comment by G3ph4z** [comment] 2018-02-28 18:53
Tested my home pc, and same issue:
http://prtsc.denes.cloud/firefox_2018-02-28_19-52-36.png

**Comment by ansgarbecker** [comment] 2018-02-28 19:18
#170 is the same issue, going to close that one.

**Comment by ansgarbecker** [comment] 2018-06-26 18:58
Sorry, closed by mistake

**Closed** 2019-05-03 05:46 UTC
Labels: bug

**Comment by ansgarbecker** [comment] 2019-05-03 05:49
Finally I could reproduce it, for some reason. The confirmation dialog was resetting the settings path to the history, so the "delete path" method made an emergency stop with a crash (which is better than deleting the root key for all settings). Fix was to set it again after that message dialog.
