### ISSUE TITLE
Double menu on 250% scaling after move to 2nd screen

### ISSUE THREAD

**Issue by wrufeger** [HeidiSQL/HeidiSQL#446] opened 2018-12-17 08:14 UTC
## Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/524191/50074170-5b230c80-01db-11e9-99dc-a5a2cc19ed9d.png)

After updating to build 5405 the menu  doubled with the second bigger one not clickable.
The missing save & cancel buttons in table edit window disappeared a few versions earlier. 

## Possible solution

Maybe using code from earlier versions, since it used to work and display perfectly before.

## Environment

* Windows 10 Professional (1809, build 17763.194)
* HeidiSQL 9.5.0.5405
* MariaDB 10.1.30

**Comment by ansgarbecker** [comment] 2018-12-17 11:14
To what percentage is your DPI scaling set?

**Comment by wrufeger** [comment] 2018-12-17 12:35
Its set to 250% on a 4K display.

**Comment by ansgarbecker** [comment] 2018-12-17 20:49
The hidden buttons are reported in #440

**Comment by wrufeger** [comment] 2018-12-18 21:15
Probably only my problem or not worthy to fix. I do use 2 screens, the main one is a 28" 4k display at 150%, the second one is a 17" 4k laptop display at 250%.
The "bug" is reproduceable by starting the program on the laptop screen (250%) and moving to the other display. If I do it the other way the menu disappears completely. Very few times it just happens without moving, but it didn't show after setting scaling of both displays to the same value.

**Comment by ansgarbecker** [comment] 2018-12-19 18:56
Thanks for the update. In that case this may be related to #378 .

**Comment by Jerry-Shaw** [comment] 2018-12-20 02:36
![7 euilpij 8kjlu5dbzwu1](https://user-images.githubusercontent.com/13212198/50260364-a12dd980-0442-11e9-967e-03661707ea30.png)
And this too. 
Latest nightly build. On 4K screen, 250% scale.
Open any table, click "CREATE code". The columns are too long in horizon scrolling.

**Comment by ansgarbecker** [comment] 2018-12-22 14:55
Growing column widths in table editor should be fixed in the next build.

**Comment by Jerry-Shaw** [comment] 2018-12-23 04:10
Good, thanks.

**Comment by Jerry-Shaw** [comment] 2018-12-24 02:49
Tested, fixed. 
But, is the current line height twice the height than the version before? Seems a little too large.

**Comment by Jerry-Shaw** [comment] 2018-12-24 06:10
![ao thar 7kf85 pkf c v](https://user-images.githubusercontent.com/13212198/50392023-7b2b7080-0785-11e9-8d77-a1fc8955d950.png)
But, the latest build, in this area, content is over flow.

**Comment by ansgarbecker** [comment] 2018-12-24 11:38
Can confirm that. But please post separate reports for different topics. This here is still the "double menu" issue.

**Comment by Jerry-Shaw** [comment] 2018-12-25 02:10
OK, reopened. Thanks for your work for us.

**Comment by Saibamen** [comment] 2019-01-10 12:38
Similar: https://github.com/HeidiSQL/HeidiSQL/issues/479

**Comment by rentalhost** [comment] 2019-05-20 11:14
Really, HeidiSQL get very confused when two monitors are in different resolutions and DPI. I have tested in a 4k+250% and 1080p and every time that I move it from a monitor to another it turns worse.

There are some way to force repaint/reflow all program when it is moved to another monitor?

**Comment by tothandor** [comment] 2019-05-30 10:13
HeidiSQL 9.5, does not had this issue. What has changed since? 
It seems that the problem came with themes and icon packs. I can live without these.

**Comment by ansgarbecker** [comment] 2019-05-30 10:33
It's not caused by themes nor the new icons. Scaling problems are more noticable since v10.0 as I activated the `dpiAware` flag in [HeidiSQL's manifest](https://github.com/HeidiSQL/HeidiSQL/blob/master/res/manifest.xml). Here's an explanation I posted in #378:

> v9.5 scales correctly, but looks blurry with high DPI settings - this was discussed in #213. It may look ok enough for some people, but this is just a backward compatibility logic from Microsoft. The right way to go is the complex one - scale every component separately, to make them look sharp. Though that's really hard work, and v10.1 is the first version with support for that, so please have a bit of patience here.

**Comment by tothandor** [comment] 2019-05-30 13:02
[Creators update](https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1703_(Creators_Update)) has brought some updates for Windows 10, which have affected high-DPI problems, and since then HeidiSQL 9.5 runs without blurring on any of my screens, without being dpiAware.

**Comment by ansgarbecker** [comment] 2019-05-30 13:40
I'm curious - could you post a screenshot of HeidiSQL then?

**Comment by tothandor** [comment] 2019-05-31 10:24
Attached a screenshot after moving HeidiSQL 9.5 between a screen with 125% DPI scaling and one with no DPI scaling (100%) a few times. And the same with dpiAware HeidiSQL 10.
![image](https://user-images.githubusercontent.com/4449214/58699732-80c55c00-839e-11e9-8765-d22504d415b7.png)
![image](https://user-images.githubusercontent.com/4449214/58699891-efa2b500-839e-11e9-832e-98490edfb199.png)

**Comment by ansgarbecker** [comment] 2019-05-31 16:19
Accidentally closed. Thought I was closing a different one...

**Comment by oemmes** [comment] 2019-06-03 06:40
I can confirm that 9.5 works well on multiple monitors with different DPI scaling on Windows 10 .

I use 3 monitors - 100% (laptop monitor), 200% (main screen) and 150% - and moving HeidiSQL 9.5 from one monitor to the other does not cause any problems.

Version 10 unfortunately is not usable for me as many things do not fit (buttons, editboxes, text in tables, ...). I tried to enable High DPI compatibility settings from Windows 10 which caused that the layout was mostly okay but I had to decrease the font size in the HeidiSQL settings to make it fit somehow.

Nonetheless many thanks for the great software! It helps me a lot every day :-)

**Comment by ansgarbecker** [comment] 2019-07-07 07:32
Here we can see the toolbars and buttons height when moving between different DPI monitors:

```
ppi:96 ControlBarMain.Height:26 ToolBarMainButtons.Height:22 ToolBarMainButtons.ButtonHeight:22 Toolbutton5.Height:22
ppi:168 ControlBarMain.Height:51 ToolBarMainButtons.Height:47 ToolBarMainButtons.ButtonHeight:47 Toolbutton5.Height:47
ppi:96 ControlBarMain.Height:39 ToolBarMainButtons.Height:35 ToolBarMainButtons.ButtonHeight:35 Toolbutton5.Height:35
ppi:168 ControlBarMain.Height:73 ToolBarMainButtons.Height:69 ToolBarMainButtons.ButtonHeight:69 Toolbutton5.Height:69
ppi:96 ControlBarMain.Height:51 ToolBarMainButtons.Height:47 ToolBarMainButtons.ButtonHeight:47 Toolbutton5.Height:47
ppi:168 ControlBarMain.Height:94 ToolBarMainButtons.Height:90 ToolBarMainButtons.ButtonHeight:90 Toolbutton5.Height:90
ppi:96 ControlBarMain.Height:63 ToolBarMainButtons.Height:59 ToolBarMainButtons.ButtonHeight:59 Toolbutton5.Height:59

```

**Closed** 2019-07-07 07:42 UTC
Labels: high-dpi

**Comment by ansgarbecker** [comment] 2019-07-07 07:46
I just pushed a change which fixes the height of the toolbar when moving between screens. This does not yet address the other issues, like growing form sizes and such, which are reported in the other DPI tickets, like #378.
