### ISSUE TITLE
Fails to start - Attempts to write to \Program Files\WindowsApps\...\portable_settings.txt - Write Access restricted.

### ISSUE THREAD

**Issue by JayS4** [HeidiSQL/HeidiSQL#700] opened 2019-07-03 20:25 UTC
## Steps to reproduce this issue

1. open Heidi
2. Then I get "Error: Cannot create file "C:\Program Files\WindowsApps\2691AnsgarBeckerS...\protable_settings.txt"  Access Denied.

## Current behavior

Unable to start as file is in a protected read/execute area you are attempting to write in.
Working Yesterday before i exited.  I had imported a list of servers but it worked yesterday.

## Expected behavior

program to start.

## Possible solution

select a non-protected area like in \Users\<username>\AppData\... 

## Environment

* **HeidiSQL version:**  latest
BUG REPORT ATTACHED

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3356711/bugreport.txt)
 download

  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment] 2019-07-03 21:41
I just resubmitted a version which should not have that portable.lock file shipped in the appx installer. I already did that several times but I recall I did that in the same "submission" in the store administration. This time I created a submission no. 4 and hope it gets updated at all, since the version 10.2 has not changed yet.

**Comment by JayS4** [comment] 2019-07-03 23:47
Thanks.

Jay 
 
  On Wed, Jul 3, 2019 at 5:41 PM, Ansgar Becker<notifications@github.com> wrote:   
I just resubmitted a version which should not have that portable.lock file shipped in the appx installer. I already did that several times but I recall I did that in the same "submission" in the store administration. This time I created a submission no. 4 and hope it gets updated at all, since the version 10.2 has not changed yet.

**Comment by HeadhunterXamd** [comment] 2019-07-04 07:47
@ansgarbecker Just tried it now, the portable_settings.txt file is (still) preventing the app from launching

**Comment by cpdk** [comment] 2019-07-04 08:45
Can confirm I also get this using version that was updated from Store an hour ago

**Comment by ansgarbecker** [comment] 2019-07-04 11:20
Ok, then my submission from yesterday passed the certification already.

Could you please uninstall and reinstall HeidiSQL from the store, to see if that works?

**Comment by biospirt** [comment] 2019-07-04 12:27
Checked for updates, there was no update.
Uninstalled and installed back again - same thing. 
On error report, same app version as before is shown: 10.2.0.5599

**Comment by Vire5cent** [comment] 2019-07-05 09:19
One of our users had the same issue with the portable_settings file this morning. Reading the comments here, I uninstalled, downloaded a fresh copy of the 64bit version (from the Heidi website) and installed that. When it runs, I comes up with the "Session Manager" dialog. I copied the details from my PC and got the following error; I also exported the settings from my PC, imported those and got the same error.

Error: Library seems unusable. Please select a different one. Internal error 126: The specified module could not be found.

**Comment by ansgarbecker** [comment] 2019-07-05 11:21
@Vire5cent you are using the latest build - be aware these can contain bugs.
The error message is brand new, and caused by non-existing libmysql.dll and/or libmariadb.dll in your HeidiSQL directory. Please check if one of these files exist there. But please post feedback in #677 as that's the right ticket for that library loader.

**Comment by agisp** [comment] 2019-07-05 16:18
I have been having the same issue.  

I just downloaded HeidiSQL_10.2_64_Portable and the program started without any errors.  Then downloaded the installer and HeidiSQL started without errors.

**Comment by Firesphere** [comment] 2019-07-08 01:11
Having the same issue, tried resetting, repairing and reinstalling, but neither worked.

I've submitted a bug report via the crash reporter

**Comment by JboyJW** [comment] 2019-07-08 18:23
> I have been having the same issue.
> I just downloaded HeidiSQL_10.2_64_Portable and the program started without any errors. Then downloaded the installer and HeidiSQL started without errors.

Yes, downloading the installer from heidisql.com worked for me too.  It's just HeidiSQL through the Microsoft Store that is still showing the error.  Tried uninstalling and reinstalling several times to no avail.  Proceeding with the downloaded installer only.

**Comment by ansgarbecker** [comment] 2019-07-08 18:30
I uploaded an update to the Windows Store last Friday. The package is still in the certification process. Normally this takes only one day or two, but with the weekend in mind probably one more day.

**Comment by GrantyT** [comment] 2019-07-12 13:10
Is there any update on this yet? I'm still getting the portable_settings error when trying to launch the Heidi app on my desktop. I want to try and avoid downloading again and having to set up multiple connections from scratch.

**Comment by ansgarbecker** [comment] 2019-07-12 14:09
Today at 12 o'clock I got the message "Your app HeidiSQL submission has been processed." from the Microsoft Store. So, you could watch out if you already get an update for HeidiSQL in the store. If yes, and the problem persists in the new version, I recommend uninstalling and reinstalling. That should remove one offending file from your HeidiSQL directory.

**Comment by GrantyT** [comment] 2019-07-12 14:37
Thanks dude. New release seems to have fixed the issue. It did cause a plink error when trying to connect to a connection, but fixed by downloading plink.exe again. Back in the game :)

**Comment by ansgarbecker** [comment] 2019-07-12 15:58
That's great news!

**Closed by ansgarbecker** 2019-07-12 15:58 UTC
Labels: confirmed, microsoft-store
