### ISSUE TITLE
Error on close application

### ISSUE THREAD

**Issue by kolokoltsov** [HeidiSQL/HeidiSQL#554] opened 2019-02-27 05:24 UTC
1. Close application
2. Error
date/time          : 2019-02-27, 12:19:21, 194ms
computer name      : KMR-HD-220618
user name          : kolokoltsov.av
registered owner   : Пользователь Windows
operating system   : Windows 10 x64 build 17134
system language    : Russian
system up time     : 9 days 2 hours
program up time    : 46 minutes 36 seconds
processors         : 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
physical memory    : 6569/16276 MB (free/total)
free disk space    : (C:) 47,83 GB
display mode       : 1920x1080, 32 bit
process id         : $3180
allocated memory   : 108,74 MB
largest free block : 131025,95 GB
executable         : heidisql.exe
exec. date/time    : 2019-01-26 07:17
version            : 10.1.0.5464
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $9d4a93f6, $e69e3e2a, $e69e3e2a
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 000000000040E235 in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.

main thread ($1300):
0040e235 heidisql.exe System                    TObject.Free
00c4160a heidisql.exe sqlhelp           155  +4 TfrmSQLhelp.treeTopicsFreeNode
00928336 heidisql.exe VirtualTrees    19946 +18 TBaseVirtualTree.DoFreeNode
0093884c heidisql.exe VirtualTrees    26477 +53 TBaseVirtualTree.DeleteNode
0093824c heidisql.exe VirtualTrees    26362 +32 TBaseVirtualTree.DeleteChildren
0093767e heidisql.exe VirtualTrees    26092 +24 TBaseVirtualTree.Clear
00915e07 heidisql.exe VirtualTrees    12024 +22 TBaseVirtualTree.Destroy
00949abc heidisql.exe VirtualTrees    33835  +2 TCustomVirtualStringTree.Destroy
006a4413 heidisql.exe Vcl.Controls              TWinControl.Destroy
006b1aac heidisql.exe Vcl.Controls              TCustomControl.Destroy
006a4413 heidisql.exe Vcl.Controls              TWinControl.Destroy
0083c30e heidisql.exe Vcl.Forms                 TScrollingWinControl.Destroy
0083df31 heidisql.exe Vcl.Forms                 TCustomForm.Destroy
0040e235 heidisql.exe System                    TObject.Free
00558caa heidisql.exe System.Classes            TComponent.DestroyComponents
0055848a heidisql.exe System.Classes            TComponent.Destroy
0069d507 heidisql.exe Vcl.Controls              TControl.Destroy
006a44c6 heidisql.exe Vcl.Controls              TWinControl.Destroy
0083c30e heidisql.exe Vcl.Forms                 TScrollingWinControl.Destroy
0083df31 heidisql.exe Vcl.Forms                 TCustomForm.Destroy
0040e235 heidisql.exe System                    TObject.Free
00558caa heidisql.exe System.Classes            TComponent.DestroyComponents
0083a9c4 heidisql.exe Vcl.Forms                 DoneApplication
00475a80 heidisql.exe System.SysUtils           DoExitProc
00411189 heidisql.exe System                    @Halt0
00dd74ce heidisql.exe heidisql           87 +28 initialization
7ffbdb4b KERNEL32.DLL                           BaseThreadInitThunk
7ffbdc12 ntdll.dll                              RtlUserThreadStart

**Comment by ansgarbecker** [comment] 2019-04-18 11:56
Please update to the latest build of HeidiSQL, and try to repeat whatever you exactly did. And post what you exactly did before closing.

**Comment by ansgarbecker** [comment] 2019-05-01 06:49
Closing due to no feedback.

If you can reproduce that crash, please post some details about where you clicked right before.

**Closed by ansgarbecker** 2019-05-01 06:49 UTC
Labels: bug, needs-info
