### ISSUE TITLE
Erreor when typing lettre D in column name

### ISSUE THREAD

**Issue by Chateau-Darnis** [HeidiSQL/HeidiSQL#661] opened 2019-05-29 15:01 UTC
## Steps to reproduce this issue

1. Select database
2. select a table;
3. Sélect Table description;
4. Add column
5 Type letter D in new column name 

## Current behavior
before typing D
![Annotation 2019-05-29 165811](https://user-images.githubusercontent.com/51167369/58567714-1b089100-8233-11e9-9be3-824c3b2d6a90.jpg)
After typing D
![Annotation 2019-05-29 165845](https://user-images.githubusercontent.com/51167369/58567725-1e038180-8233-11e9-8f75-f40a58f612bb.jpg)

heidi arrive to request editor

## Expected behavior

i want to be able to type letter D in column name

## Environment

* **HeidiSQL version:** 
  10.1.0.5578
same issue with 10.1.0.5577
* **Database system and version:** 
 mariaDB 10.0.38
* **Operating system:** 
Window 10 Pro

**Comment by rentalhost** [comment] 2019-05-29 15:30
I could not reproduces that on **r5578**.

![image](https://user-images.githubusercontent.com/421851/58569935-6f991580-820d-11e9-9845-466529b7da8e.png)

**Comment by ansgarbecker** [comment] 2019-05-30 05:46
Maybe you assigned D as a keyboard shortcut? See Tools > Preferences > Shortcuts.

**Comment by Chateau-Darnis** [comment] 2019-05-31 08:47
Hi David,

my colleague has exactly the same issue.

not shortened with the letter D.

I will try a complete uninstallation and reinstallation

 

Thierry

 

De : David Rodrigues <notifications@github.com> 
Envoyé : mercredi 29 mai 2019 17:30
À : HeidiSQL/HeidiSQL <HeidiSQL@noreply.github.com>
Cc : Chateau-Darnis <tchateau@airetd.fr>; Author <author@noreply.github.com>
Objet : Re: [HeidiSQL/HeidiSQL] Erreor when typing lettre D in column name (#661)

 

I could not reproduces that on r5578.

 <https://user-images.githubusercontent.com/421851/58569935-6f991580-820d-11e9-9845-466529b7da8e.png>

**Comment by Chateau-Darnis** [comment] 2019-05-31 14:23
Hi David

I uninstalled HeidiSQL



I installed HeidiSQL with HeidiSQL_10.1.0.5464_Setup installer

I Add a new Column in a table with the letter D, it’s work fine

I checked for update ans install it
Version 5580 installed



I Add a new Column in a table with the letter D, Bug, Same issue than with r5578 

 

So I uninstalled Heidi and I installed HeidiSQL_10.1.0.5464_Setup installer with no upgrade when it’s done

 

Thierry



 

De : tchateau@airetd.fr <tchateau@airetd.fr> 
Envoyé : vendredi 31 mai 2019 07:10
À : 'HeidiSQL/HeidiSQL' <reply@reply.github.com>
Objet : RE: [HeidiSQL/HeidiSQL] Erreor when typing lettre D in column name (#661)

 

Hi David,

my colleague has exactly the same issue.

not shortened with the letter D.

I will try a complete uninstallation and reinstallation

 

Thierry

 

De : David Rodrigues <notifications@github.com <mailto:notifications@github.com> > 
Envoyé : mercredi 29 mai 2019 17:30
À : HeidiSQL/HeidiSQL <HeidiSQL@noreply.github.com <mailto:HeidiSQL@noreply.github.com> >
Cc : Chateau-Darnis <tchateau@airetd.fr <mailto:tchateau@airetd.fr> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Objet : Re: [HeidiSQL/HeidiSQL] Erreor when typing lettre D in column name (#661)

 

I could not reproduces that on r5578.

 <https://user-images.githubusercontent.com/421851/58569935-6f991580-820d-11e9-9845-466529b7da8e.png>

**Comment by paullupa** [comment] 2019-06-04 18:10
I attempted to re-create the problem and I could not.  
    But for your Windows 10 installation:
What are the Region & Language settings on your computer? 
What are the "Advanced keyboard settings"

Sincerely,
PaulLupa

**Comment by Chateau-Darnis** [comment] 2019-06-05 05:57
Hi

 

Region & Language France/ Français

Input all cases activated

Advanced Keyboard Settings : Utiliser la liste de langue, Emoji panel activated

 

Best regards

 

Thierry Chateau-Darnis

 

De : paullupa <notifications@github.com> 
Envoyé : mardi 4 juin 2019 20:11
À : HeidiSQL/HeidiSQL <HeidiSQL@noreply.github.com>
Cc : Chateau-Darnis <tchateau@airetd.fr>; Author <author@noreply.github.com>
Objet : Re: [HeidiSQL/HeidiSQL] Erreor when typing lettre D in column name (#661)

 

I attempted to re-create the problem and I could not.
But for your Windows 10 installation:
What are the Region & Language settings on your computer?
What are the "Advanced keyboard settings"

Sincerely,
PaulLupa

**Comment by ansgarbecker** [comment] 2020-01-21 11:12
@Chateau-Darnis is this still an issue in the current v10.3 release?
I assume we can close this anyway, as noone else seems to be able to reproduce.

**Closed by ansgarbecker** 2020-01-21 11:12 UTC
Labels: needs-info

**Comment by Chateau-Darnis** [comment] 2020-01-21 13:07
Hi,
happy new year 2020

i confirm that this issue was solved with 10.3 release

Best regards
Thierry

**Comment by ansgarbecker** [comment] 2020-01-21 18:16
Oh that's even better :) Thanks for feedback!
