### ISSUE TITLE
Clear data tab sort order

### ISSUE THREAD

**Issue by snuggeman** [HeidiSQL/HeidiSQL#1868] opened 2023-11-05 16:24 UTC
**Is your feature request related to a problem? Please describe.**
When choosing sort options to a table tab, they are remembered.
If that sort is causing a very long response time, there is no way of (after killing the query) re-entering the tab without the same sort occurring again.

**Describe the solution you'd like**
Add a context menu item for the table; "Clear data tab sort" next to the existing "Clear data tab filter" to remove any saved sort options

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment] 2023-11-05 18:09
I would probably prefer to modify the existing "Clear data tab filter" so it also clears the sorting.

A workaround is to start regedit.exe, and delete the `Sort` value in the relevant table key:
```
HKEY_CURRENT_USER\Software\HeidiSQL\Servers\[name-of-session]\[database]|[table]\ -> Sort
```

**Comment by snuggeman** [comment] 2023-11-07 14:17
I'd prefer a separate menu item, but both works for me!

**Comment by Madjosz** [comment] 2024-01-12 09:10
It's a duplicate of your own issue #1594.

**Closed** 2024-04-29 05:44 UTC
Labels: enhancement, confirmed
