### ISSUE TITLE
Refresh commands are ignored

### ISSUE THREAD

**Issue by RickKukiela** [HeidiSQL/HeidiSQL#1585] opened 2022-05-09 18:20 UTC
**Preconditions**

* HeidiSQL version:  12.0.0.6468
* Database type and version: MariaDB 10.6.5
* OS: Win 11 x64

**Describe the bug**

F5 or Right click table -> refresh does not work

**To Reproduce**

Check the struture in heidi
Make a change to the structure via different software or command line.
Attempt to refresh the table view
The old structure persists / refresh command is ignored.
Restart the program, observe the updated structure.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2023-01-18 19:20
Duplicate of #1628 (was fixed in v12.2)

**Closed by ansgarbecker** 2023-01-18 19:20 UTC
