### ISSUE TITLE
HeidiSQL distorts the definition of a DOUBLE column in MariaDB

### ISSUE THREAD

**Issue by srogatch** [HeidiSQL/HeidiSQL#1055] opened 2020-06-11 17:43 UTC
## Steps to reproduce this issue

Please, see:
https://dba.stackexchange.com/questions/268944/heidisql-rounds-down-double-values-upon-insert-select
https://dba.stackexchange.com/a/268946/144167

1. Create in UI a table as follows:
2. Add a column of type `DOUBLE` but don't specify its dimensions, so that according to MariaDB documentation ( https://mariadb.com/kb/en/double/ ), "If M and D are omitted, values are stored to the limits allowed by the hardware"
3. We get a table with (64-bit) double-precision floating-point numbers in the DB.
4. Now go to "CREATE code" in HeidiSQL UI
5. You will see DOUBLE(22,0) type for this column, meaning 22 digits total and no digits after the decimal point.
6. If you copy-paste the table creation code and run it as a query, you get a column with exactly this: no floating point.

## Current behavior

DB stores DOUBLE column without the limits on the total number of digits and the number of digits after the decimal point. However, HeidiSQL skews the definition for this column to DOUBLE(22,0).

## Expected behavior

I expect that HeidiSQL will display the column in the Create code as just `DOUBLE` rather than `DOUBLE(22,0)` if it's stored as the former in the DB.

## Possible solution

I guess internally you have a pair of integers for each `DOUBLE` column. You can make that pair nullable, so to display just `DOUBLE` instead of `DOUBLE(22,0)` where appropriate.

## Environment

Windows10 64-bit, MariaDB 10.4.13, connected via libmariadb.dll

* **HeidiSQL version:** 
11.0.0.6005 (64 Bit) compiled on 2020-06-11 10:55:50
  
* **Database system and version:** 
MariaDB 10.4.13
  
* **Operating system:** 
Windows 10 64-bit, version 2004

**Comment by ansgarbecker** [comment] 2020-06-13 15:46
I suppose this is a duplicate of #953 
If not please shout.

**Closed by ansgarbecker** 2020-06-13 15:46 UTC
