### ISSUE TITLE
Default value for BIT column is escaped as text in table editor

### ISSUE THREAD

**Issue by Madjosz** [HeidiSQL/HeidiSQL#1037] opened 2020-05-19 17:16 UTC
## Steps to reproduce this issue

1. Create a new column of type `BIT`.
2. Assign a default value (Expression: `0`)
3. Save the table changes.
4. `0` is converted to correct `b'0'`.
5. When rereading the table information `b'0'` is interpreted as string and escaped to `b\'0\'`
6. When making another change to this column, the escaped string is sent as default value, giving
`SQL Error (1067): Invalid default value for 'bitcolumn'`

## Current behavior

HeidiSQL sends the following command to the server:

    ALTER TABLE `table`
        CHANGE COLUMN `bitcolumn` `bitcolumn` BIT(1) NOT NULL DEFAULT 'b\'0\'';

and gets back
`SQL Error (1067): Invalid default value for 'bitcolumn'`.

Also when I then click again on the `Default` column to change the value, the string `b'0'` is inserted (unescaped) in the field "Custom text:" and not an "Expression" anymore

## Expected behavior

The default value is not escaped as a string but treated as a `BIT` literal instead.
Or it is correctly inserted to the "Expression" field.

## Possible solution

Sorry, no suggestions for that other than not treating the default value as "Custom text".

## Environment

* **HeidiSQL version:** 11.0 (official) and 11.0.0.5985 (64-bit) (latest)
* **Library:** libmariadb.dll
* **Database system and version:** MySQL Server 8.0.19
* **Operating system:** Windows 10 Pro 1903

**Comment by ansgarbecker** [comment] 2024-06-21 11:27
Duplicate of #1663

**Closed by ansgarbecker** 2024-06-21 11:27 UTC
