### ISSUE TITLE
Table definition doesn't refresh after altering table

### ISSUE THREAD

**Issue by BrianPittVP** [HeidiSQL/HeidiSQL#1665] opened 2022-09-21 15:21 UTC
**Preconditions**

* HeidiSQL version: 12.0.0.6468 (64 bit)
* Database type and version: MySQL Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64 (Ubuntu)
* OS: Windows 11 pro build 22000.978

**Describe the bug**

If I use a Query tab to alter a table to add a column, remove a column, change keys, etc, the **table:** tab that contains the table definition does not update.  Hitting F5 refreshes the data but not the table definition.  I have not found a way to force this to update except to restart the app
**To Reproduce**

Use a query to alter the table, then view the table definition in the **table:** tab
**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2022-09-28 09:18
I think this is a duplicate of #1628. I just fixed that for the next build, so if you press the refresh button with the table tab opened, the structure should show all modified stuff.

**Closed by ansgarbecker** 2022-09-28 09:18 UTC

**Comment by BrianPittVP** [comment] 2022-09-28 15:04
Indeed, that looks the same.  Thanks!
