### ISSUE TITLE
Can't connect via SSH tunnel if password includes " quote mark

### ISSUE THREAD

**Issue by phinor** [HeidiSQL/HeidiSQL#297] opened 2018-07-03 06:29 UTC
I use a random password generator for server connections. I was am unable to connect to a server using SSH tunnels within HeidiSQL if the password contains a quote mark. I am able to connect to the server using PuTTY and a manual SSH tunnel with the same password.

## Steps to reproduce this issue

1. Step 1; Create a connection to a server using SSH tunnel
2. Step 2; Enter credentials for SSH, including a password that includes a " mark
3. Then I get an error: PLink exited unexpected. Command line was: C:\Program Files (x86)\PuTTY\plink.exe -ssh [user]@[host] -pw "******"[partofpassword]" -P [port] -N -L 3307:127.0.0.1:3306

## Current behavior

The connection attempt is abandoned and no connection is established with the remote server. The part of the password that appears after the quote mark is shown in the error message.

## Expected behavior

The connection is established with the server.

## Possible solution

Escape the password before it is passed to the command line.

## Environment

* **HeidiSQL version:** 
  9.5.0.5280
* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment] 2019-06-29 05:38
Duplicate of #261

**Closed** 2019-06-29 06:15 UTC
Labels: ssh-tunnel
