### ISSUE TITLE
Please don't collapse the treeview after refreshing

### ISSUE THREAD

**Issue by AnvarNazar** [HeidiSQL/HeidiSQL#1238] opened 2020-11-27 13:51 UTC
**Is your feature request related to a problem? Please describe.**
It is very annoying to see the database tree view collapse when I press F5 to refresh.

**Describe the solution you'd like**
I want to see the tree view to not collapse after a refresh.

**Describe alternatives you've considered**
?!

**Additional context**
I am talking about this

![image](https://user-images.githubusercontent.com/22008947/100455912-86ac1280-30e5-11eb-8b52-7a456a2979ad.png)

**Comment by ansgarbecker** [comment] 2020-11-27 14:25
I think this is a duplicate of issue #16

**Closed by ansgarbecker** 2020-11-27 14:25 UTC
