### ISSUE TITLE
Programm hangs or crashes since one of the two nightly builds while using multi column search

### ISSUE THREAD

**Issue by C0kkie** [HeidiSQL/HeidiSQL#1552] opened 2022-03-16 10:33 UTC
**Preconditions**
* HeidiSQL version: 11.3.0.6447
* Database type and version: MariaDB 10.6.5
* OS: Windows 11

**Describe the bug**
If i use the multi-column search the programm stopps working while writing or it crashes

**To Reproduce**
1. Open a table
2. open multi column search
3. type in a few chars
4. it will crash or hang up

**Screenshots or Crash reports**
I sended yesterday already a crash report via email

**Comment by ansgarbecker** [comment] 2022-03-16 18:39
Confirmed. Caused by my commit 3ca092f59ea2d376246192c16fafb4856b27ad1e from last Sunday, where I call `TSynMemo.GetTextLen` in `OnPaintTransient`. Must be an interlocked Windows message `WM_GETTEXTLENGTH` while the component is working on another message. Probably. No clue. I'll go and remove the check for the length, which was intended to prevent lagging on large contents.

**Comment by ansgarbecker** [comment] 2022-03-16 18:41
Related to #670

**Comment by ansgarbecker** [comment] 2022-03-16 18:44
Fixed in the next build.

**Closed by ansgarbecker** 2022-03-16 18:44 UTC
Labels: bug, confirmed

**Comment by webloft** [comment] 2024-08-07 10:45
Regression in 12.8?

Search-Results are now freezing
