### ISSUE TITLE
Wrong syntax for update of bit fields while using MSSQL connection.

### ISSUE THREAD

**Issue by RJPoelstra** [HeidiSQL/HeidiSQL#169] opened 2018-02-28 14:15 UTC
## Steps to reproduce this issue

1. Connect to a MSSQL (version 12) server
2. Make sure you have a table that contains bit field columns and some data
3. Update the value of a row/column.

## Current behavior

1. The displayed data as well as the generated query shows a '0' or '1' for the bit field column
2. An error 102 (incorrect syntax) is returned for the update query

## Expected behavior

1. Queries should use 'true' or 'false' for bit fields, even though '0' or '1' is displayed.

## Possible solution

1. Make sure the query uses 'true' and 'false' when updating a bit field column

## Environment

MS SQL 12.0

* **HeidiSQL version:** 
9.5.0.5196/9.5.0.5255
* **Database system and version:** 
MS SQL 12.0
* **Operating system:** 
Windows 10

**Comment by W-Alsayer** [comment] 2019-04-17 10:08
Mentioned here: https://github.com/HeidiSQL/HeidiSQL/issues/264

**Comment by GPHemsley** [comment] 2020-07-19 04:54
Indeed, this appears to be a duplicate of #264.

**Comment by ansgarbecker** [comment] 2020-07-19 09:07
Thanks for checking!

Duplicate of #264

**Closed by ansgarbecker** 2020-07-19 09:07 UTC
