### ISSUE TITLE
Procedure/Function parameters in decimal types are splitted by comma

### ISSUE THREAD

**Issue by qualishovt** [HeidiSQL/HeidiSQL#546] opened 2019-02-22 10:35 UTC
## Steps to reproduce this issue

1. Step 1;

I have a function which has the following parameters:

    p_wt_cus_id INT (11),
	p_wt_wag_length_m DECIMAL (3, 1),
	p_wt_wag_width_cm INT (11),
	p_wtl_create_doc_dt date

## Current behavior
I get these names of parameters in the **Parameters** tab of the function:

    p_wt_cus_id
	p_wt_wag_length_m
    1),
	p_wt_wag_width_cm
	p_wtl_create_doc_dt

## Expected behavior

    p_wt_cus_id
	p_wt_wag_length_m
	p_wt_wag_width_cm
	p_wtl_create_doc_dt

## Possible solution

The problem is because of HeidiSQL splits parameters by comma even if the type of a parameter is DECIMAL (m, n).

## Environment

Windows 10 Enterprise 64-bit

* **HeidiSQL version: 10.1.0.5484**

**Comment by ansgarbecker** [comment] 2019-04-18 12:04
Can you please update to the latest build and try to reproduce. I cannot reproduce with the latest build and a `DECIMAL(10, 3)` parameter.

**Comment by giovanniperri** [comment] 2022-01-30 07:56
Good morning, I also have the same problem.
I attach the code to create the MySql table 'Quietanzini' and the stored procedure that has parameters that are decimal values (x, y) on which the problem occurs.

When the software is loaded, the stored procedure fields are not well formed and it is impossible to save them.

Thank you for your interest.

[CreateSpQuietanzini.txt](https://github.com/HeidiSQL/HeidiSQL/files/7965502/CreateSpQuietanzini.txt)
.

**Comment by ansgarbecker** [comment] 2024-02-09 07:38
I'm not sure when it was but a quick test tells me this issue is fixed in the current release.

**Closed by ansgarbecker** 2024-02-09 07:38 UTC
Labels: bug, needs-info
