### ISSUE TITLE
Window glitches after "Run SQL file..." while using theme other than "Windows"

### ISSUE THREAD

**Issue by ZaclR** [HeidiSQL/HeidiSQL#499] opened 2019-01-25 09:03 UTC
## Steps to reproduce this issue

1. Install the latest version of HeidiSQL (10.0.0.5460) using either theming option
2. Open HeidiSQL
3. Maximize window
4.  
4.1 (If installed using Windows theme) Click Tools > Preferences > General and change the Style Theme to any theme other than "Windows" (I successfully reproduced it using themes "Windows10" and "Windows10 Dark"
4.2 (If installed using Material Dark theme) Go to step 5
5. Click File > Run SQL file...
6. Select an SQL file to run (I used a DB import file from HeidiSQL's "Export database as SQL" functionality)
7. Let the query script finish
8. Hover UI items and notice how they change colors
9. Move window out of Maximized by dragging the window top bar to make the window disappear/invisible/unclickable

## Current behavior

After carrying out the steps to reproduce the issue, notice how certain items (i.e. query tabs) change colors when hovered over, and the window completely disappears when moved (at least out of maximized mode, haven't tested this in windowed mode). This forces me to hover the windows taskbar and close HeidiSQL using the X button on the window preview there. On hovering the taskbar, the window displays an empty square, indicating the window is not being rendered at all. Relaunching HeidiSQL after closing resolves the issue, as though it never happened (until I run another SQL file).

## Expected behavior

I expect the UI to stay the way it was before running the SQL file, and I expect to be able to move the window without "losing" it.

## Possible solution

Release a bugfix.

## Environment

3 monitor setup, happens on any monitor. They are all 1920x1080 monitors.

* **HeidiSQL version:** 
  
Version 10.0.0.5461 (64 Bit)
EDIT 14.02.19: Also happens in HeidiSQL 10.1.0.5464 (64 Bit)
![heidisql gui bug](https://user-images.githubusercontent.com/16118388/51735659-43675f80-2088-11e9-8e97-0e92cf56f419.png)

* **Operating system:** 
  
Windows 10 Pro (64-bit, version 1803)

**Comment by jny986** [comment] 2019-02-11 02:34
I am getting a similar problem:
OS: Window 10  64 bit 1809
Version: 10.1.0.5464

![2019-02-11_12h55_13](https://user-images.githubusercontent.com/37679074/52543883-168fa800-2dfd-11e9-9177-4450e0b8b249.png)

As you can see in the above image the styling messes up and you can't access any of the menu items at the top of the screen.

This occurs after "Run SQL File" has completed

However for me when I drag the window from the top it returns the menu items and fixes the messed up styling

**Comment by ansgarbecker** [comment] 2019-09-13 16:15
Duplicate of #654

**Closed by ansgarbecker** 2019-09-13 16:15 UTC

**Comment by ZaclR** [comment] 2019-12-12 08:56
Updating to HeidiSQL 10.3.0.5771 fixed this issue! Be sure to select Dark Theme during the install procedure. Everything works now, even after running "Run SQL..."!

Big thanks to Ansgar!
