### ISSUE TITLE
Windows 10 Build 1803 heidiSQL didnot start

### ISSUE THREAD

**Issue by Binapick** [HeidiSQL/HeidiSQL#403] opened 2018-11-20 08:45 UTC
## Steps to reproduce this issue

nothing happens after trying to start the heidiSQL 64Bit app.
The app did not start and generate an event app error

## Current behavior

app did not start
event viewer log see attachment
 
## Environment
Windows 10 Enterprise
Version 1803
Build 17134.345

* **HeidiSQL version:** 
  
9.5.0.5337 64bit

* **Database system and version:** 
  
* **Operating system:** 
  
[error.txt](https://github.com/HeidiSQL/HeidiSQL/files/2598821/error.txt)

**Comment by ansgarbecker** [comment] 2018-11-28 19:43
I got Win 10 v1803 running here and don't get that crash, at least not with the latest build, which is 5349.

![grafik](https://user-images.githubusercontent.com/7986591/49177761-4e369a00-f34e-11e8-875a-f033ed9f43a6.png)

Is the crash reproducible for you, with the latest build?

**Comment by ansgarbecker** [comment] 2019-01-03 16:02
Closing due to no feedback

**Closed by ansgarbecker** 2019-01-03 16:02 UTC
Labels: nightly-required
