### ISSUE TITLE
Trailing zeroes in scientific notation truncated

### ISSUE THREAD

**Issue by chris-heo** [HeidiSQL/HeidiSQL#1793] opened 2023-04-04 18:24 UTC
**Preconditions**

* HeidiSQL version: 12.4.0.6659
* Database type and version: SQLite3
* OS: Windows 10 21H2 Build 19044.2728 (also confirmed with older version)

**Describe the bug**

Trailing zeroes in exponents (scientific notation) are truncated.
This could not be reproduced with the sqlite3 command line.
Could not reproduce this behavior with the MySQL and MariaDB drivers

**To Reproduce**

execute 
SELECT 2e-20 AS notok1, 3e15 AS ok, 2e20 AS notok2

results show: 2,0e-2 3,0e+15 2,0e+2

**Screenshots or Crash reports**

![grafik](https://user-images.githubusercontent.com/73906153/229883512-b51e73c4-adb9-465e-b6eb-76e7503524d5.png)

**Comment by ansgarbecker** [comment] 2023-04-05 08:38
Truncated trailing zeros are caused by the setting "Max decimal zeros for floats". See the [forum](https://www.heidisql.com/forum.php?t=38775) for a discussion about that feature.

![grafik](https://user-images.githubusercontent.com/7986591/230019702-b8cfae0d-6f36-4915-9134-d4aaa0d8cffd.png)

Note this is only a problem on really large numbers (>2^64). `2e10` for example is displayed as normal number without issue ("20000000000.0").

Also, the issue affects MySQL and all other types as well, not only SQLite.

**Comment by chris-heo** [comment] 2023-04-05 20:32
Maybe there is a misunderstanding, it's perfectly fine to have the SCI notation or if trailing zeroes are truncated if they got no added value, though: in my example, with select SELECT 2e-20 AS notok1, the expected number in the result would be 2e-20 and not 2e-2.

To give a better example, I'm coming from electronics where you got quite small values i.e. for capacitors. Storing a value like 100pF would result in 1e-**10**. With the behavior shown above, this value would be displayed as 1e-**1** which is 0.1F (while a displayed value like 1.000000e-**10** would be silly but perfectly fine)


Hope this example clarified the issue better.

**Comment by ansgarbecker** [comment] 2023-04-06 04:54
As said, the issue is that setting "Max decimal zeros for floats" breaks a value of `2.0e-20` to `2.0e-2` (formatted locally with a comma `2,0e-2`). The setting removes the zeros from the exponent "20"=>"2", because it's not aware of numbers in scientific notations. Try it out, set the "Max decimal zeros for floats" to `-1` to disable it.

**Comment by ansgarbecker** [comment] 2023-04-07 08:33
Should be fixed in the next nightly build.

**Closed** 2023-04-07 08:32 UTC
Labels: bug, confirmed
