### ISSUE TITLE
Crash when clicking on a database and then keeping F5 pressed

### ISSUE THREAD

**Issue by niente1** [HeidiSQL/HeidiSQL#258] opened 2018-05-04 08:01 UTC
## Steps to reproduce this issue

1. Click on a database name
2. Keep F5 key pressed to refresh the database list
3. Then I get a crash

## Current behavior

2 crashes (see screenshots)

![screenshot](https://user-images.githubusercontent.com/38974152/39617871-a0d6ebfa-4f81-11e8-8488-bf912bebf03e.jpg)

![screenshot2](https://user-images.githubusercontent.com/38974152/39617973-0aee1496-4f82-11e8-92ff-e7336f487916.jpg)

## Expected behavior

No crash

## Possible solution

None found.

## Environment

Windows Server 2008, Windows 10 (more than a system, all show the same behavior)
I have more than fifty databases

* **HeidiSQL version:** 
  9.5.0.5278 (and all previous versions)

* **Database system and version:** 

* **Operating system:**

**Comment by niente0** [comment] 2020-03-27 09:27
Hello, bug is still here. When it will be fixed? Thank you

**Comment by ansgarbecker** [comment] 2023-01-18 19:23
Duplicate of #1717

**Closed by ansgarbecker** 2023-01-18 19:23 UTC
