### ISSUE TITLE
After connecting to the greenplus database, many databases with the name of temp will be displayed

### ISSUE THREAD

**Issue by ninghongju** [HeidiSQL/HeidiSQL#1002] opened 2020-04-21 05:35 UTC
## Steps to reproduce this issue

1. connecting to the greenplum database;

## Current behavior

![20200421133734](https://user-images.githubusercontent.com/23132816/79829345-6391e580-83d5-11ea-9ac0-60e2ae2b7300.png)

## Possible solution

[SELECT "nspname" FROM "pg_catalog"."pg_namespace" ORDER BY "naspname";]
replace with
[SELECT "nspname" FROM "pg_catalog"."pg_namespace" WHERE "nspacl" is not null ORDER BY "naspname";]
![20200421135548](https://user-images.githubusercontent.com/23132816/79830429-f0d63980-83d7-11ea-9b7d-69bcd149d884.png)

## Environment

* **HeidiSQL version:** 11.0.0.5919
  
* **Database system and version:** PostgreSQL 8.2.15 (Greenplum Database 4.3.8.2 build 1)
  
* **Operating system:**

**Comment by ansgarbecker** [comment] 2020-04-21 15:03
Duplicate of #387

**Closed by ansgarbecker** 2020-04-21 15:03 UTC
Labels: duplicate
