### ISSUE TITLE
BIT data type

### ISSUE THREAD

**Issue by YitzchakK** [HeidiSQL/HeidiSQL#1708] opened 2022-11-18 07:05 UTC
**Preconditions**

* HeidiSQL version:12.2.0.6576
* Database type and version: mySQL
* OS: Win10 64-bit

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by YitzchakK** [comment] 2022-11-18 07:05
I cannot update any BIT data type field. 0 to 1 or 1 to 0 does not work. Error: 1054

**Comment by ansgarbecker** [comment] 2022-11-24 17:39
Duplicate of #1709

Fixed in coming build.

**Closed by ansgarbecker** 2022-11-24 17:39 UTC
