### ISSUE TITLE
enhancement: (add option) restore unsaved queries 

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#140] opened 2018-02-16 12:50 UTC
## Current behavior

* new queries open in a new tab and have a `*` when unsaved
* on closing HeidiSQL user is asked whether to save those queries
* unsaved queries are lost when restarting HeidiSQL next time

## Expected behavior

* Option for the user to restore unsaved queries next time
* Notepad++ has it by default, that unsaved tabs are automatically saved and restored
* also browser have option to restore tabs on next restart
* if HeidiSQL crashes it won't lose those user queries

## Possible solution

* HeidiSQL could automatically save it's query tabs in `%appdata%\HeidiSQL\unsaved Queries`
* if this in enabled HeidiSQL won't ask anymore to save them.

## Environment

* **HeidiSQL version:** 
  9.5.0.5248
* **Operating system:** 
 Windows 10 1709

## Comment
I use those queries for debugging. They are not relevant enough to save them for ever but I'd like them to be there for 1-2 weeks until they aren't relevant anymore.

**Comment by penCsharpener** [comment] 2018-02-16 12:57
additionally it would be nice to be useful to hit `F2` on a query tab to rename it in place (without save file dialog) because Query 1, Query 2, Query 3, Query 4 is hard to tell apart. 

Thanks for the best SQL-Browser on Windows!

**Comment by jcguevara** [comment] 2018-02-21 10:27
I think the problem with multiple instances could be partially solved if the unsaved tabs are saved in subfolders by connection name like: '%appdata%HeidiSQL\unsaved Queries\[CONNECTION_NAME]_query_*.sql' in my case I'm used to have several instances  opened but connected to a different DBs.

**Comment by carlosfrutos** [comment] 2018-04-10 10:54
Please, remember this enhancement was requested for the first time in 2012:

[https://sourceforge.net/p/heidisql/tickets/2991/](https://sourceforge.net/p/heidisql/tickets/2991/)

A couple of issue-tracker migrations since then...

Thank you for your efforts, guys. I really like HeidiSQL, but I'm scared of using it sometimes because it does not backup your work.

Kind regards

**Comment by sloboy** [comment] 2018-08-25 00:01
MySql workbench even reopens tabs that were saved but visible when the program is closed and reopened, not just unsaved queries.  This is helpful when you are working on a project that needs input from several queries to figure out, but spans multiple days because of phb interruptions :)

**Comment by kiltannen** [comment] 2018-10-30 09:32
I also would like to see this.

I use Heidi for any MySQL queries I do, and this would be a very nice enhancement.

**Comment by johnnyPescarul** [comment] 2019-01-10 19:47
This is a critical feature. I love Heidi and appreciate all great effort, but I would prioritize this over other enhancements.

**Comment by Miktarbad** [comment] 2019-01-24 13:31
This feature would greatly increase my workflow, since i do not have the time to save every query - but might need them later.

**Comment by phiter** [comment] 2019-02-02 13:09
Been looking for this as well. My co-worker told me he loves Heidi but this is a feature that is missing and would help him a lot. Hope it gets implemented soon.

**Comment by styler2go** [comment] 2019-02-15 08:14
I am also looking forward for this feature. Will improve my experience a lot.

**Comment by mfaustusi** [comment] 2019-02-26 18:43
This would also save those who get frequent crashing of HeidiSQL and lose large queries that they were working on. Often when a crash occurs an exception dialog will popup and sometimes clicking on "continue" will actually close the program, or "continue" won't be available. In either case, trying to copy the query out of the tab before closing the exception box is not possible and unsaved queries are lost. Notepad++ also has this feature and it's saved me countless times.

**Comment by penCsharpener** [comment] 2019-02-27 09:05
Hi @ansgarbecker, since quite a few people would find this useful can you give us an idea whether you have already been working on this or when we can expect this in a nightly version? Of course you have a bunch of other things in your 10.2 milestone. This is not to rush anything, just informational.

**Comment by ansgarbecker** [comment] 2019-02-28 07:09
This is one of the most and longest wish from many users, so it will be one of the next feature I am going to implement.

**Comment by phiter** [comment] 2019-02-28 12:36
Fantastic news, thanks @ansgarbecker !

**Comment by ansgarbecker** [comment] 2019-03-10 07:32
Notepad++ has this restore-feature, and its preference dialog looks like this:
![grafik](https://user-images.githubusercontent.com/7986591/54081872-cda01600-430c-11e9-8126-540d71413e16.png)
While HeidiSQL only has this option:
![grafik](https://user-images.githubusercontent.com/7986591/54081884-0213d200-430d-11e9-8ae2-550386bd96e7.png)

So, the approach in Notepad++ is missing the option to ignore unsaved text in a tab without even auto-saving it.

In order not to break this old feature of HeidiSQL, I should add a new "Files" tab to the preferences dialog, containing that old "_Prompt to save_" checkbox. Additionally, we will have a new checkbox like in Notepad++, labelled "_Automatically backup unsaved files_". This option applies to tabs _left open_ when exiting HeidiSQL, not to _closed_ tabs, in contrast to the _Prompt_ option.

And finally I think there is no need to even customize the interval for saving these backups, like in Notepad++. Instead, Heidi should save these temporary files every 10 seconds, and only if content was changed.

By the way, is it a good idea to leave out files bigger than let's say 10MB? I'm quite sure such bigger files are normally automatically generated. And it may introduce a performance issue if HeidiSQL e.g. has to save a 5GB file every 10 seconds.

**Comment by penCsharpener** [comment] 2019-03-10 07:43
10MB sound way touch I find. If I export data as SQL and paste it in a tab, then I don't want that saved. 
10kb or 100kb would already be very big queries. 
What about putting the file size as another option if you already create a new settings tab? My limit would likely be around 10kb.

**Comment by phiter** [comment] 2019-03-11 11:00
Yeah I think 10MB is huge for a file. If you want to go full customization, this can be a configurable field where you set max size in kb.

**Comment by mfaustusi** [comment] 2019-03-11 17:49
To ensure this feature is done right there should be some forethought about being able to recover from a corrupt cache that prevents HeidiSQL from loading properly, such as a command line option to skip loading background-saved queries, or on launch after a crash give the option to skip loading background saved queries that may be preventing it from starting up.

Also, in regards to file size I would assume it would be fairly trivial to compress the queries before saving to disk since SQL text is highly compressible. Very large queries likely have a lot of repeating text and could be reduced in size drastically with most compression algorithms.

**Comment by pipanni** [comment] 2019-03-12 13:36
I would like this feature very much. I would also like some sushi.

**Comment by dig314** [comment] 2019-03-12 18:26
I would appreciate this feature.

**Comment by ansgarbecker** [comment] 2019-04-07 11:35
I think I have most parts of this new feature ready to use. Some translation strings are missing yet, and probably not done enough testing yet. For all who want to test the new auto-restore feature:

* update to the new nightly build
* watch out for unsaved query tabs, either after loading a file from harddisk or without a file in the back
* if you want to know more exactly what's going on:
  * activate Preferences > Logging > "Debug" messages
  * watch the auto-created directory `C:\Users\<yourUsername>\AppData\Roaming\HeidiSQL\Backups\`
  * watch the new setup file `C:\Users\<yourUsername>\AppData\Roaming\HeidiSQL\tabs.ini`

The auto-restore feature is activated by default, and can be disabled in Preferences > Files > "Reopen previously used SQL files..."

**Comment by ansgarbecker** [comment] 2019-04-08 18:58
I think the current implementation is not yet safe against running multiple instances... Please be aware of that if you already use this feature.

**Comment by penCsharpener** [comment] 2019-04-08 19:01
nothing important should remain unsaved anyway. It can't be worse than before the feature implementation when all the unsaved queries were gone by default.

**Comment by okneloper** [comment] 2019-04-08 19:51
Not really. Previously it was warning about unsaved queries, and wouldn't close until you save or discard them. 
If atm it's closing without prompt and overwriting other queries, that's unsafe indeed. Thanks for flagging @ansgarbecker

**Comment by pantantrollo** [comment] 2019-04-10 18:58
> * watch the auto-created directory `C:\Users\<yourUsername>\AppData\Roaming\HeidiSQL\Backups\`
> * watch the new setup file `C:\Users\<yourUsername>\AppData\Roaming\HeidiSQL\tabs.ini`

Will it also be implemented for the portable version?

**Comment by ansgarbecker** [comment] 2019-04-11 05:32
The portable is the same executable as the normal version, it just gets flagged via the portable.lock file. But I suppose your question was meant for the directories, which are not "quite portable". Well I did not see the need for it yet, but it may make sense. In the portable version, the tabs.ini could live in the directory with heidisql.exe, and the "Backups" directory could be auto-created as a subfolder of it. Does that make sense?

**Comment by pantantrollo** [comment] 2019-04-11 10:46
Right, something like that.

The "tabs.ini" that was in the same place as the executable heidiSql.exe (as is its configuration), for any of the versions, portable and installable.

The directory "backups" or that its location could be configured (either via config gui or editing the config file) or failing that, for example if it detects the "portable.lock" or 2portable_settings.txt" file, then create the directirios "backups" in that same place, otherwise, in \%appdata%\heidisql (for example)

Thx

**Comment by ansgarbecker** [comment] 2019-04-12 12:15
done:
[x] prevent file locks when multiple instances access tabs.ini
[x] store tabs.ini and backups folder locally in portable mode

There is still the chance one instance overwrites a backup file from another running instance. So I thought I could add something like this:
* store current process id to each section in tabs.ini
* when restoring tabs, check if the process id is running
  * if it's still running: don't restore that tab
  * if it's not running: replace it with the current process id and restore tab

Read: the first instance restores tabs from the previous one. Second and later instances do not restore tabs, but can add new tabs. This way, no tab content gets lost. If you exit 3 instances with let's say 2 tabs, then the next started instance should restore 6 tabs. Or, if 1 of the 3 instances is still running, then 4 tabs get restored.

**Comment by 3vcloud** [comment] 2019-04-12 15:21
This only seems to restore the first tab for me atm

**Comment by ansgarbecker** [comment] 2019-04-13 06:50
I just tested with a blank setup and the latest build. I can reproduce that if I am very quickly closing HeidSQL, before the 10 seconds timer for storing the tab setup has reached its first end. So I think the call of `MainForm.StoreTabs` when closing HeidiSQL is not fired for some reason.

**Comment by ansgarbecker** [comment] 2019-04-13 08:58
Next nightly build should work stable with multiple HeidiSQL instances, each of them managing its own tab setup, writing to the same tabs.ini file. Tabs get restored if no other running instance is using them.

Any more issues here? Please report if you find one.

**Comment by okneloper** [comment] 2019-04-13 20:40
What an awesome improvement to my day-to-day work! Thanks for taking the time to implement this!

**Comment by ansgarbecker** [comment] 2019-04-16 18:50
I am closing this issue now, as there are no complaints for some days, and I can also find nothing to change. Please shout if you find more issues.

**Comment by igitur** [comment] 2019-04-30 09:03
I think this was a great improvement, but I think the norm with other applications (e.g. Notepad++) is that when the user manually closes a Window it always asks him for confirmation to save the contents or not. Only when the program is closed (e.g. when it is upgrading to a new version) does the auto-backup apply.

**Comment by 3vcloud** [comment] 2019-04-30 09:10
I agree with @igitur , this is a bug to do with this change. Tabs still need to prompt if the user closes them within the application

**Comment by ansgarbecker** [comment] 2019-04-30 09:28
Yes, when you close a tab, it should ask you. But this is the case, at least if you did not disable this prompt:

![grafik](https://user-images.githubusercontent.com/7986591/56952399-909d1680-6b3a-11e9-8e33-7330d9cc410b.png)

Is this not intuitive in some way? Or maybe because the user tends to disable the option? 

![grafik](https://user-images.githubusercontent.com/7986591/56952587-ed003600-6b3a-11e9-90e5-77646e18810c.png)

**Comment by igitur** [comment] 2019-04-30 09:31
Ah, then I misunderstood that question. I assumed it meant specifically to "Keep asking this question" when closing the files in bulk (e.g. when closing/upgrading the application).

**Comment by 3vcloud** [comment] 2019-04-30 09:33
I have that box ticked, and my application doesn't prompt me when I close a tab. I may have unticked `Keep asking this question` in the past, but that should just update `Prompt to save modified files on tab close`, yes?

**Comment by ansgarbecker** [comment] 2019-06-03 14:28
Still an issue, described in [the forum](https://www.heidisql.com/forum.php?t=27074): physically existing files loaded into a tab are restored even when the user closed them in the previous session.

**Comment by ansgarbecker** [comment] 2019-06-03 18:34
Just fixed that for the next build. Closed tabs with manually loaded files should no longer be restored in the next session.

**Closed by ansgarbecker** 2019-06-03 18:34 UTC
Labels: enhancement

**Comment by ilpssun** [comment] 2019-06-04 05:46
Can confirm the fix in build 5585.

**Comment by WesleyM77** [comment] 2019-06-24 18:50
Should bound parameters also be restored?

**Comment by ansgarbecker** [comment] 2019-06-24 19:47
They are not currently, but I guess they should be, right? But please file another issue for solving that.

**Comment by ansgarbecker** [comment] 2022-08-17 08:48
Note that since v12.1, the auto-created backup file of a user-closed tab is now deleted to the recycle bin. Previously, they were just deleted without any possibility to restore. So, even when you closed a tab, by accident or not, you may restore its content.

**Comment by DRSDavidSoft** [comment] 2023-04-02 20:05
@ansgarbecker You just saved me from a heart attack! I had some important information in a few queries, and the tabs were closed. I'm so relieved that I found the content in the recycle bin! 😄
