### ISSUE TITLE
Update or Insert row with BIT type

### ISSUE THREAD

**Issue by yucikala** [HeidiSQL/HeidiSQL#1707] opened 2022-11-17 20:10 UTC
**Preconditions**
* HeidiSQL version:  12.2.6576 
* Database type and version: 10.5.8-MariaDB-log
* OS: windows 10

**Describe the bug**
I have a table with BIT column. When I try to insert data, It is not possible. Error: /* SQL chyba (1054): Unknown column 'b0' in 'field list' */
It generate SQL:
INSERT INTO ``aktuality` (`datum`, `aktualita`,  `zvyraznit`) VALUES ('2020-12-21', 'test uložení', b0);

But corrent is:
INSERT INTO ``aktuality` (`datum`, `aktualita`,  `zvyraznit`) VALUES ('2020-12-21', 'test uložení', 0);

**To Reproduce**
see Description. Open table, Click to Data. Then click Duplicate row witout keys. After try to insert you can see an error

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2022-11-24 17:38
Duplicate of #1709

Fixed in coming build.

**Closed by ansgarbecker** 2022-11-24 17:39 UTC
