### ISSUE TITLE
When enter pressed in edit value in "data" tab.

### ISSUE THREAD

**Issue by lukyrys** [HeidiSQL/HeidiSQL#1518] opened 2022-01-17 00:30 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6371
* Database type and version: MySQL 
* OS: Windows 11 arm64 (build 22000.434) (Virtualized in Parallels 17)

**Describe the bug**

When pressed "Enter" key in edit column mode in Data tab. Usually immediately after startup or after a long period of inactivity, when I click the mouse the line is saved and then enter works 
Sometime HeidiSQL cause unexcepted crash without notice about error.
`/* #39: Access violation at address 00000000 in module 'heidisql.exe'. Read of address 00000000 Message CharCode:13 Msg:256 */`

**Screenshots or Crash reports**

`/* #39: Access violation at address 00000000 in module 'heidisql.exe'. Read of address 00000000 Message CharCode:13 Msg:256 */`

![obrazek](https://user-images.githubusercontent.com/2318346/149684245-a4f6e676-ffff-41f1-a547-f35677ca9714.png)
![obrazek](https://user-images.githubusercontent.com/2318346/149684265-9018a966-9329-489f-9844-efe5dbf4091c.png)

**Comment by ansgarbecker** [comment] 2022-04-15 07:15
Duplicate of #1353

**Closed by ansgarbecker** 2022-04-15 07:15 UTC
