### ISSUE TITLE
Query editor produces crash (List index out of bounds)

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#780] opened 2019-10-25 11:28 UTC
## Steps to reproduce this issue

1. Clicking at the very first column of the first row of saved query produces crash;
2. I was trying to align manually the SQL source code, because I saw that the first column of first row is a bit indented (see the attached screenshot);
3. The query was opened at the same time in 2 instances of Heidi.

![heidi-2019-10-25_142027](https://user-images.githubusercontent.com/8297417/67568024-bf83f600-f733-11e9-9af2-bbf12cf491e2.png)
[heidi-bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3771817/heidi-bugreport.txt)

## Environment

* **HeidiSQL version:** 
 10.2.0.5721

* **Database system and version:** 
MySQL 5.7.21

* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment] 2019-10-25 15:16
Duplicate of already fixed #776

**Comment by ansgarbecker** [comment] 2019-10-25 15:18
Sorry, this is different - not a duplicate

**Comment by ansgarbecker** [comment] 2019-10-25 15:21
Is that reproducible for you? I don't get that exception, no matter if I use a saved query or a new one, double-click, right-click or left-click.

**Comment by budiony** [comment] 2019-10-25 16:29
It happens every time when I open saves query, this did not happen view versions back. Every loaded query in the editor begins with first line a bit indented on right, as you see from screen shot, when I position the cursor at exactly the first character and pressing "Delete" key, the crash happens.

If you prefer I can make a video and post it?

**Comment by ansgarbecker** [comment] 2019-10-26 06:22
I'm nearly sure the issue was my code change in 10f61069c82975016c3a4ed76191925aaa4e1435 (build 5716), which I fixed 2 days later in deab98736ed591b1aeb6a229de1ddf06e9f43a42 (build 5717). I suppose your file was saved with build 5716, in UTF8 encoding _with_ a 3 Byte BOM at the very beginning, and now HeidiSQL loads that file with disregard to that BOM. Clicking into that BOM area with control characters may cause such an issue, which I cannot because my files don't have a BOM.

Please try to remove the BOM manually, by copying the text without the invisible characters into a new file. And please report back if that helped.

**Comment by budiony** [comment] 2019-10-26 10:10
Yes, you are absolutely right. Coping file contents from query editor to notepad and then re-save the file did the trick.

**Comment by ansgarbecker** [comment] 2019-10-27 06:56
Thanks for your feedback.

**Closed by ansgarbecker** 2019-10-27 06:56 UTC
Labels: bug, needs-info
