### ISSUE TITLE
PostgreSQL - HeidiSQL User Manager error

### ISSUE THREAD

**Issue by Raegedoc** [HeidiSQL/HeidiSQL#1654] opened 2022-08-30 00:27 UTC
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: PostgreSQL 12.12 or 14.5 or else
* OS: Windows 10

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by Virgil-Zu** [comment] 2022-12-02 06:09
Preconditions

HeidiSQL version: 12.2.0.6576
Database type and version: PostgreSQL 15.0
OS: Windows 10

Describe the bug
ERROR: syntax error at or near "FLUSH"LINE 1: FLUSH PRIVILEGES

**Comment by ansgarbecker** [comment] 2022-12-16 21:01
Duplicate of #80

**Closed by ansgarbecker** 2022-12-16 21:01 UTC
