### ISSUE TITLE
Follow foreign keys

### ISSUE THREAD

**Issue by ferenczy** [HeidiSQL/HeidiSQL#1328] opened 2021-03-03 16:33 UTC
**Is your feature request related to a problem? Please describe.**
On bigger and more complex databases with a lot of data, it's sometimes quite complicated to effectively browse the data from various tables linked by foreign keys.

**Describe the solution you'd like**
It would be great to have a possibility to "follow" foreign keys, so it's easier to browse complex databases. Let me explain.

Let's have two tables:

    Table A:
        column ID (int)

    Table B:
       column ID (int)
       column A_ID (foreign key to A.ID)

When I would view data of the table `B` and executed (by a double click/keyboard shortcut/etc.) the "follow foreign key" feature on a cell `A_ID` with value, for example, 3, it would switch me to the data view of the table `A` with filter `SELECT * FROM A WHERE ID = 3`, or with all data shown, but with the row with `ID = 3` selected.

I hope it's understandable what I mean.

**Describe alternatives you've considered**
Alternative is to remember IDs of foreign keys, navigate to data views of other tables and search/filter rows with those IDs or to write ad hoc queries with joined tables which would return data I'm looking for. But that's sometimes too much work/overhead.

**Comment by ansgarbecker** [comment] 2021-03-03 16:38
Duplicate of #156 ?

**Comment by ferenczy** [comment] 2021-03-04 11:27
Yep, that's exactly what I meant! Sorry for missing it. You can mark this issue as a duplicate.

**Closed** 2021-03-04 11:44 UTC
