### ISSUE TITLE
Unable to work with HeidiSQL, freezes even when open tables

### ISSUE THREAD

**Issue by acuna-public** [HeidiSQL/HeidiSQL#1519] opened 2022-01-18 19:14 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6391
* Database type and version: MySQL 6.1
* OS: Windows 7 x64

**Describe the bug**

Compelled to dublicate this issue because I have no answers about 2 weeks but I needs to use HeidiSQL. Having a huge exceptions even while opens tables. Sometimes having a message "This handle is already connected. Use a separate handle for each connection" on MySQL and "Can't connect twice. Already connected" with MariaDB. I have only one connection to the DB from my desktop and working script with cron which using this DB too, so it's unable to work with it in HeidiSQL.

**To Reproduce**

Every action

**Screenshots or Crash reports**

I have saved about ten of it, but seems most of it is repeated so here is three of them:

```
date/time          : 2022-01-05, 20:28:33, 151ms
computer name      : ACUNAPC
user name          : Acuna <admin>
registered owner   : Acuna
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Russian
system up time     : 1 day 21 hours
program up time    : 1 day 21 hours
processors         : 4x Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz
physical memory    : 3240/8191 MB (free/total)
free disk space    : (C:) 12,48 GB
display mode       : 1280x1024, 32 bit
process id         : $26c0
allocated memory   : 122,39 MB
largest free block : 8181,02 GB
executable         : heidisql.exe
exec. date/time    : 2022-01-01 06:01
version            : 11.3.0.6389
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.1
callstack crc      : $a3e67eac, $c0c3dd08, $c0c3dd08
exception number   : 9
exception class    : EAccessViolation
exception message  : Access violation at address 000007FEF6C87A74 in module 'libmariadb.dll'. Read of address 0000000000000374.

main thread ($2480):
7fef6c87 libmariadb.dll
7fef6c83 libmariadb.dll                         mysql_stat
00cdec71 heidisql.exe   dbconnection   7142  +4 TMySQLConnection.ConnectionInfo
011332c3 heidisql.exe   Main           1482 +19 TMainForm.StatusBarMouseMove
006e0259 heidisql.exe   Vcl.Controls            TControl.MouseMove
006e0334 heidisql.exe   Vcl.Controls            TControl.WMMouseMove
0040f0a2 heidisql.exe   System                  TObject.Dispatch
006df68d heidisql.exe   Vcl.Controls            TControl.WndProc
006e68eb heidisql.exe   Vcl.Controls            TWinControl.WndProc
006e5a6a heidisql.exe   Vcl.Controls            TWinControl.MainWndProc
0056bbf3 heidisql.exe   System.Classes          StdWndProc
7754956d USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe   Vcl.Forms               TApplication.ProcessMessage
0089e663 heidisql.exe   Vcl.Forms               TApplication.HandleMessage
0089eab1 heidisql.exe   Vcl.Forms               TApplication.Run
01186f18 heidisql.exe   heidisql        105 +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart
```

```
date/time          : 2022-01-06, 01:50:54, 805ms
computer name      : ACUNAPC
user name          : Acuna <admin>
registered owner   : Acuna
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Russian
system up time     : 2 days 2 hours
program up time    : 1 hour 12 minutes
processors         : 4x Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz
physical memory    : 3071/8191 MB (free/total)
free disk space    : (C:) 12,35 GB
display mode       : 1280x1024, 32 bit
process id         : $2c34
allocated memory   : 97,96 MB
largest free block : 8180,96 GB
executable         : heidisql.exe
exec. date/time    : 2022-01-05 23:38
version            : 11.3.0.6391
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.1
callstack crc      : $f31ee59a, $0bc9c854, $e09dca92
exception number   : 5
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000411D9C in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.

main thread ($28e8):
00411d9c heidisql.exe System                    @UStrAddRef
00ccac21 heidisql.exe dbconnection    5363   +0 TDBConnection.IdentifierEquals
00cec63a heidisql.exe dbconnection    9664   +4 TDBObject.IsSameAs
0114e1f5 heidisql.exe Main            5750  +18 TMainForm.DataGridBeforePaint
00980b7d heidisql.exe VirtualTrees   19613   +2 TBaseVirtualTree.DoBeforePaint
0099ab5b heidisql.exe VirtualTrees   30586   +5 TBaseVirtualTree.PaintTree
0098bbc7 heidisql.exe VirtualTrees   24023  +23 TBaseVirtualTree.Paint
006f09d6 heidisql.exe Vcl.Controls              TCustomControl.PaintWindow
006e6b83 heidisql.exe Vcl.Controls              TWinControl.PaintHandler
006e7aef heidisql.exe Vcl.Controls              TWinControl.WMPaint
006f0968 heidisql.exe Vcl.Controls              TCustomControl.WMPaint
0097c92d heidisql.exe VirtualTrees   17759   +8 TBaseVirtualTree.WMPaint
0040f0a2 heidisql.exe System                    TObject.Dispatch
006df68d heidisql.exe Vcl.Controls              TControl.WndProc
006e68eb heidisql.exe Vcl.Controls              TWinControl.WndProc
00990aa3 heidisql.exe VirtualTrees   25876  +32 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
0096516e heidisql.exe VirtualTrees    7883   +8 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
00965192 heidisql.exe VirtualTrees    7886  +11 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                 TApplication.Run
01186f08 heidisql.exe heidisql         105  +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart

main thread ($28e8), inner exception level 1:
>> EAccessViolation, Access violation at address 0000000000411D9C in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
00411d9c heidisql.exe System       @UStrAddRef
7feff722 GDI32.dll                 BitBlt
77543857 USER32.dll                CallWindowProcW
006e6a82 heidisql.exe Vcl.Controls TWinControl.DefaultHandler
00805448 heidisql.exe Vcl.Themes   ThemeControl

main thread ($28e8), inner exception level 2:
>> EAccessViolation, Access violation at address 0000000000411D9C in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
00411d9c heidisql.exe System                    @UStrAddRef
00ccac21 heidisql.exe dbconnection    5363   +0 TDBConnection.IdentifierEquals
00cec63a heidisql.exe dbconnection    9664   +4 TDBObject.IsSameAs
0114e1f5 heidisql.exe Main            5750  +18 TMainForm.DataGridBeforePaint
00980b7d heidisql.exe VirtualTrees   19613   +2 TBaseVirtualTree.DoBeforePaint
0099ab5b heidisql.exe VirtualTrees   30586   +5 TBaseVirtualTree.PaintTree
0098bbc7 heidisql.exe VirtualTrees   24023  +23 TBaseVirtualTree.Paint
006f09d6 heidisql.exe Vcl.Controls              TCustomControl.PaintWindow
006e6b83 heidisql.exe Vcl.Controls              TWinControl.PaintHandler
006e7aef heidisql.exe Vcl.Controls              TWinControl.WMPaint
006f0968 heidisql.exe Vcl.Controls              TCustomControl.WMPaint
0097c92d heidisql.exe VirtualTrees   17759   +8 TBaseVirtualTree.WMPaint
0040f0a2 heidisql.exe System                    TObject.Dispatch
006df68d heidisql.exe Vcl.Controls              TControl.WndProc
006e68eb heidisql.exe Vcl.Controls              TWinControl.WndProc
00990aa3 heidisql.exe VirtualTrees   25876  +32 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
0096516e heidisql.exe VirtualTrees    7883   +8 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
00965192 heidisql.exe VirtualTrees    7886  +11 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                 TApplication.Run
01186f08 heidisql.exe heidisql         105  +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart

main thread ($28e8), inner exception level 3:
>> EAccessViolation, Access violation at address 0000000000411D9C in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
00411d9c heidisql.exe System                    @UStrAddRef
00ccac21 heidisql.exe dbconnection    5363   +0 TDBConnection.IdentifierEquals
00cec63a heidisql.exe dbconnection    9664   +4 TDBObject.IsSameAs
0114e1f5 heidisql.exe Main            5750  +18 TMainForm.DataGridBeforePaint
00980b7d heidisql.exe VirtualTrees   19613   +2 TBaseVirtualTree.DoBeforePaint
0099ab5b heidisql.exe VirtualTrees   30586   +5 TBaseVirtualTree.PaintTree
0098bbc7 heidisql.exe VirtualTrees   24023  +23 TBaseVirtualTree.Paint
006f09d6 heidisql.exe Vcl.Controls              TCustomControl.PaintWindow
006e6b83 heidisql.exe Vcl.Controls              TWinControl.PaintHandler
006e7aef heidisql.exe Vcl.Controls              TWinControl.WMPaint
006f0968 heidisql.exe Vcl.Controls              TCustomControl.WMPaint
0097c92d heidisql.exe VirtualTrees   17759   +8 TBaseVirtualTree.WMPaint
0040f0a2 heidisql.exe System                    TObject.Dispatch
006df68d heidisql.exe Vcl.Controls              TControl.WndProc
006e68eb heidisql.exe Vcl.Controls              TWinControl.WndProc
00990aa3 heidisql.exe VirtualTrees   25876  +32 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
0096516e heidisql.exe VirtualTrees    7883   +8 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
00965192 heidisql.exe VirtualTrees    7886  +11 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                 TApplication.Run
01186f08 heidisql.exe heidisql         105  +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart

main thread ($28e8), inner exception level 4:
>> EAccessViolation, Access violation at address 0000000000411D9C in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
00411d9c heidisql.exe System                    @UStrAddRef
00ccac21 heidisql.exe dbconnection    5363   +0 TDBConnection.IdentifierEquals
00cec63a heidisql.exe dbconnection    9664   +4 TDBObject.IsSameAs
0114e1f5 heidisql.exe Main            5750  +18 TMainForm.DataGridBeforePaint
00980b7d heidisql.exe VirtualTrees   19613   +2 TBaseVirtualTree.DoBeforePaint
0099ab5b heidisql.exe VirtualTrees   30586   +5 TBaseVirtualTree.PaintTree
0098bbc7 heidisql.exe VirtualTrees   24023  +23 TBaseVirtualTree.Paint
006f09d6 heidisql.exe Vcl.Controls              TCustomControl.PaintWindow
006e6b83 heidisql.exe Vcl.Controls              TWinControl.PaintHandler
006e7aef heidisql.exe Vcl.Controls              TWinControl.WMPaint
006f0968 heidisql.exe Vcl.Controls              TCustomControl.WMPaint
0097c92d heidisql.exe VirtualTrees   17759   +8 TBaseVirtualTree.WMPaint
0040f0a2 heidisql.exe System                    TObject.Dispatch
006df68d heidisql.exe Vcl.Controls              TControl.WndProc
006e68eb heidisql.exe Vcl.Controls              TWinControl.WndProc
00990aa3 heidisql.exe VirtualTrees   25876  +32 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
0096516e heidisql.exe VirtualTrees    7883   +8 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
0096d740 heidisql.exe VirtualTrees   11493  +42 TVTHeader.Invalidate
00965192 heidisql.exe VirtualTrees    7886  +11 TVirtualTreeColumns.GetNewIndex
0096558d heidisql.exe VirtualTrees    8004   +1 TVirtualTreeColumns.AdjustHoverColumn
0096c078 heidisql.exe VirtualTrees   10879 +303 TVTHeader.HandleMessage
00990a47 heidisql.exe VirtualTrees   25870  +26 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
004f11f0 heidisql.exe madExcept                 HandleException
004fd551 heidisql.exe madExcept                 InterceptAHandleExcept
006e5a8e heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7769b4eb ntdll.dll                              KiUserCallbackDispatcher
77546b27 USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                 TApplication.Run
01186f08 heidisql.exe heidisql         105  +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart
```

```
date/time          : 2022-01-06, 03:50:06, 36ms
computer name      : ACUNAPC
user name          : Acuna <admin>
registered owner   : Acuna
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Russian
system up time     : 2 days 4 hours
program up time    : 2 hours 44 minutes
processors         : 4x Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz
physical memory    : 2578/8191 MB (free/total)
free disk space    : (C:) 12,31 GB
display mode       : 1280x1024, 32 bit
process id         : $3014
allocated memory   : 125,29 MB
largest free block : 8180,96 GB
executable         : heidisql.exe
exec. date/time    : 2022-01-05 23:38
version            : 11.3.0.6391
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.1
callstack crc      : $275db886, $6b5e553f, $6b5e553f
exception number   : 30
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000CAB81E in module 'heidisql.exe'. Read of address 0000000000000090.

main thread ($3688):
00cab81e heidisql.exe dbconnection    1140  +66 TPlink.Connect
00cb26c9 heidisql.exe dbconnection    2280  +49 TMySQLConnection.SetActive
00cbb78b heidisql.exe dbconnection    3255  +15 TMySQLConnection.Ping
00cc8890 heidisql.exe dbconnection    5114   +3 TMySQLConnection.GetTableEngines
00f62099 heidisql.exe table_editor     290  +17 TfrmTableEditor.Init
0116dd10 heidisql.exe Main           11341  +17 TMainForm.PlaceObjectEditor
01162ed3 heidisql.exe Main            9274  +69 TMainForm.DBtreeFocusChanged
009821a4 heidisql.exe VirtualTrees   20141   +2 TBaseVirtualTree.DoFocusChange
009893ab heidisql.exe VirtualTrees   22907 +274 TBaseVirtualTree.HandleMouseDown
0097c005 heidisql.exe VirtualTrees   17531   +6 TBaseVirtualTree.WMLButtonDown
0040f0a2 heidisql.exe System                    TObject.Dispatch
00990a22 heidisql.exe VirtualTrees   25863  +19 TBaseVirtualTree.WndProc
006e5a6a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
0056bbf3 heidisql.exe System.Classes            StdWndProc
7754956d USER32.dll                             DispatchMessageW
0089e5ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0089e663 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0089eab1 heidisql.exe Vcl.Forms                 TApplication.Run
01186f08 heidisql.exe heidisql         105  +41 initialization
7742556b kernel32.dll                           BaseThreadInitThunk
7768372b ntdll.dll                              RtlUserThreadStart
```

**Comment by ansgarbecker** [comment] 2022-01-18 20:27
Duplicate of #1511

**Closed by ansgarbecker** 2022-01-18 20:27 UTC
