### ISSUE TITLE
Access violation at address 000000506A500000 in module 'heidisql.exe'.

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#1179] opened 2020-10-01 13:51 UTC
**Describe the bug**
Changing/editing comment fields in tables from database via interface produces:
 `#1634496361: Access violation at address 000000506A500000 in module 'heidisql.exe'. Execution of address 000000506A500000 Message CharCode:13 Msg:256 `

**To Reproduce**
1. Edit random comment field in random UTF-8 InnoDB table from database via interface and press "Enter", it happens before saving changes.

**Screenshots**
![1](https://user-images.githubusercontent.com/8297417/94818043-55c1a100-0406-11eb-8bbf-b8ae7b938343.png)

**Note**
Comment of field is changed, despite the error.

**Environment:**
 - OS: Windows 10
 - Heidi SQL version 11.0.0.6099
 - Database type and version MySQL 5.7.31

**Comment by ansgarbecker** [comment] 2020-10-01 13:56
Duplicate of #1107

**Closed by ansgarbecker** 2020-10-01 13:56 UTC
