### ISSUE TITLE
Version 11 '#' Comment Bug when Update/Insert

### ISSUE THREAD

**Issue by knassif18** [HeidiSQL/HeidiSQL#1117] opened 2020-08-07 16:41 UTC
Trying to update/insert a string into a column with a '#' symbol included in the string.  I believe HeidiSQL thinks this is a comment and it breaks "WHERE" clauses.  Cannot escape the '#' symbol, and nothing works.  Tried the same queries in the previous version and no errors.

**Comment by WesleyM77** [comment] 2020-08-07 18:24
What version of HeidiSQL are you running? What platform are you on? Can you provide example queries? Why didn't you use the issue template when opening this bug?

**Comment by Durgmey** [comment] 2020-08-07 18:53
I have run into this as well.   For me it hit with the query:

UPDATE `Config` SET `caption` = "ID # field" WHERE `configguid` = '{REDACTEDVALUE}';

Also, like knassif18 I was unaware there were templates for the issues.  Happy to use that going forward as soon as I find it.

In my case I'm running HeidiSQL 11.0.0.6077 (64 bit) compiled on 2020-08-07 at 10:25:59 64 bit Windows 10 version 2004, hitting MariaDB 10 running Windows 2019 server

**Comment by WesleyM77** [comment] 2020-08-07 18:56
When you click "New Issue" there's a bug report and feature request option. Either will pre-populate the text box with a template. You kinda have to go out of your way to get rid of it.

**Comment by knassif18** [comment] 2020-08-07 19:03
Actually, I was NOT originally signed in when I posted this.  I clicked the button to write a post and it prompted me to sign in.  After which it showed a giant text box where I can create a title and add text.  So no, I didn't go out of my way to 'avoid' using a template -- I really was unaware.

**Comment by WesleyM77** [comment] 2020-08-07 19:10
I hadn't considered being not logged in when you enter an issue. Apologies. I know Ansgar just updated the templates for bug reports as people not using them has been an issue in the past. I wonder why it doesn't pre-populate in the case you described and if that's a GitHub issue or if he can solve it for future issue submissions.

**Comment by Durgmey** [comment] 2020-08-07 19:16
If it makes things easier one of us can enter it using the template.  I know at least one other person on my team has this going on.   KNASSIF18-  we can enter this in the preferred manner if you want.   (Unless you are already doing so.)

**Comment by ansgarbecker** [comment] 2020-08-08 05:02
I cannot reproduce an error here, and I wrote an INSERT and an UPDATE, both using single quotes and double quotes around my test string with a hash.
Please report error messages.
Would be good if Github was able to force users to use the issue templates.

**Comment by Setitch** [comment] 2020-08-20 10:09
I need to ask - which database are you using?  As you used double quotes to escape the string with hash, and that can work under mysql but other bases are a bit more tricky - postgress uses double quotes for identifier not string for which you should use single quote - maybe thats the problem for you?

**Comment by Durgmey** [comment] 2020-08-20 11:16
In my case I am using MariaDB 10.3.   Also, we discovered that the warning thrown was a false alarm.   The where clause did what it should as the command seems to have been misunderstood by HeidiSQL, but passed on cleanly to MariaDB.   We can keep working safely, we just ignore the warning.

**Comment by ansgarbecker** [comment] 2020-08-21 07:15
Alright, whatever error message this was, I'll close this.

**Closed** 2020-08-21 07:15 UTC
Labels: needs-info
