### ISSUE TITLE
Bug in table copy in menu option

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1213] opened 2020-11-11 11:37 UTC
**Describe the bug**
Hello,

When I right click a table and select "Create New > Table copy" and then a copy of the table is created (with all data), heidi is not showing the correct size.

**To Reproduce**
1 - Right click on the table you want to copy and select "Create New > Table copy"
2 - Ensure the "Data" checkbox is checked in the "Elements to create in new table"
3 - See new table in the treeview with incorrect size
![image](https://user-images.githubusercontent.com/1086401/98806967-de722a80-2411-11eb-9dbd-44e5bc778fde.png)

**Expected behavior**
If the table copied is shown immediately in the treeview I would expect to see the correct size.

**Environment:**
 - OS: Windows 10 64bit
 - HeidiSQL  Version 11.1.0.6116 (64 Bit)
 - Database type and version: MySQL 5.7 (running on docker)

**Comment by ansgarbecker** [comment] 2020-11-13 16:29
This is most likely due to a limitation of InnoDB table engine. You should not rely on that byte size. Please fire a `SELECT COUNT(*) FROM mytable` to verify that.

**Comment by AntonioCS** [comment] 2020-11-14 18:41
@ansgarbecker What do you mean? I know the size is incorrect, I'm just saying that if the table is copied with that it should show the same size.

**Comment by ansgarbecker** [comment] 2020-11-15 14:09
HeidiSQL retrieves the size of the table from the server. The server gives an inaccurate/estimated size, which you are seeing. That is due to the underlying InnoDB engine of your table. That is why you should not rely on that size. HeidiSQL cannot do much about it. Please fire the above mentioned COUNT query instead, to verify whether the copy was successful.

**Comment by AntonioCS** [comment] 2020-11-15 16:18
Or I can just look in the data tab :)

**Comment by ansgarbecker** [comment] 2020-11-15 20:00
Yes, of course, the data tab does nearly the same.
I am closing the issue, as in my understanding that InnoDB limitation was the cause here.

**Closed by ansgarbecker** 2020-11-15 20:00 UTC
Labels: needs-info

**Comment by AntonioCS** [comment] 2020-11-15 20:06
Well.. you can also do something that the size that is seen is correct, if you know the user has selected to copy the data. If it's correct then do that  `COUNT`.

**Comment by ansgarbecker** [comment] 2020-11-16 07:35
A COUNT(*) would introduce huge performance issues when firing against the whole database. That was discussed before.
