### ISSUE TITLE
Hard crash when adding an index

### ISSUE THREAD

**Issue by philipmartian** [HeidiSQL/HeidiSQL#70] opened 2018-01-03 21:04 UTC
used to work in this environment 
Windows home 7-64 Heidi 9.5 
Acer 17" laptop  
Maria DB My SQL
Created new table with 1 int field
Set default to auto increment
Clicked add index
Clicked on default name to rename new index
application locks, must end process to escape Heidi screen

Also set default to custom value zero with same crash
Also tried adding index to existing table with indexes
Heidi error screen flashes by then application screen becomes frozen.
 
Not broken on Lenovo desktop Windows Pro 7 SQL Express

**Comment by ansgarbecker** [comment] 2018-01-04 09:01
You deleted the whole issue template. Please don't do that.

You are not describing a crash, probably some long during process. However, can you reproduce that? I can't, I'm afraid.

**Comment by rentalhost** [comment] 2018-02-12 20:51
Can't reproduce that. 

What do you mean with "clicked on default name to rename new index"?

**My steps:**
* Create a new table `x`;
* Create a column `id` as `INT` and `AUTO_INCREMENT`;
* I went to `Index` tab and clicked on `Add`;
* I clicked twice on `Index 1` (new index) to renamed it;
* Nothing happened at 9.5.0.5245;

**Comment by ansgarbecker** [comment] 2018-02-15 16:31
Closed as no feedback from user.

**Closed by ansgarbecker** 2018-02-15 16:31 UTC
Labels: question
