### ISSUE TITLE
Unable to remove shortcut key

### ISSUE THREAD

**Issue by tkdennis** [HeidiSQL/HeidiSQL#1919] opened 2024-03-04 15:49 UTC
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MariaDB 10.4.32
* OS: Windows 11

**Describe the bug**

* Ctrl+Y shortcut still functions and is not available for reassignment after removing from Delete Line. 
* I expected to be able to reassign Ctrl+Y to a different action.
* I get the message /* Could not apply SynEdit keystroke shortcut "Ctrl+Y" (or secondary: "") to ecRedo. Shortcut already exists. Please go to Tools > Preferences > Shortcuts to change this settings. */

**To Reproduce**

1. Goto Tools->Preferences->Shortcuts->SQL Editing->Delete Line
2. Click Remove (Ctrl+Y is replaced with "(None)")
3. Click OK
4. Ctrl+Y still deletes Line
5. Goto Tools->Preferences->Shortcuts->SQL Editing->Delete Line
6. Ctrl+Y is still the Shortcut for Delete Line
7. Click on first Redo in list (Shift+Alt_BkSp)
8. Change shortcut to Ctrl+Y
9. Message Box appears: Ctrl_Y already assigned to "Delete Line" Remove it there and assign to "Redo" instead?"
10. Click Yes : Ctrl+Y is now on Redo and off Delete Line
11. Click OK : message /* Could not apply SynEdit keystroke shortcut "Ctrl+Y" (or secondary: "") to ecRedo. Shortcut already exists. Please go to Tools > Preferences > Shortcuts to change this settings. */ appears twice
12. Ctrl+Y still delete line

**Screenshots or Crash reports**

Related to #940 
Registry looks updated?
[HKEY_CURRENT_USER\Software\HeidiSQL]
"Shortcut1_ecDeleteLine"=dword:00000000
"Shortcut1_ecRedo"=dword:00004059

**Comment by ansgarbecker** [comment] 2024-03-04 15:57
Duplicate of #733

**Closed by ansgarbecker** 2024-03-04 15:57 UTC
