### ISSUE TITLE
Support MariaDB 10.2 check constraints

### ISSUE THREAD

**Issue by vaintroub** [HeidiSQL/HeidiSQL#75] opened 2018-01-08 19:56 UTC
## Expected behavior

MariaDB supports SQL standard CHECK  constraints, starting with 10.2 for CREATE/ALTER table. 
However HeidiSQL does not  are supported by CREATE TABLE  dialog (CREATE  CODE tab, DDL editor etc)

More information about check constraints in MariaDB can be found in 
https://mariadb.com/kb/en/library/constraint/#check-constraints

## Current behavior

Check constraints are not supported 

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. 
```sql
CREATE TABLE t2 (name VARCHAR(30) CHECK (CHAR_LENGTH(name)>2), start_date DATE, 
  end_date DATE CHECK (start_date IS NULL OR end_date IS NULL OR start_date<end_date));
```
2. Find t2 in the tree, right click/Edit/Create Code, see constraints removed 

```sql
CREATE TABLE `t2` (
	`name` VARCHAR(30) NULL DEFAULT NULL,
	`start_date` DATE NULL DEFAULT NULL,
	`end_date` DATE NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=Innodb
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5
* Database system + version: MariaDB  10.2
* Operating system: Windows

**Comment by rentalhost** [comment] 2018-02-12 21:02
**Possible solution:** create a new column at Table Editor called `Check` that allows a SQL expression.

**Comment by GerhardWw** [comment] 2018-08-20 13:19
@rentalhost: there is no need to change the table, the check constraint is there, as you can see if you run SHOW CREATE TABLE `t2`. So this is only a HeidiSQL issue, this database feature is probably ignored when editing the output from the database system for presenting it in the CREATE TABLE tab.

**Comment by lukinhaspm** [comment] 2019-04-05 19:23
You can fetch some information from CHECK_CONSTRAINTS in information_schema.

I think you can add this option to create "check" in the collumns options

**Comment by lukinhaspm** [comment] 2019-07-23 17:43
This case can be new index, near to FKs

**Comment by richardeaxon** [comment] 2021-01-02 03:34
Any idea when this will be supported? As pointed out there is a real risk of any column constraints being removed if the table is altered in any way using Heidi.

Thanks.

**Comment by ansgarbecker** [comment] 2021-01-03 15:15
Things I found so far:
* check constraints can be bound to a column, but they do not need to
* It's impossible to find out whether an existing check constraint is bound to a column. There is no column reference in `IS`.`check_constraints`. Even if the name of the constraints equals a column name, it's possible the user just named it like that but referenced a different column.
* This means these checks constraints must be presented in the table itself, as a new tab besides the "Foreign keys" tab (not as I was hoping as a new column "Check expression" in the column definition)
* There is no way to alter an existing check constraint. When altering a table, Heidi will need to drop and recreate it:
```
ALTER TABLE t1 DROP CONSTRAINT a_greater;
ALTER TABLE t1 ADD CONSTRAINT a_greater CHECK (a>b);
```
* While the drop query seems to be done silently by the server, the add query has to be done for all check constraints, and for all kinds of modifications.
* I could provide the modifying part in a second step, just leaving check constraints intact in a first step

**Comment by ansgarbecker** [comment] 2021-01-03 20:36
Forgot one issue:
* `check_clause` in IS.check_constraints is limited to 64 characters, so recreation of checks with more than 64 chars will be broken:
```
ALTER TABLE json_chk ADD CONSTRAINT `comment` CHECK (octet_length(`path`) > 0 AND octet_length(`path`) > 1 AND octet_length(`path`) > 2);
SELECT * FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA IN ('test');
```
---
| CONSTRAINT_CATALOG | CONSTRAINT_SCHEMA | CONSTRAINT_NAME | TABLE_NAME | CHECK_CLAUSE | 
| --- | --- | --- | --- | --- | 
| def | test | comment | json_chk | `octet_length(path) > 0 and octet_length(path) > 1 and octet_` | 

This was reported and already fixed in MariaDB: https://jira.mariadb.org/browse/MDEV-24139
Fixed MariaDB versions: 10.2.37, 10.3.28, 10.4.18, 10.5.9

**Comment by richardeaxon** [comment] 2021-01-03 23:03
> Forgot one issue:
> 
> * `check_clause` in IS.check_constraints is limited to 64 characters, so recreation of checks with more than 64 chars will be broken:
> 
> ```
> ALTER TABLE json_chk
>   ADD CONSTRAINT `comment` CHECK
>   (octet_length(`path`) > 0 AND octet_length(`path`) > 1 AND octet_length(`path`) > 2);
> SELECT * FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_SCHEMA IN ('test');
> ```
> 
> CONSTRAINT_CATALOG	CONSTRAINT_SCHEMA	CONSTRAINT_NAME	TABLE_NAME	CHECK_CLAUSE
> def	test	comment	json_chk	`octet_length(path) > 0 and octet_length(path) > 1 and octet_`
> This was reported and already fixed in MariaDB: https://jira.mariadb.org/browse/MDEV-24139
> Fixed MariaDB versions: 10.2.37, 10.3.28, 10.4.18, 10.5.9

You can get all the info from SHOW CREATE TABLE but I am not sure how much parsing you want to do.

**Comment by lukinhaspm** [comment] 2021-01-13 12:18
I saw about the CHECK size limit, but I noticed that in Heidi you truncated the text, but Maria DB accepted ...
![image](https://user-images.githubusercontent.com/11230133/104450706-431b4400-557f-11eb-85a6-b204508729f6.png)
create statment / Show create table
![image](https://user-images.githubusercontent.com/11230133/104451006-b2913380-557f-11eb-8f96-052e1f9ec24d.png)

MariaDB 10.5.8 and 10.2.36

CREATE TABLE `acc` (
  `aip_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `aip_criadopor` smallint(5) unsigned NOT NULL COMMENT 'Criado por',
  `aip_criadoem` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Criado em',
  `aip_atualizadopor` smallint(5) unsigned DEFAULT NULL COMMENT 'Atualizado por',
  `aip_atualizadoem` datetime DEFAULT NULL ON UPDATE current_timestamp() COMMENT 'Atualizado em',
  `aip_desativadopor` smallint(5) unsigned DEFAULT NULL COMMENT 'Desativado por',
  `aip_desativadoem` datetime DEFAULT NULL COMMENT 'Desativado em',
  PRIMARY KEY (`aip_id`) USING BTREE,
  CONSTRAINT `aip_atualizadoem` CHECK (`aip_atualizadoem` >= `aip_criadoem`),
  CONSTRAINT `aip_desativadoem` CHECK (`aip_desativadoem` >= `aip_criadoem` or `aip_desativadoem` >= `aip_atualizadoem`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1

**Comment by ansgarbecker** [comment] 2021-01-13 12:48
That's what I meant two comments above. This is not an issue in HeidiSQL, but in older MariaDB versions, see here: https://jira.mariadb.org/browse/MDEV-24139
HeidiSQL does - for good reasons - not parse the `SHOW CREATE TABLE` code, but relies on what IS.CHECK_CONSTRAINTS returns.

**Comment by lukinhaspm** [comment] 2021-01-13 14:02
@ansgarbecker sorry, I read again and undertand now... :D

**Comment by ansgarbecker** [comment] 2021-01-13 16:39
Further investments:
* `ALTER TABLE .. CHANGE COLUMN` deletes a _field level_ check constraint from a JSON column
* the same query does not remove _table level_ check constraints. Even when their name equals the name of the modified column
* there is no indicator for table/field level in IS.CHECK_CONSTRAINTS, neither in IS.TABLE_CONSTRAINTS
* only the `SHOW CREATE TABLE` result tells whether a check constraint has table or field level
* `CREATE TABLE` and `ALTER TABLE .. ADD COLUMN` automatically create a check constraint for JSON columns [since MariaDB 10.4.3](https://jira.mariadb.org/browse/MDEV-13916)
* => `ALTER TABLE .. ADD CONSTRAINT ...` is required in some cases of column modifications, but it's nearly unpredictable when this is the case
* => one idea is to explcitly drop a constraint named by a modified column, and then recreate it
  * => problematic: [MySQL](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html) does not name a field level check constraint by its column name, but differently: "table name, a literal _chk_, and an ordinal number (1, 2, 3, ...)"
* MySQL lacks a column `TABLE_NAME` in IS.CHECK_CONSTRAINTS (MariaDB has it), which is why my current implementation would not work on MySQL. I have to join IS.CHECK_CONSTRAINTS with IS.TABLE_CONSTRAINTS to support MySQL as well.

**Comment by ansgarbecker** [comment] 2021-01-14 20:55
@vaintroub do you know a way to modify a column without deleting its field level check constraint? I thought I could drop it explicitly and recreate it afterwards, but MairaDB 10.3.12 says it does not exist:

```sql
CREATE TABLE json_chk (jscol JSON NOT NULL CHECK (json_valid(jscol)));
-- user modifies the column's null allowance:
ALTER TABLE json_chk CHANGE COLUMN jscol jscol JSON NULL;
-- problem: constraint was deleted inadvertently
-- alternative: drop constraint, change column, recreate check constraint on table level
ALTER TABLE json_chk DROP CONSTRAINT jscol, CHANGE COLUMN jscol jscol JSON NULL, ADD CONSTRAINT jscol CHECK(json_valid(jscol));
-- SQL error: Can't DROP CONSTRAINT `jscol`; check that it exists
```

I also can't find a way to detect whether a check constraint was created on a field level (like in above `CREATE` query) or using the `ADD CONSTRAINT .. CHECK ..` syntax. If I could distinct between these two types, I could recreate a check constraint along with other clauses in a `ALTER TABLE .. CHANGE COLUMN ..` query.

**Comment by lukinhaspm** [comment] 2021-01-14 21:08
I ask a friend to saw how DBForge do it:

Create a table with some constrains

Try to rename ONE field using in some constrain (one or more)

USE test;

--
-- Drop check constraint
--
ALTER TABLE teste
   DROP CONSTRAINT teste_desativadoem;

--
-- Alter column `teste_desativadoem2` on table teste`
--
ALTER TABLE teste
  CHANGE COLUMN teste_desativadoem teste_desativadoem2 DATETIME DEFAULT NULL COMMENT 'Desativado em';

--
-- Create check constraint
--
ALTER TABLE teste 
  ADD CONSTRAINT teste_desativadoem CHECK (teste_desativadoem2 >= teste_criadoem);

**Comment by ansgarbecker** [comment] 2021-01-14 21:13
@lukinhaspm that just works for table level constraints - straight forward. I meant field level constraints:

    CREATE TABLE json_chk (
      jscol JSON NOT NULL CHECK (json_valid(jscol))
    );

Try to drop such a constraint - I'm curious what error you get.

I suppose I have two ways to go:
* parse the `SHOW CREATE TABLE` result
* do not support field level check constraints

**Comment by lukinhaspm** [comment] 2021-01-14 21:24
I drop the constrain:

ALTER TABLE json_chk 
   CHANGE COLUMN jscol jscol LONGTEXT BINARY CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
   
   works fine after this, keep data normaly

**Comment by richardeaxon** [comment] 2021-01-14 21:29
> I suppose I have two ways to go:
> 
>     * either: parse the `SHOW CREATE TABLE` result
> 
>     * or: do not support field level check constraints

I found this which appears to work just fine to get column level constraints: https://dataedo.com/kb/query/mariadb/list-table-check-constraints in MariaDB (article states it also works for MySQL). This query does the trick:

```
select constraint_schema as table_schema,
table_name,
constraint_name,
check_clause as definition
from information_schema.check_constraints
order by table_schema,
table_name;
```

**Comment by lukinhaspm** [comment] 2021-01-14 21:31
@ansgarbecker 
   After that, I try to recreate the constrain, but DBForge haven't the option to create like you do (in column)! When I create I have the script:
   ALTER TABLE json_chk
ADD CONSTRAINT CK_json_chk CHECK (JSON_VALID(jscol));

**Comment by lukinhaspm** [comment] 2021-01-14 21:34
https://dbfiddle.uk/?rdbms=mariadb_10.4&fiddle=3f5e20272df94a0ba9d7fa10b4505124

helps?

**Comment by ansgarbecker** [comment] 2021-01-15 06:27
No, these examples don't show how to distinct between field level and table level check constraints. If modifying a column is the only way to edit/delete a field level constraint, then HeidiSQL needs to see _if it currently is on field level, before altering the table_. There is no column reference in IS.CHECK_CONSTRAINTS and neither in IS.TABLE_CONSTRAINTS.

**Comment by vaintroub** [comment] 2021-01-15 06:32
> @vaintroub do you know a way to modify a column without deleting its field level check constraint? I thought I could drop it explicitly and recreate it afterwards, but MairaDB 10.3.12 says it does not exist:
> 
> ```sql
> -- table created somewhere, not in HeidiSQL:
> CREATE TABLE json_chk (
>   jscol JSON NOT NULL CHECK (json_valid(jscol))
> );
> -- user modifies the column's null allowance:
> ALTER TABLE json_chk
>   CHANGE COLUMN jscol jscol JSON NULL;
> -- problem: constraint was deleted inadvertently
> -- alternative: drop constraint, change column, recreate check constraint on table level
> ALTER TABLE json_chk DROP CONSTRAINT jscol,
>   CHANGE COLUMN jscol jscol JSON NULL,
>   ADD CONSTRAINT jscol CHECK(json_valid(jscol));
> -- SQL error: Can't DROP CONSTRAINT `jscol`; check that it exists
> ```
> 
> I also can't find a way to detect whether a check constraint was created on a field level (like in above `CREATE` query) or using the `ADD CONSTRAINT .. CHECK ..` syntax. If I could distinct between these two types, I could recreate a check constraint along with other clauses in a `ALTER TABLE .. CHANGE COLUMN ..` query.


Why to recreate a constraint?  If you change a column, one of the reasons is that you might want to remove a constraint

**Comment by ansgarbecker** [comment] 2021-01-15 06:53
>  If you change a column, one of the reasons is that you might want to remove a constraint

Yes, if the user intended to do that. Note that I am talking about the table editor GUI in HeidiSQL. For cases where the user just wants to modify the column's data type, I'd like to keep (or recreate) a field level check constraint. That was what @richardeaxon  asked for in #1274:

> ALTERing the table created with a JSON column removes the CHECK constraint

**Comment by richardeaxon** [comment] 2021-01-15 07:23
> 
> 
> No, these examples don't show how to distinct between field level and table level check constraints. If modifying a column is the only way to edit/delete a field level constraint, then HeidiSQL needs to see _if it currently is on field level, before altering the table_. There is no column reference in IS.CHECK_CONSTRAINTS and neither in IS.TABLE_CONSTRAINTS.

Ok, I now see the problem. If I create this table

```
CREATE TABLE t (
path VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
json_c1 JSON NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
json_c2 JSON NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
comment VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
UNIQUE INDEX path (path),
CONSTRAINT json_c1 CHECK (path > 0)
)
WITH SYSTEM VERSIONING
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

And then dump the information schema I get this:

"CONSTRAINT_CATALOG"	"CONSTRAINT_SCHEMA"	"TABLE_NAME"	"CONSTRAINT_NAME"	"CHECK_CLAUSE"
"def"	"prod_sync_re"	"t"	"json_c1"	"json_valid(`json_c1`)"
"def"	"prod_sync_re"	"t"	"json_c2"	"json_valid(`json_c2`)"
"def"	"prod_sync_re"	"t"	"json_c1"	"`path` > 0"

You can infer that the "constraint_name" is the column name for lines 1 and 2 as you cannot specify a name for a column constraint. You can also infer that if there is a duplicate constraint name the first one will be a column and the second one is a table constraint. The edge case is if there is only a table constraint with the same name as a column - you cannot infer if it is column or table.

**Comment by vuvova** [comment] 2021-01-15 09:01
https://jira.mariadb.org/browse/MDEV-24598

**Comment by vuvova** [comment] 2021-01-15 09:05
> MySQL lacks a column TABLE_NAME in IS.CHECK_CONSTRAINTS

because _supposedly_ MySQL implemented that part of the standard that says that constraint names must be unique within the schema. In MariaDB they're only unique within a table (presuming MDEV-23498 is fixed), so MariaDB had to add a non-standard TABLE_NAME column to the IS.CHECK_CONSTRAINTS table.

**Comment by vuvova** [comment] 2021-01-15 09:24
it seems the standard doesn't differentiate between "column" and "table" constraints (at least, I cannot see where it does). That's why IS tables don't show this information.

MariaDB clearly does differentiate, so this could be a valid feature request to show it in IS somewhere.

**Comment by richardeaxon** [comment] 2021-01-15 11:04
> 
> 
> > MySQL lacks a column TABLE_NAME in IS.CHECK_CONSTRAINTS
> 
> because _supposedly_ MySQL implemented that part of the standard that says that constraint names must be unique within the schema. In MariaDB they're only unique within a table (presuming MDEV-23498 is fixed), so MariaDB had to add a non-standard TABLE_NAME column to the IS.CHECK_CONSTRAINTS table.

Thanks for picking this up @vuvova. So if the constraint name followed these rules we can infer if the CHECK is column or table level from the IS:

1. Column level CHECK must have name as column name
2. Table level CHECK name if specified cannot be the same as a column name

Not sure if 2. is practical as it will create all manner of issues during ALTER TABLE. I guess if what you are saying is that CONSTRAINT names must be unique per schema, that 2. should not be an issue and then there is enough uniqueness to determine column or table constraint. This will work for MariaDB but not for MySQL as MySQL allows named column constraints but MariaDB always uses column name for column constraints.

**Comment by vuvova** [comment] 2021-01-15 12:14
not quite.

I'm saying that
1. In SQL standard (and, supposedly, in MySQL) CHECK constraint names are unique within schema, but in MariaDB CHECK constraint names are unique within a table
2. Table level CHECK name definitely **can** be the same as a column name
3. "MySQL allows named column constraints but MariaDB always uses column name for column constraints" — don't rely on that, looks like an omission on our part. [MDEV-24602](https://jira.mariadb.org/browse/MDEV-24602)
4. The correct solution would be to show in IS whether the constraint is on the column or on the table. [MDEV-24601](https://jira.mariadb.org/browse/MDEV-24601)

**Comment by ansgarbecker** [comment] 2021-01-15 20:06
@vuvova thanks for your analysis and creation of MDEV-24601

I will get the remaining stuff working as good as it can in Heidi's table editor.

By the way, here's a proof that a table can have a column-level constraint plus a table-level constraint both with the same name:

    CREATE TABLE json_chk7 (jscol JSON NOT NULL CHECK (JSON_VALID(jscol)), CONSTRAINT jscol CHECK (1 > 0));

![grafik](https://user-images.githubusercontent.com/7986591/104773397-4841e400-5775-11eb-89e1-198314b20917.png)

**Comment by ansgarbecker** [comment] 2021-01-17 13:10
* Constraint editor is now working for table level constraints on MariaDB.
* Field level constraints are displayed, but unsupported for modification and deletion. These will still be silently dropped when you alter a column definition. If the user does not have that in mind, I can just recommend to prefer table level constraints instead of field level constraints. At least until MariaDB has fixed [MDEV-24601](https://jira.mariadb.org/browse/MDEV-24601)
* Users will get an error when trying to delete or modify a field level constraint: _Can't DROP CONSTRAINT foobar; check that it exists_ . While I could work around that using the `DROP CONSTRAINT IF EXIST ..` syntax, I prefer to get an error dialog instead of a silent ignorance.
* MySQL, MSSQL and PostgreSQL need a different query syntax to be supported, as these don't have that column `IS.CHECK_CONSTRAINTS.TABLE_NAME`. They have it instead in `IS.TABLE_CONSTRAINTS`, but querying that table is somehow very slow on servers with many databases and/or tables

**Closed by ansgarbecker** 2021-01-17 13:10 UTC
Labels: feature, nettype-mysql

**Comment by RupaliGaikwadMercury** [comment] 2023-08-24 17:01
MariaDb getting crashed with following scenario:

Create the following table,
CREATE TABLE `test` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `val` INT(11)COMMENT 'abcd' CHECK (`val` = 1 OR `val` IS NULL),
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

Select the respective table in the 'Object Browser' and click on 'Alter Table'.

This issue is reproducible with MariaDB 10.8.3 (and v10.4 and v10.5 as reported by the user) in SQLyog v13.2.0. The issue is not reproducible if the COMMENT is not passed to the column with the 'CHECK' constraint.

Please help on this

**Comment by ansgarbecker** [comment] 2023-08-24 17:14
Are you sure you want to report an SQLyog issue in the HeidiSQL tracker? Or did you perhaps mean HeidiSQL?
