### ISSUE TITLE
Double datatype length/set display error

### ISSUE THREAD

**Issue by MT-QD** [HeidiSQL/HeidiSQL#1087] opened 2020-07-10 14:54 UTC
## Steps to reproduce this issue

1. Step 1; Create a table with a column with datatype double like so
```
CREATE TABLE `test_table` (
	`test_column` DOUBLE NULL DEFAULT NULL
)
COLLATE='utf8mb4_general_ci'
ENGINE=MyISAM
;
```
2. Step 2;
Check the table structure in Heidi. This shows the column with a Length/Set of `22,0` and the create statement also changed the datatype of the column to `DOUBLE (22,0)` 
![image](https://user-images.githubusercontent.com/16702364/87167209-ed629800-c2cc-11ea-885a-b85d719bd721.png)
Making a dump with create statement of the table via Heidi gives the correct datatype of `DOUBLE`

## Current behavior

Heidi shows a different datatype to the one the table was created with for a DOUBLE column

## Expected behavior

The datatype should be `DOUBLE` and not `DOUBLE (22,0)`

* **HeidiSQL version:** 
  
Version 11.0.0.5919 (64 Bit)
* **Database system and version:** 
  
MariaDB 10.1.38
* **Operating system:** 
  
Windows 10 Pro

**Comment by Setitch** [comment] 2020-08-13 08:37
Just want to cite 

> As of MySQL 8.0.17, the nonstandard FLOAT(M,D) and DOUBLE(M,D) syntax is deprecated and support for it will be removed in a future MySQL version.

**Comment by ansgarbecker** [comment] 2020-08-13 08:44
I suppose this is a duplicate of #953 - which I already fixed. Please update.

**Closed by ansgarbecker** 2020-08-13 08:44 UTC
