### ISSUE TITLE
SQLite renaming table throws error

### ISSUE THREAD

**Issue by TheColorRed** [HeidiSQL/HeidiSQL#1561] opened 2022-04-03 15:41 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: SQLite 3.34.0
* OS: Windows 10

**Describe the bug**

Renaming a table executes the wrong query causing an error:

> /* SQL Error (1): near "RENAME": syntax error */

```sql
-- Query that gets executed:
RENAME TABLE my_table to my_table_old;

-- Query that should be executed:
ALTER TABLE my_table RENAME TO my_table_old;
```

**To Reproduce**

1. Go to Table tab
2. Change the table name
3. Click save

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2022-04-03 15:54
Duplicate of #1427 
Please use the latest nightly build before reporting issues.

**Closed by ansgarbecker** 2022-04-03 15:54 UTC
