### ISSUE TITLE
Support JSON column type in MariaDB >= 10.4.3

### ISSUE THREAD

**Issue by richardeaxon** [HeidiSQL/HeidiSQL#1274] opened 2021-01-02 04:21 UTC
**Is your feature request related to a problem? Please describe.**
JSON column type is supported as a LONGTEXT with a CHECK constraint applied to the column.

**Describe the solution you'd like**
ALTERing the table created with a JSON column removes the CHECK constraint. This issue is related to the lack of support for CHECK constraints in Heidi as per issue https://github.com/HeidiSQL/HeidiSQL/issues/75

**Describe alternatives you've considered**
None. CHECK constraints are required to support JSON column types, or enforce checks via application code. This is not ideal as invalid JSON entered into the database could severely break applications - decoding invalid JSON could result in NULL or an exception. Double checking that JSON data from the database is valid is an added overhead.

**Additional context**
Using the following example see the output of the SHOW CREATE TABLE:

```
CREATE TABLE `t` (
	`path` VARCHAR(100) NOT NULL COLLATE 'utf8_general_ci',
	`json_schema` JSON NOT NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`comment` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	UNIQUE INDEX `path` (`path`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

SHOW CREATE TABLE t;

CREATE TABLE `t` (
  `path` varchar(100) NOT NULL,
  `json_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '' CHECK (json_valid(`json_schema`)),
  `comment` varchar(100) DEFAULT NULL,
  UNIQUE KEY `path` (`path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by ansgarbecker** [comment] 2021-01-02 08:01
This is a duplicate of #75, isn't it? HeidiSQL already provides JSON in the data type dropdown on the table editor.

**Comment by richardeaxon** [comment] 2021-01-02 09:19
> This is a duplicate of #75, isn't it? HeidiSQL already provides JSON in the data type dropdown on the table editor.

I guess it could be classified duplicate. What I am more concerned about is that Heidi strips any table definitions it does not explicitly understand when altering an existing table. This has caused me issues on a number of occasions. Is it not possible to rather just leave attributes not understood as is instead of removing them?

**Comment by ansgarbecker** [comment] 2021-01-02 14:03
I'm afraid no - this CREATE/ALTER stuff is highly complex, especially since HeidiSQL supports MS SQL, PG and SQLite as well, all with different syntaxes. Even if you focus on MySQL/MariaDB only, modifying a column's data type is done with an ALTER query, and the server expects the whole definition in it, not only a part of it. If you leave out that `CHECK` clause, it gets deleted by the server.
I'll go and put some priority on issue #75.

**Closed by ansgarbecker** 2021-01-02 14:03 UTC
