### ISSUE TITLE
generated columns - invalid (?) options added to CREATE or ALTER statements

### ISSUE THREAD

**Issue by frankw333** [HeidiSQL/HeidiSQL#1332] opened 2021-03-12 08:28 UTC
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: MariaDB 10.4.17
* OS: Win10 

**Describe the bug**

I wanted to add a generated column (VARCHAR, json_value). To start with expression and virtuality were removed when I saved the table.
Tried different things, but ended up to find that HeidiSQL adds 'Allow NULL', default value 'NULL' and a 'COLLATED ...' to the field. This happens every time I open the table editor. When I remove these it works.

**To Reproduce**

1. create a table:
CREATE TABLE table22 (
b VARCHAR(32),
d VARCHAR(5) AS (left(b,5)) PERSISTENT
);

2. open in table editor and check Allow NULL, default value and Collation. The Create statement is then:
CREATE TABLE table22 (
`b` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
`d` VARCHAR(5) **DEFAULT NULL** AS (left(`b`,6)) stored **COLLATE 'utf8_general_ci'**
) COLLATE='utf8_general_ci' ENGINE=InnoDB ;

3. MariaDB SHOW CREATE TABLE table22 gives:
CREATE TABLE `table23` (
  `b` varchar(32) DEFAULT NULL,
  `d` varchar(5) GENERATED ALWAYS AS (left(`b`,5)) STORED
) ENGINE=InnoDB DEFAULT CHARSET=UTF8

Related issues could be:
- HeidiSql forgets about generated columns and virtuality #1007
- Creating and handling generated columns fails #778

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2021-12-11 12:09
Should be fixed by c203956 for the next build.

**Comment by ansgarbecker** [comment] 2021-12-11 12:09
Duplicate of #1210

**Closed by ansgarbecker** 2021-12-11 12:09 UTC
