### ISSUE TITLE
CTRL+V doesn't work in data cell

### ISSUE THREAD

**Issue by Cassetete** [HeidiSQL/HeidiSQL#592] opened 2019-04-01 14:29 UTC
## Steps to reproduce this issue

1. Copy to put anytext in clipboard
2. Enter in inline cell data
3. Try to paste WITH keyboard shortcut (CTRL+V)  

## Current behavior
The paste doesn't work. Nothing change (like if I do nothing).
It's wierd because right-click then paste option work, but it's so long alternative.

## Expected behavior
The text in clipboard is put in cell

## Possible solution
The event on data cell widget isn't not handle or error in handle.

## Environment
Tested on Windows 10.0.17763.379

* **HeidiSQL version:** 
10.1.0.5508 (and some build before but I don't noted).

**Comment by ansgarbecker** [comment] 2019-04-01 16:57
Please verify <kbd>Ctrl+V</kbd> is still assigned to "Paste":

![grafik](https://user-images.githubusercontent.com/7986591/55345358-fc468200-54af-11e9-9984-0090645dde81.png)

**Comment by fifonik** [comment] 2019-04-02 01:47
I never re-defined shortcuts in Heidi and it works for me (I can paste into value in Data grid while inline-editing).
Checked shortcuts and 'Ctrl+V' is there (btw, it would be nice to be able to search through these shortcuts if shortcut I'm interested in is assigned).

**Comment by assachs** [comment] 2019-04-06 12:56
I have the same problem:
if i configure STRG-v then i can use STRG-shift-v. if i configure STRG-shift-v then i can use STRG-v.

**Comment by assachs** [comment] 2019-04-07 19:52
What is really strange:
sometimes it is working. Sometimes not.

Now, i had two open instances from heidisql. One was Pasting on ctrl-v the other on ctrl-shift-v.
After closing both and restarting, both are working with ctrl-v.

**Comment by Arffeh** [comment] 2019-04-09 06:28
I believe I was just hit by the same issue.

To correct it I did a combination of switching views and resetting clipboard state by copying from something.

Next time it occurs, I'll do the above bit-by-bit to see what correctly unsticks it.

**Comment by Arffeh** [comment] 2019-04-11 05:14
Just an update, this occurred specifically in the "Data" tab. Swapping to a query tab and back allowed me to paste again. 

The Data tab was fully usable/scrollable/etc, it was just pasting that didn't work.

**Comment by szmcdull** [comment] 2019-11-09 02:53
I find out a repo. At first CTRL-V works fine. But after copy some text from the log pane (no matter CTRL-C or through the context menu), then it breaks.

**Comment by rentalhost** [comment] 2019-11-09 03:27
I could reproduce with @szmcdull method.

1. Go to **Data** tab;
2. At this point: you could copy and past cells;
3. Then copy some log information;
4. Try paste to a cell: it will not works anymore;
5. Change to **Query** tab, for instance, and back again to **Data** tab will made it works again;

**Comment by Ejsstiil** [comment] 2019-11-26 17:04
Can confirm that as well, CTRL + C copies the cell content, but CTRL + V does not work on another cell - even when you are in edit (white) cell.

CTRL + V has been disabled in the GRID??

**Comment by ansgarbecker** [comment] 2020-01-25 18:56
I heard from another user which had the same problem, but v10.3 solved it for him: https://www.heidisql.com/forum.php?t=35471

Please also verify if the issue persists in the current release.

**Comment by ansgarbecker** [comment] 2020-01-25 19:05
Oh I just could reproduce it with the latest build.. The inactive paste and cut actions where caused by my changes in a50c21a38322f8eed7f86e88906866ff9746cde4 . Just fixed that.

**Closed** 2020-01-25 19:05 UTC
Labels: bug
