### ISSUE TITLE
EAccessViolation - Access violation at address 006A9AE4

### ISSUE THREAD

**Issue by Yousha** [HeidiSQL/HeidiSQL#323] opened 2018-08-02 10:29 UTC
## Steps to reproduce this issue

1. Step 1: Open HeidiSQL

2. Step 2: Open a Remote connection to MySQL

3. Step 3: Select a database.

4. Step 4: Click on Query window and wait few minutes to get automatically **disconnected** from the Remote connection.

5 Step 5: Write a simple query(`SELECT * FROM x`) then **execute** it.
Finally HeidiSQL crashes!

## Current behavior

HeidiSQL crashes

> exception number   : 1
> exception class    : EAccessViolation
> exception message  : Access violation at address 006A9AE4 in module 'heidisql.exe'. Read of address 000CE09C.

## Expected behavior

HeidiSQL must Re-connect to Remote  server then execute query in Query window.

## Possible solution

-

## Environment

date/time          : 2018-08-02, 14:39:19, 874ms
computer name      : x-PC
user name          : x <admin>
registered owner   : x
operating system   : Windows 7 Service Pack 1 build 7601
system language    : English
system up time     : 51 minutes 17 seconds
program up time    : 16 minutes 32 seconds
processors         : 4x Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
physical memory    : 2670/3450 MB (free/total)
free disk space    : (C:) 42.18 GB
display mode       : 1366x768, 32 bit
process id         : $e7c
allocated memory   : 126.95 MB
largest free block : 1.44 GB
executable         : heidisql.exe
exec. date/time    : 2018-07-21 20:27
version            : 9.5.0.5282
compiled with      : Delphi XE5

* **HeidiSQL version:** 

9.5.0.5282

* **Database system and version:** 

MySQL 5.6

* **Operating system:** 

Windows 7 Service Pack 1 build 7601 32bit

## Stacktrace

```
madExcept version  : 4.0.12
callstack crc      : $e48ec0e1, $d09a302e, $d09a302e
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 006A9AE4 in module 'heidisql.exe'. Read of address 000CE09C.

main thread ($c88):
006a9ae4 heidisql.exe SynEditHighlighter  1184   +9 TSynCustomHighlighter.Next
0076fcf9 heidisql.exe SynHighlighterSQL   1892  +39 TSynSQLSyn.Next
006d5ca4 heidisql.exe SynEdit             4613 +204 PaintLines
006d5fc0 heidisql.exe SynEdit             4694  +53 TCustomSynEdit.PaintTextLines
006d1eed heidisql.exe SynEdit             2906  +61 TCustomSynEdit.Paint
005bbbb7 heidisql.exe Vcl.Controls                  TCustomControl.PaintWindow
005b5ef1 heidisql.exe Vcl.Controls                  TWinControl.PaintHandler
005b66e4 heidisql.exe Vcl.Controls                  TWinControl.WMPaint
005bbb51 heidisql.exe Vcl.Controls                  TCustomControl.WMPaint
00727a49 heidisql.exe VirtualTrees       17412   +8 TBaseVirtualTree.WMPaint
005b1205 heidisql.exe Vcl.Controls                  TControl.WndProc
005b5d25 heidisql.exe Vcl.Controls                  TWinControl.WndProc
006ddb0a heidisql.exe SynEdit             8581  +22 TCustomSynEdit.WndProc
005b5368 heidisql.exe Vcl.Controls                  TWinControl.MainWndProc
0053c7e0 heidisql.exe System.Classes                StdWndProc
77366feb ntdll.dll                                  KiUserCallbackDispatcher
7726649c USER32.dll                                 PeekMessageW
00686280 heidisql.exe Vcl.Forms                     TApplication.ProcessMessage
006863a2 heidisql.exe Vcl.Forms                     TApplication.HandleMessage
006866dd heidisql.exe Vcl.Forms                     TApplication.Run
009c5c0b heidisql.exe heidisql              80  +24 initialization
760b3c43 kernel32.dll                               BaseThreadInitThunk
```

**Comment by Whissi** [comment] 2018-09-26 00:08
I think I hit the same:

```
date/time          : 2018-09-26, 01:59:35, 54ms
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : German
system up time     : 11 hours 25 minutes
program up time    : 7 minutes 22 seconds
processors         : 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
physical memory    : 19332/32644 MB (free/total)
free disk space    : (C:) 13.02 GB
display mode       : 1920x1200, 32 bit
process id         : $2380
allocated memory   : 121.12 MB
largest free block : 8185.15 GB
executable         : heidisql.exe
exec. date/time    : 2018-09-19 19:34
version            : 9.5.0.5293
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $409e6063, $23eb2799, $23eb2799
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 000000000084C19E in module 'heidisql.exe'. Read of address 0000000005538000.

main thread ($1468):
0084c19e heidisql.exe SynEditHighlighter 1184   +8 TSynCustomHighlighter.Next
00963753 heidisql.exe SynHighlighterSQL  1892  +39 TSynSQLSyn.Next
0084c32c heidisql.exe SynEditHighlighter 1236   +5 TSynCustomHighlighter.SetLineExpandedAtWideGlyphs
0088f185 heidisql.exe SynEdit            4566 +157 PaintLines
0088f8ed heidisql.exe SynEdit            4694  +53 TCustomSynEdit.PaintTextLines
00887b4c heidisql.exe SynEdit            2906  +61 TCustomSynEdit.Paint
006a6856 heidisql.exe Vcl.Controls                 TCustomControl.PaintWindow
0069d603 heidisql.exe Vcl.Controls                 TWinControl.PaintHandler
0069e49f heidisql.exe Vcl.Controls                 TWinControl.WMPaint
006a67e8 heidisql.exe Vcl.Controls                 TCustomControl.WMPaint
008988a8 heidisql.exe SynEdit            7370  +16 TCustomSynEdit.WMPaint
0040d90e heidisql.exe System                       TObject.Dispatch
00695ca3 heidisql.exe Vcl.Controls                 TControl.WndProc
0069d36e heidisql.exe Vcl.Controls                 TWinControl.WndProc
0089c5a6 heidisql.exe SynEdit            8581  +22 TCustomSynEdit.WndProc
0069c5aa heidisql.exe Vcl.Controls                 TWinControl.MainWndProc
005dce43 heidisql.exe System.Classes               StdWndProc
7755b5cb ntdll.dll                                 KiUserCallbackDispatcher
772e9054 USER32.dll                                PeekMessageW
008156bc heidisql.exe Vcl.Forms                    TApplication.ProcessMessage
00815833 heidisql.exe Vcl.Forms                    TApplication.HandleMessage
00815d1f heidisql.exe Vcl.Forms                    TApplication.Run
00cd5227 heidisql.exe heidisql             80  +24 initialization
773e59cb kernel32.dll                              BaseThreadInitThunk
7754385b ntdll.dll                                 RtlUserThreadStart
```

1. I started HeidiSQL
2. I connected to a MySQL server via SSH tunnel
3. I clicked "Query" tab and run a simple query (like `SHOW GLOBAL VARIABLES LIKE 'innodb_%'`)
4. I restarted the MySQL server through another SSH session using a different program.
5. When MySQL became available again I hit "F9" key to re-run the query and HeidiSQL crashed

**Comment by ansgarbecker** [comment] 2018-09-27 05:52
This is a duplicate of issue #57

**Closed** 2018-09-27 05:52 UTC
Labels: duplicate
