### ISSUE TITLE
Text editor behaves weirdly and undo removes semi-random parts

### ISSUE THREAD

**Issue by Tokeiburu** [HeidiSQL/HeidiSQL#1212] opened 2020-11-10 01:10 UTC
**Describe the bug**
The query text editor acts weird at times, and it messes up with the undo commands. It appears to be related to the feature where key words are automatilly set to uppercase.

**To Reproduce**
1. Open a new blank query tab.
2. Copy and paste the following query (in lowercase):
```
select * from `char` where `char_id` = 2373558
```
3. Select the word "where", using your mouse (using keyboard shortcuts will not cause this issue) and then press the `*` key (or any other control symbol, like `(, @, /, -, etc`).
4. Instead of erasing the word, it will append the asterisk at the end, and uppercase the word.
5. Undoing/pressing Ctrl-Z once will undo the change, but keep the uppercase. Pressing Ctrl-Z again will remove something nearby. Sometimes part of the text at random.
6. The undo issues is probably related to the first part, though, but it is extremely annoying when editing queries nonetheless.

**Expected behavior**
Typing letters on selected text should be overwritten by the pressed keys like any text editor.

**Environment:**
 - OS: [e.g. Windows 7]
 - HeidiSQL version [e.g. 11.1.0.6116]

**Comment by ansgarbecker** [comment] 2020-11-10 06:22
This is likely due to the auto-uppercase feature. Please disable and retry:

![grafik](https://user-images.githubusercontent.com/7986591/98635549-84943680-2325-11eb-808c-e30297a6d953.png)

**Comment by Tokeiburu** [comment] 2020-11-10 16:58
Disabling the uppercase feature does fix the issue. Although it would be nice to have the uppercase feature activate without the issue.

**Comment by ansgarbecker** [comment] 2020-11-10 20:30
Yes, that's true. That was more for verifying the cause is really this uppercase-feature.

I think this is a duplicate of #1047

**Closed by ansgarbecker** 2020-11-10 20:30 UTC
Labels: bug, needs-info
