### ISSUE TITLE
backspace while editing a cell doesn't work.

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#919] opened 2020-02-28 17:17 UTC
## Steps to reproduce this issue

1. Have any data show, either in:

* table 'definition' view (where you define column names, datatypes, etc):
![image](https://user-images.githubusercontent.com/13773388/75569228-58948780-5a1a-11ea-9351-577f184a32f6.png)

* ...Or in the Data tab for any table, or within a result set from a query.
e.g.
![image](https://user-images.githubusercontent.com/13773388/75569421-a8734e80-5a1a-11ea-8710-688b46320d36.png)

2. enter 'edit' mode on any cell (double click or F2)

## Current behavior

You can freely edit the data, BUT if you press BACKSPACE, it suddenly 'breaks', the data grid loses focus, and it somehow goes to the Host > Databases tab. At least it doesn't delete anything unintendedly.

I also noticed that if while editing you had the Filter Panel on...

![image](https://user-images.githubusercontent.com/13773388/75569851-875f2d80-5a1b-11ea-925f-b43fe7bd2892.png)

 the first time you press backspace, it CLOSES that panel, instead of deleting a character. The cursor even stays at the same position, and the cell still shows the same data, without deleting anything.
If you press BACKSPACE again, the data grid loses focus and goes to the Host > Databases tab again.

## Expected behavior

Editing should go as normal, and backspace should delete characters instead of messing around.

## Possible solution

Maybe it is an error on the mapping of the backspace key while editing cells?
Note that backspace works normally on the query editor.
Also note that the Del key does delete characters, from left to right, and is a temporal solution, but obviously not ideal.

Note that I'm using Heidi on MacOS via Wine, and it may be an issue, but I really don't think so, because backspace works fine elsewhere on Heidi, or in other apps.

## Environment

* **HeidiSQL version:** 10.3.0.5901 (but it has happened since a few versions back)
  
* **Database system and version:** MySQL 5.1.73 and 5.5.62 (irrelevant anyway)
  
* **Operating system:** MacOS 10.14 (Mojave), with Wine 5.0

**Comment by ansgarbecker** [comment] 2020-02-29 07:14
This is a duplicate of issue #723 . Please note that Wine compatibility is broken currently, at least with the v5 versions. I'm in doubt if these issues can all be fixed.

**Closed by ansgarbecker** 2020-02-29 07:14 UTC
