### ISSUE TITLE
Setting a (signed) TINYINT(1) fails

### ISSUE THREAD

**Issue by rednnnno** [HeidiSQL/HeidiSQL#1714] opened 2022-11-28 17:00 UTC
**Preconditions**

* HeidiSQL version: 12.2.0.6585, but has been in there for quite a while.
* Database type and version: MySQL 5.6.51
* OS: Windows 11 (10.0.22621.819)

**Describe the bug**

You get an error message when trying to update a (signed) TINYINT(1):
`#1634496361: Access violation at address 00000000006E6E81 in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF Message CharCode:9 Msg:256`

I didn't check if UNSIGNED works properly though.

**To Reproduce**

```CREATE TABLE `new_table` (
  `idnew_table` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idnew_table`)
)```
Try to add a value in the list. It doesn't matter if the column is a PRIMARY KEY or not.
Using manual UPDATE/INSERT works just fine.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2022-11-28 18:46
Duplicate of #1353

**Closed by ansgarbecker** 2022-11-28 18:46 UTC
