### ISSUE TITLE
When executing long or multiple queries, HeidiSQL hangs when it tries to get database system info

### ISSUE THREAD

**Issue by Ivan-Perez** [HeidiSQL/HeidiSQL#278] opened 2018-06-01 07:50 UTC
## Steps to reproduce this issue

1. Execute a long query on the query tab or, alternatively, multiple queries (for example, when I detected the error I was doing 10.000 inserts on a remote server, that would take some minutes to complete).
2. Move the mouse over the status bar, exactly over the database system name. When idle, HeidiSQL performs a query to get some information about the database system, and a popup is shown.
3. But when a query is running, the program I think still tries to get that information and hangs because another query is already running.

The exact part of the status bar where you have to over the mouse is this:

![status bar](https://user-images.githubusercontent.com/3533970/40828461-f3e8d2b2-6580-11e8-80a5-1da4861daf6f.png)

## Current behavior

HeidiSQL crashes and no queries continue to be executed. I have to force stop the program.

## Expected behavior / Possible solution

If a query is executing at the moment, don't load database system information.

## Environment

* **HeidiSQL version:** 9.5.0.5278 (this has been happening to me since long time ago)
* **Database system and version:** MySQL 5.5 / MySQL 5.6 / MariaDB 10.2 (happens in multiple database systems)
* **Operating system:**  Windows 7 64-bit

**Comment by ansgarbecker** [comment] 2018-06-01 11:42
This waiter is very normal, as automatic queries are postponed to after the SQL code has finished executing. If HeidiSQL would not block that, the connection would crash, your running queries would be interrupted.

**Comment by Ivan-Perez** [comment] 2018-06-03 17:52
Hi Ansgar.

I don't understand exactly what you mean. Is there something implemented to avoid the issue but isn't working at least in my case, or it's something you didn't care about (because you haven't noticed it) and then can be implemented?

If I wasn't clear on the main post, HeidiSQL hangs when I over the mouse on that part of the status bar, and so I have to force quit the application.

**Comment by ansgarbecker** [comment] 2018-06-03 18:13
Executing two queries at the same time through one connection breaks the connection. You will get some error from the server like "You cannot run this command now" (from MySQL).
So I think it's something which is only fixable with a parallel connection executing your queries, to make the main connection free to execute other queries (like those executed when hovering over the status panel). But having a second connection would also lose session based settings, so I think that's a bad idea, just for fixing a waiting time.

**Comment by Ivan-Perez** [comment] 2018-06-04 07:30
The easiest solution I think is to prevent the execution of the query that gathers the system information data when the connection is busy. Using another parallel connection to get that data I think is overkill, and not really necessary to fix the problem.

**Comment by Ivan-Perez** [comment] 2018-06-04 08:56
But there should be some edge cases where HeidiSQL is trying to execute the query - which causes the program to crash.

I've just tried a query which takes ~5 seconds to complete. If I move the mouse over that area before the query completes, HeidiSQL stops working. I'm using a SSH tunnel to connect to MySQL, I don't know if that matters.

Thanks!

**Comment by magnetik** [comment] 2018-06-13 12:29
I can confirm.

To reproduce:
1. connect to a mysql
2. in Query tab, issue `SELECT SLEEP(50);`
3. during execution, hover over "MySQL 5.X" in the statusbar
4. notice crash

**Comment by ansgarbecker** [comment] 2018-06-13 13:46
Yes, just happened to myself by accident. So the user query is not just postponed, but never executed.

**Comment by ThomasBecker42** [comment] 2024-10-03 08:50
Still happening on 12.8.0.6908 54bit on Windows 11. 
Network setting: "MariaDB or MyQL (TCP/IP)"

Every time a SQL query is actively running and I hover the database section on the bottom, the sand watch time in the bottom right stops counting. 
Then Heidi is frozen and shows "Not responding" on the top left after the Program name and version after a time. 
The initial query result never will be shown as Heidi is frozen. 
No idea if the query finished and we just do not see the result. 

In my company, people then and when complain that Heidi is freezing. 
Maybe most of those cases and also of the incidents you see may be caused by this?

**Comment by ThomasBecker42** [comment] 2024-10-03 08:52
Can´t you deactivate the hover functionality while a request is running?

**Comment by ThomasBecker42** [comment] 2024-10-03 09:01
FYI, for me Heidi also is crashing when running a request in one query tab and then starting a second request on another tab while the one in the first tab still is running. 
So in both cases executing a second query not only results in a connection break with a server error as @ansgarbecker was mentioning above, but also freezes Heidi.

**Comment by ansgarbecker** [comment] 2024-10-03 09:22
I'm not able to reproduce this any longer:

![query-statusbar-hover](https://github.com/user-attachments/assets/ca6ca002-f03f-48a0-85ee-8add37540e96)

However, for cases where this still happens I will attempt to prevent the connection usage from the status bar while a query is running.

**Comment by ansgarbecker** [comment] 2024-10-03 09:34
Please test with the next build coming up in an hour.

**Comment by ThomasBecker42** [comment] 2024-10-03 14:28
@ansgarbecker wow, fixed one hour after my comment, for a 6 year old bug. :-)

Tested nightly heidisql64.r6938.exe by copying it to the program folder. 

The bug is not appearing anymore. 
Just to doublecheck I tried again with 12.8.0.6908 64bit stable from my install and made a video. 
Just to proof that I did not hallucinate. 
Problem still is replicable with the stable version. 

Thanks so much and greetings from Bavaria. 

https://github.com/user-attachments/assets/b47f5112-0c3a-42f5-9d9e-d67758885c6a

**Comment by ThomasBecker42** [comment] 2024-10-03 15:04
@ansgarbecker this cures the symptom and this will prevent many frustration, thanks! 

Do you want me to open another issue to look for the cause? 
For me the same freeze happens when running `SELECT SLEEP(50); ` in one query tab, then opening another tab, also start running `SELECT SLEEP(50); `  --> freeze. Sleep is just a dummy, it happens for any query. 
The log window and the session log does not even show the second query. 
Last thing that happens is the message "checking queries for unsafe UPDATE/..." bottom right after starting the second query. 
![image](https://github.com/user-attachments/assets/fecd052e-4d6a-4de4-9922-aca0948ac357)

**Comment by ansgarbecker** [comment] 2024-10-04 06:57
If you had waited the 20 seconds from the sleep command, you would have seen there is no crash. At least that's what I could see. It was not a crash when the window became unresponsive. HeidiSQL was just waiting in the main thread for the query.

The same happens when you fire a second query in a tab while another one is still running. The first query is not interrupted. HeidiSQL has to wait for the connection to be ready to receive further queries. No crash, just a busy/waiting main thread.
Running a query is done in a separate thread, so the window is responsive normally. Only if you try to run a second thread at the same time does that, for some reason. 
Note that a MySQL connection breaks with `Commands out of sync` if you send simultaneous queries: https://dev.mysql.com/doc/refman/8.4/en/commands-out-of-sync.html - that's why HeidiSQL (and the user) has to wait.

**Closed by ansgarbecker** 2024-10-04 06:57 UTC
Labels: bug, confirmed

**Comment by ThomasBecker42** [comment] 2024-10-08 10:32
@ansgarbecker If I run a ten second sleep and meanwhile open another tab with a ten second sleep and run it, Heidi does not come back responsive any time. 
Not after 10 seconds, not after 20 seconds, not after 5 minutes. 
The log window and the session log does not even show the second query.
Last thing that happens is the message "checking queries for unsafe UPDATE/..." bottom right after starting the second query.

I will open a separate issue and try to help you as good as I can.

**Comment by ansgarbecker** [comment] 2024-10-08 13:25
I did exactly that, with the current build: run `select sleep(10)` in one tab, and immediately the same in a second tab. After 10 seconds the first tab shows its result, and after 20s the second one.
I don't doubt it behaves differently on your side. But we will need to find out why.
