### ISSUE TITLE
Alter Column

### ISSUE THREAD

**Issue by tobisch1591** [HeidiSQL/HeidiSQL#1736] opened 2022-12-28 09:04 UTC
Hey,

unfortunately i get an error when i change a table field in HeidiSQL. It doesn`t 
care if its a rename of the field or a change of the data type.

I can do the change but if i cklick the save button the generated SQL always 
come to the error:

**sql error 102
incorrect syntax near INT**

it doesnt matter which data type here it is. The followin Code is generated bei HeidiSQL in "Alter Code":
`
ALTER TABLE "dbo"."dispo_kopf"
	ALTER COLUMN "dk_ersteller" "dk_erstellerr" INT NULL DEFAULT NULL;
`

Maybe someone can help me?

Thanks a lot.

Best regards
Tobias

**Comment by ansgarbecker** [comment] 2023-01-05 07:59
Duplicate of #1230

**Closed by ansgarbecker** 2023-01-05 07:59 UTC
