### ISSUE TITLE
Allow assigning shortcut on the delete key

### ISSUE THREAD

**Issue by marioawad** [HeidiSQL/HeidiSQL#1226] opened 2020-11-18 19:44 UTC
Hello,

Trying to assign the "Database -> Drop..." shortcut to be issued when I press the delete button.

When I go there I can assign any shortcut but when I use the delete button the shortcut itself is actually deleted.

On my system I also see that "Empty table(s) ..." is assigned to "Shift + Num Del" but I can use it properly with the standard "Shift + Del" key. I tried to assign "Database -> Drop..." to "Num Del" but that didn't work as well.

Using Windows 10 Pro and HeidiSQL Portable x64 both latest versions.

Thank you.

**Comment by aqvador** [comment] 2021-04-13 10:24
+1

**Comment by ansgarbecker** [comment] 2023-02-05 13:30
Confirmed. I already filed a ticket for fixing the cause in the VCL's `THotKey` component: https://quality.embarcadero.com/browse/RSP-40478 . <kbd>Enter</kbd> and <kbd>Tab</kbd> plus their combinations with <kbd>Ctrl</kbd>, <kbd>Alt</kbd> or <kbd>Shift</kbd> are unsupported as well.

This topic has a longer history:
* Initial ticket requesting custom keyboard shortcuts: https://sourceforge.net/p/heidisql/tickets/536/
* First commit using `THotKey` from Sep 2009: c6be8dd5752ba7819c7dacfe4b60dbde38be59c5
* Switch to SynEdit's `TSynHotKey` 2 days later: 445c1adefde5efa56bdb4f29b60d6b611fb7cd61
* Switch back to the `THotKey` in Jun 2020: b4926f3f579c9d82981dea59a0785dd31c040b01
* _New plan for now: place a `TSynHotKey` in the preferences again, but avoiding the issues I had through component updates_

**Comment by ansgarbecker** [comment] 2023-02-05 14:30
<kbd>Del</kbd> and some others can now be used as shortcuts again through the customizer. Note that <kbd>Del</kbd> alone without <kbd>Ctrl</kbd> or other modifiers is already used for a different thing:

![grafik](https://user-images.githubusercontent.com/7986591/216825440-2487cc5c-985c-4549-9047-cb660b40b1fd.png)

However, the non-assignable keys should be fixed in the next nightly build.

**Closed by ansgarbecker** 2023-02-05 14:30 UTC
Labels: bug, confirmed, keyboard
