### ISSUE TITLE
During the replacement of one word for another, throughout the database, an error appeared, as on the screen, and it was impossible to close the dialog box or stop the operation

### ISSUE THREAD

**Issue by toxi22** [HeidiSQL/HeidiSQL#1421] opened 2021-08-07 18:50 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (64 Bit)
* Database type and version: MariaDB - 5.5.68
* OS: Windows 7 SP1 x64 Ultimate

**Describe the bug**
During the replacement of one word for another, throughout the database, an error appeared, as on the screen, and it was impossible to close the dialog box or stop the operation. Lines in the table are one hundred thirteen thousand and more. I had to end the heidisql.exe task through the task manager.

I would like to be able to cancel the operation or close the domain window or skip all errors.

**Screenshots or Crash reports**

![2021-08-06_011041_2](https://user-images.githubusercontent.com/4610098/128610977-93086bc6-ce5c-42d0-a633-177060bd6d4b.png)

**Comment by toxi22** [comment] 2021-08-07 18:52
> **Preconditions**
> 
> * HeidiSQL version: 11.3.0.6295 (64 Bit)
> * Database type and version: MariaDB - 5.5.68
> * OS: Windows 7 SP1 x64 Ultimate
> 
> **Describe the bug**
> 
During the replacement of one word for another, throughout the database, an error appeared, as on the screen, and it was impossible to close the dialog box or stop the operation. Lines in the table are one hundred thirteen thousand and more. I had to end the heidisql.exe task through the task manager.

I would like to be able to cancel the operation or close the domain window or skip all errors.
> 
> **Screenshots or Crash reports**
> 
> ![2021-08-06_011041_2](https://user-images.githubusercontent.com/4610098/128610977-93086bc6-ce5c-42d0-a633-177060bd6d4b.png)

**Comment by ansgarbecker** [comment] 2022-05-04 05:39
Duplicate of #1577

**Closed by ansgarbecker** 2022-05-04 05:39 UTC
