### ISSUE TITLE
Postgresql: Invalid query to create unique index

### ISSUE THREAD

**Issue by TheColorRed** [HeidiSQL/HeidiSQL#1257] opened 2020-12-12 20:16 UTC
When creating an index, an invalid query is executed:

```
ALTER TABLE "clients" ADD UNIQUE INDEX "owner_name" ("owner", "name");
```

This results in the following error:

> ERROR:  syntax error at or near "INDEX" LINE 2:  ADD UNIQUE INDEX "owner_name" ("owner", "name")

The proper query would look like this:

```
CREATE UNIQUE INDEX owner_name ON clients ("owner", "name");
```

**Comment by ansgarbecker** [comment] 2020-12-13 12:31
Duplicate of issue #321

**Closed by ansgarbecker** 2020-12-13 12:31 UTC
Labels: nettype-postgresql
