### ISSUE TITLE
Access violation when pressing escape in data-editors

### ISSUE THREAD

**Issue by NLSurfMan** [HeidiSQL/HeidiSQL#1564] opened 2022-04-12 12:36 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6447 (32 Bit)
* Database type and version: mysql  Ver 15.1 Distrib 10.6.4-MariaDB, for Win64 (AMD64), source revision 2db692f5b4d6bb31a331dab44544171c455f6aca
* OS: Windows 11 (21H2, build 22000.556)

**Describe the bug**

When pressing escape in a textfield in your data, there is a Access Violation logged:
````
/* #63: Access violation at address 00502283 in module 'heidisql.exe'. Read of address 00000000 Message CharCode:27 Msg:256 */
/* #50: Access violation at address 00502283 in module 'heidisql.exe'. Read of address 00000000 Message CharCode:27 Msg:256 */
/* #6488129: Access violation at address 0001001D. Write of address 004B6198 Message CharCode:27 Msg:256 */
/* #12: Access violation at address 0001001D. Write of address 004B6198 Message CharCode:27 Msg:256 */
/* #6488129: Access violation at address 0001001D. Write of address 004B6198 Message CharCode:27 Msg:256 */
````
This happens for textfields for any type of data. Dropdowns (columns with a foreign key) also show this behaviour.

The application remains usable.

**To Reproduce**
1. Open a table that has data in it
2. Double click on any value of a field to start the inline-editor
3. Press `escape` to cancel editing and close the editor
4. Note the Access Violation error in the status window.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/5594197/162963625-68060f4c-43de-40a8-a711-0a90584bf8b7.png)

**Comment by ansgarbecker** [comment] 2022-04-15 07:14
Duplicate of #1353

**Closed by ansgarbecker** 2022-04-15 07:14 UTC
