### ISSUE TITLE
Allow multiple fields selected on autocomplete field popup

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1446] opened 2021-09-20 13:30 UTC
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
When filling out the `SELECT` part of a query, I would like to be allowed to select multiple fields in the little popup that shows after I type:
```
tablename.
````
So it would be at this stage:

![image](https://user-images.githubusercontent.com/1086401/134010088-be6f4488-a201-4714-9381-f7c9940f3054.png)

So in that example, if I would be allowed to immediately select multiple fields HeidiSQL would then just do something like:

```
SELECT
	sync_message_order.creationdate, sync_message_order.modificationdate,
	sync_message_order.requestparameter, sync_message_order.requestendpoint,
	sync_message_order.requestverbe, sync_message_order.send_state
...
```
In this example I have selected fields:
```
creationdate
modificationdate
requestparameter
requestendpoint
requestverbe
send_state
```

**Describe alternatives you've considered**
I have to select each field one by one.

**Comment by lukinhaspm** [comment] 2021-09-20 15:52
a option "check all" will be great... not *, put all names

**Comment by AntonioCS** [comment] 2021-09-20 16:36
@lukinhaspm for all you can just use `*`. I was in a situation where I wanted like 5 or 6 fields and if I could select all of them from the list it would have made my life a lot easier :)

**Comment by lukinhaspm** [comment] 2021-09-20 17:15
@AntonioCS in some cases you needs to do some adjusts and standarize the statment... this way, you needs to select one by one... that's why I suggested an ALL but bring it by name

**Comment by AntonioCS** [comment] 2021-09-20 17:35
@lukinhaspm good point.

**Comment by ansgarbecker** [comment] 2022-04-13 05:05
Duplicate of #1029

**Closed by ansgarbecker** 2022-04-13 05:05 UTC
