### ISSUE TITLE
Crash after click on trigger in MSSQL

### ISSUE THREAD

**Issue by bcludek** [HeidiSQL/HeidiSQL#69] opened 2018-01-03 07:07 UTC
## Expected behavior

I expect that at after clicking on trigger name its properties are displayed

## Current behavior

I have created connection to the MSSQL 2016 database (but the problem was also at version 2012). In datbase explorer it is possible to click on entity nodes and properties are displayed on right side. But when I click on any trigger name the program crashes. See the attached generated bug report and screenshot.

## Failure information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Open connection to the MSSQL database.
2. Unpack any database containing trigger in database explorer
3. Click on trigger name

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5.0.5196
* Database system + version: MSSQL 2016 Express
* Operating system: Windows 10 Pro

### Failure Logs

Please include any relevant log snippets or files here.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1599609/bugreport.txt)
![clipboard01](https://user-images.githubusercontent.com/35057774/34511588-20475746-f05d-11e7-893d-f480d41d3e07.jpg)

**Comment by ansgarbecker** [comment] 2018-01-03 08:23
> Incorrect syntax near the keyword 'FROM'

The trigger editor is not yet capable of editing MSSQL triggers. Making it compatible to MSSQL requires some documentation on triggers.

**Comment by ilpssun** [comment] 2018-02-26 18:47
FYI: This is a duplicate of #42

**Comment by ansgarbecker** [comment] 2018-02-28 16:39
Correct. Closing this one.

**Closed by ansgarbecker** 2018-02-28 16:39 UTC
Labels: bug, mssql
