### ISSUE TITLE
Crash report window - UI problem with style theme Windows 10 Dark

### ISSUE THREAD

**Issue by Yousha** [HeidiSQL/HeidiSQL#1009] opened 2020-04-27 08:13 UTC
![Untitled](https://user-images.githubusercontent.com/18091267/80348748-8152c500-8883-11ea-9021-d6f2916a16f1.png)

## Steps to reproduce this issue

1. Step 1; Open HeidiSQL.exe
2. Step 2; Go to Tools menu -> Preferences item
3. Step 3; Click on General tab -> change Style theme to **Windows 10 Dark**
4. Then try to crash application.

## Current behavior

UI problem with colors.

## Environment

* **HeidiSQL version:** 11.0.0.5919 64bit - Windows 10 Dark theme
* **Database system and version:** 
  
* **Operating system:**  Windows 10 Pro 64bit

**Comment by ansgarbecker** [comment] 2020-04-27 12:43
Duplicate of #994

**Closed by ansgarbecker** 2020-04-27 12:43 UTC
Labels: themes
