### ISSUE TITLE
dump database cpu usage

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#345] opened 2018-09-06 14:43 UTC
## Steps to reproduce this issue

1. Select a big database
2. Export as SQL
3. watch cpu usage and dumping speed
4. wait as it's super long

## Current behavior

High cpu usage, low throughput

## Expected behavior

less CPU usage, more throughput

## Possible solution

less GUI updates, maybe once per second instead of realtime

## Environment

* **HeidiSQL version:** 
9.4.0.5125

**Comment by sirber** [comment] 2018-09-06 14:44
by commandline, on the server: 
mysqldump -uroot -p datamart loyalty_points > loyalty_points_uatprod.sql

the table is TokuDB, 1.8 GB, 16m rows, takes less than 1 minute.

**Comment by ansgarbecker** [comment] 2018-09-06 17:57
Duplicate of #343

**Closed by ansgarbecker** 2018-09-06 17:57 UTC
