### ISSUE TITLE
Invalid SQL code: unique index on create table in PostgreSQL

### ISSUE THREAD

**Issue by gmelodie** [HeidiSQL/HeidiSQL#321] opened 2018-07-28 23:02 UTC
## Steps to reproduce this issue

1. Create a new connection with a PostgreSQL database. 
2. At the chosen database, create a new table and add a couple of columns (I'm using 3).
3. Create a new index for any of the columns you created on your table.
4. Click **Save**.
5. An error message box with the following text should appear:

>  **ERROR:** syntax error at or near at "INDEX"
>  **LINE line_of_error:**  UNIQUE INDEX "your_index_name"("your_column_name")

## Current behavior

The following error is displayed on screen.

![error_heidisql](https://user-images.githubusercontent.com/8129788/43361205-55cd6dbc-929f-11e8-8426-04f5c7634407.png)

And the resulting SQL code is (in my example):

```
CREATE TABLE "table_name" (
    "column_1" BIGINT NOT NULL,
    "column_2" TIMESTAMP NOT NULL,
    "symbol" VARCHAR NOT NULL,
    PRIMARY KEY ("column_1"),
    UNIQUE INDEX "symbol" ("symbol")
);
```

## Expected behavior

The table is correctly created with indexes. And the code should be (for the same example as above):

```
CREATE TABLE "table_name" (
    "column_1" BIGINT NOT NULL,
    "column_2" TIMESTAMP NOT NULL,
    "symbol" VARCHAR NOT NULL,
    PRIMARY KEY ("column_1"),
    UNIQUE "symbol" ("symbol")
);
```

OR

```
CREATE TABLE "table_name" (
    "column_1" BIGINT NOT NULL,
    "column_2" TIMESTAMP NOT NULL,
    "symbol" VARCHAR NOT NULL UNIQUE,
    PRIMARY KEY ("column_1")
);
```

## Possible solution

There is an SQL syntax error on the generated code. Perhaps the code that generates the CREATE TABLE for PostgreSQL should be looked into.

## Environment

* **HeidiSQL version:** 9.5.0.5282

* **Database system and version:**  PostgreSQL 9.6.9

**Comment by hvamelsvoort** [comment] 2019-11-27 10:49
Same problem but also in 10.2.0.5599

**Comment by ansgarbecker** [comment] 2019-11-27 20:51
Related to #595 which I solved recently.

**Comment by halmai** [comment] 2020-01-25 15:21
I have a very similar problem with a quite recent version of heidisql: 
Version 10.3.0.5837 (64 Bit)

I get an error message when I want to add a new UNIQUE index to an _existing_ table. The problem is that HeidiSQL uses an `ALTER TABLE` syntax which is not the way how a UNIQUE index is added to a table. `CREATE INDEX` should be used instead.

**Comment by prunusnira** [comment] 2020-01-30 02:10
It creates query:

ALTER TABLE "table_name" ADD UNIQUE INDEX "column" ("column");

but it should be like:

ALTER TABLE "table_name" ADD UNIQUE ("column");

**Comment by halmai** [comment] 2020-04-13 10:04
> but it should be like:
> 
> ALTER TABLE "table_name" ADD UNIQUE ("column");

I am not sure this syntax works on older versions. It clearly does according to the https://www.postgresql.org/docs/12/sql-altertable.html and according to my tests on version 11.6. But according to the specs for older versions: https://www.postgresql.org/docs/9.1/sql-altertable.html, it does not create the index, it must already exist:

```
This form adds a new PRIMARY KEY or UNIQUE constraint to a table based on an existing unique index.
```

This code is more version proof, I think, but it needs an index name: 
```
CREATE UNIQUE INDEX <index_name> ON <table_name> (<field_list>);
```

**Comment by ansgarbecker** [comment] 2024-04-16 18:16
Should be fixed in the next build.

**Closed by ansgarbecker** 2024-04-16 18:16 UTC
Labels: bug, nettype-postgresql

**Comment by kolty17** [comment] 2024-09-19 04:44
As of 12.8 the error is still there.
Looking at the query it reflects the expected behavior writing `UNIQUE "symbol" ("symbol")`, it still result in a syntax error tough.
I solved replacing the statament with `UNIQUE ("symbol")` in the query.

**Comment by ansgarbecker** [comment] 2024-09-19 05:03
Indeed, my fix from ee3aaf86458c3db0017c200d6ae67e86205b5a01 still mentioned the name of the index. Now fixed in the next build.
