### ISSUE TITLE
Text Editor on Blob Field show not all information/data of the field

### ISSUE THREAD

**Issue by nicokaiser79** [HeidiSQL/HeidiSQL#1434] opened 2021-08-25 06:55 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (64 Bit)
* Database type and version: 10.2.32-MariaDB
* OS: CentOS 7.8.2003

**Describe the bug**

The Text Editor in HeidiSQL will not shown all data of a blob-field. The editor will show 14 chars only of more the 1000 chars data length.

**To Reproduce**

1. Create a Table with a Blob Field
2. Store Information in the Blob Field with PHP e.g. serialized PHP Object with a etc.
3. Got To Table in HeidiSql
4. Click Tab "DATA"
5. Go with Mouse over the Blob Field the Tool Tip show a long Information
6. Click in one Field and Click on the '...' to Open the Text Editor
7. The Text Editor show a minimum of the Data only 42 chars of 1602 chars in the exemple
![price_obj__with_length](https://user-images.githubusercontent.com/5329135/130740776-b2965798-1324-4134-9c5c-60619cdc8f3b.png)

https://user-images.githubusercontent.com/5329135/130740475-79861050-ba4c-451c-9d07-4b6e5d1d1e53.mp4

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment] 2021-08-25 07:01
Duplicate of #202

**Closed by ansgarbecker** 2021-08-25 07:01 UTC
