### ISSUE TITLE
Part of the session manager dialog box cannot be displayed and cannot be customized

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#718] opened 2019-07-17 00:58 UTC
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Current behavior

Some of the content is not displayed, but the point is that the current version does not save data after manually zooming in on the dialog. When you start the software again, it reverts to this.

![image](https://user-images.githubusercontent.com/2449459/61339222-5c024680-a86f-11e9-9ac1-c62ff93a88fc.png)

## Expected behavior

Save the user-defined layout of the dialog box or make sure everything is displayed properly.

## Possible solution

As before, after the user has customized the layout, save the relevant data until the default Settings are restored or the dialog layout is customized again.

## Environment

* **HeidiSQL version:** 
10.2.0.5631
* **Operating system:** 
win10, 4k screen

**Comment by ansgarbecker** [comment] 2019-07-17 05:21
I have a screen set to 175% DPI and cannot reproduce that with the latest build. Previous builds saved too high dimensions, which is what I fixed in 4f9613b05c63b9048d0d90908826af6db478c31a, or at least that was an attempt, which worked for me.

If you exit HeidiSQL, and then reopen it, is the session manager still at its smaller size?
Also, did you move HeidiSQL between that screen and another screen with a different DPI setting?

**Comment by id0612** [comment] 2019-07-17 05:37
No, I just tried to move between 4K and 2K.  (Display zoom scale: 4K 250%, 2K 125%)


Before 4K to 2k move:
![image](https://user-images.githubusercontent.com/2449459/61349658-6fc1a300-a897-11e9-897d-e9dbd79d553b.png)


After moving:
![image](https://user-images.githubusercontent.com/2449459/61349660-751eed80-a897-11e9-9faa-b63afb35a1bd.png)


Move to 4K again:
![image](https://user-images.githubusercontent.com/2449459/61349669-810aaf80-a897-11e9-91c9-ebb83a9e9969.png)


If I open it in 2K and then move to 4K.

The first is this:
![image](https://user-images.githubusercontent.com/2449459/61349745-bfa06a00-a897-11e9-8cdc-38bb33ca40a1.png)

Now, moving to 4K looks like this, and there are some positions that are different from opening at 4K.

![image](https://user-images.githubusercontent.com/2449459/61349762-d050e000-a897-11e9-97c2-3e71cff78e8e.png)

Let's move to 2K again

![image](https://user-images.githubusercontent.com/2449459/61349780-e199ec80-a897-11e9-9e55-67c704790725.png)

**Comment by ansgarbecker** [comment] 2019-07-17 05:50
Ok, I could somehow reproduce that once, but then not again. This dpi stuff drives me crazy, it's a mess.

Did you set a custom font size in HeidiSQL's Preferences: General > "GUI font"?

**Comment by id0612** [comment] 2019-07-17 05:53
No, the operating system and software are all default Settings, no third party themes and custom Settings.

**Comment by id0612** [comment] 2019-07-17 05:56
The session manager's inability to store user-defined layouts is a problem that has only been present in recent releases and has not existed before. The problem of showing proportions has always been there, but it's not very important. Usually just one screen.

**Comment by id0612** [comment] 2019-07-17 06:37
After connecting a database, enter the database management interface. If you drag between screens like the one above, it crashes directly.

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3400457/bugreport.txt)

**Comment by id0612** [comment] 2019-07-18 00:48
Oh my god, it got really bad after today's update. Restoring the default Settings failed to resolve the problem.
![image](https://user-images.githubusercontent.com/2449459/61421197-94218c00-a938-11e9-8882-3e68c1308a80.png)
![image](https://user-images.githubusercontent.com/2449459/61421206-9ab00380-a938-11e9-89c4-02dcc97ad0f0.png)
![image](https://user-images.githubusercontent.com/2449459/61421215-a996b600-a938-11e9-92a0-a558eac60207.png)
![image](https://user-images.githubusercontent.com/2449459/61421231-bd421c80-a938-11e9-93e7-9691a776a641.png)



When I tried to modify the language, when I saved it, it could not complete, and there was no response.

![image](https://user-images.githubusercontent.com/2449459/61421151-676d7480-a938-11e9-9eac-2018970449d2.png)

**Comment by id0612** [comment] 2019-07-18 00:50
In 10.2.0.5634

**Comment by ansgarbecker** [comment] 2019-07-18 05:57
Is your screen really running on 250% DPI? I have one with 175% and it looks like this:
![grafik](https://user-images.githubusercontent.com/7986591/61431077-89f99080-a92c-11e9-9b5c-b0e5036147b8.png)

I also see your "GUI font" setting is still on "Default system font", so I'm scratching my head why the font gets so huge. My change from yesterday just scales the font according to the current screen's DPI setting, so if the default size is 9pt, my one gets multiplied by 1.75, then rounded to 16pt. You said your 4k screen runs on 250%, which should result in a font size of 23pt. But it looks like 50pt or even higher.

I assume the font size is scaled by my code first, then a second time by Windows when the window internally gets moved to the previous screen. So this is a multi-monitor-with-different-dpi issue. I just wonder why I did not encounter that issue, as I have a similar setup. Well, I just pushed another change which scales the fonts later, when the form is already on the wanted screen. So it does not matter what Windows scales first, I am overwriting that font size then.

Please update and check again.
And thanks for testing! :)

**Comment by id0612** [comment] 2019-07-18 05:59
Yes, 250% DPI, 4k

**Comment by ansgarbecker** [comment] 2019-07-18 19:03
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.

**Closed by ansgarbecker** 2019-07-18 19:03 UTC
Labels: bug, high-dpi, needs-info

**Comment by id0612** [comment] 2019-07-19 01:54
OK, that's better. In 4K resolution, the session manager and Settings interface is very large, covering the entire screen except for the first boot.

![image](https://user-images.githubusercontent.com/2449459/61501773-65bcb300-aa03-11e9-8c6e-a4dc5e9ca619.png)

![image](https://user-images.githubusercontent.com/2449459/61501869-d794fc80-aa03-11e9-9b36-18009252c0d1.png)

But luckily I can scale it manually. And then it looks like this, and I think it's done. While the details of the font don't look as perfect as they used to, it's pretty good and doesn't hurt.
![image](https://user-images.githubusercontent.com/2449459/61503478-7886b600-aa0a-11e9-90bd-419b28663660.png)
![image](https://user-images.githubusercontent.com/2449459/61503487-7d4b6a00-aa0a-11e9-9465-19d36f00406e.png)
![image](https://user-images.githubusercontent.com/2449459/61503493-82a8b480-aa0a-11e9-8424-d5b9b058153d.png)
![image](https://user-images.githubusercontent.com/2449459/61503517-994f0b80-aa0a-11e9-9762-be8e29ec8a0e.png)
![image](https://user-images.githubusercontent.com/2449459/61503550-b4218000-aa0a-11e9-823f-5d2686283180.png)

**Comment by id0612** [comment] 2019-07-19 02:03
That's it. It's good enough. In my opinion, the priority of 4K screen adaptation is not high. Although the display effect is not very good, its performance in 4K screen has exceeded many software, and it does not affect the use. You are advised to focus on other issues that may affect your use.
