### ISSUE TITLE
Case sensitive database names filtered away with databases filter

### ISSUE THREAD

**Issue by vrs-webmaster** [HeidiSQL/HeidiSQL#705] opened 2019-07-05 22:58 UTC
## Steps to reproduce this issue

1. Step 1; Open session
2. Then I get a database list only containing databases with unique names regardles of uper or lower case letters.

## Current behavior

The database list shows only databases where the last letter is an upercase letter when there is also a database where the last letter is a small letter.
The database names on our web server have a first part that is always the same. They can then have 0-9, A-Z, a-z and a number of special characters as last characters.
Example: If there are two databases with the names xxxxxxxx_E and xxxxxxxx_e, only the database with E is shown in the list.

## Expected behavior

All databases should be listed in the same way as in phpMyAdmin. Thus also those with names with uper- and lowercase name end.

## Possible solution

I have no clue.

## Environment

MySQL recently updated from 5.5.3 to 10.2.19-MariaDB.
The same "error" also occurred in the previous version.

* **HeidiSQL version:** 
  10.2.0.5599 (64 Bit).
* **Database system and version:** 
  MySQL 10.2.19-MariaDB.
* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment] 2019-07-06 12:57
Is that MariaDB server running on a Windows or a Linux system? Windows may not support different case writings in databases as these are actually folder in the filesystem, which is case insensitive on Windows. On Linux most filesystems are case sensitive, so it may make a difference here.

My own test on a Linux / MariaDB 10.3 shows two databases: `abc` and `abC`. Also after a reconnect these are both displayed.

**Comment by vrs-webmaster** [comment] 2019-07-07 10:00
It is running on a Linux system.

MySQL Workbench also show all the databases, both the xxxxxx_E and xxxxx_e types.

**Comment by ansgarbecker** [comment] 2019-07-07 13:41
For some reason I cannot reproduce that here. Look at the screenshot:

![grafik](https://user-images.githubusercontent.com/7986591/60769206-35a11600-a0cd-11e9-87b2-dfd13ba6122c.png)

Please update to the latest build and check again.

And please also post the version number and filename of your libmariadb.dll/libmysql.dll, after hovering over the status bar version panel:
![grafik](https://user-images.githubusercontent.com/7986591/60769250-99c3da00-a0cd-11e9-88ae-3799ec0a61db.png)

**Comment by vrs-webmaster** [comment] 2019-07-07 18:05
I've upsated to 10.2.0.5631
No changes in the db list.

This is the information in HedieSQL
![image](https://user-images.githubusercontent.com/52584918/60772136-3ef0a980-a0f2-11e9-9bbe-2728dac2e084.png)

// VRS webmaster

**Comment by vrs-webmaster** [comment] 2019-07-07 18:09
I also installed HeidieSQL on my laptop (also Win 10) vith the same issue.

// VRS webmaster

**Comment by ansgarbecker** [comment] 2019-07-07 18:49
Could it be you are making use of the "Database(s)" list in the sesion setup?

**Comment by vrs-webmaster** [comment] 2019-07-07 19:12
It's the same in boath lists.
![image](https://user-images.githubusercontent.com/52584918/60772809-cdb5f400-a0fb-11e9-8128-7ccd2fc4d572.png)

**Comment by vrs-webmaster** [comment] 2019-07-07 19:15
There should be a vulcanri_a, vulcanri_b, vulcanri_c, vulcanri_d and vulcanri_e database too

**Comment by ansgarbecker** [comment] 2019-07-07 19:24
I meant the "Database(s)" _setting_:

![grafik](https://user-images.githubusercontent.com/7986591/60772934-829ce080-a0fd-11e9-9118-dddfe314a058.png)

**Comment by vrs-webmaster** [comment] 2019-07-07 19:43
Yes that was the problem.
I deleted the incorrect list, unchecked the Compressed.. checkbox and rechecked it. Then I got the text "Separated…" insted of the incorect list.
Now I have all our databases in the list. Nice!
I don't know how the list were created in the first Place but now it's no longer there.

Thank you so much!
// VRS webmaster

**Comment by ansgarbecker** [comment] 2019-07-08 04:28
Ok, but then the databases filter is working incorrectly, and should be fixed. You should be able to use that filter with your database names.

**Comment by ansgarbecker** [comment] 2019-08-12 07:33
In the end it was a wrong expectation here - the databases filter in the session setup prevents the user from having to call a probably unsupported `SHOW DATABASES`. If there is a database `test_a` and one called `test_A`, then the filter just has to contain both (at least if you want to see both).

**Closed by ansgarbecker** 2019-08-12 07:33 UTC
Labels: bug, confirmed
