### ISSUE TITLE
Binary editor with "Hex" view mode consistently causes an exception when closed

### ISSUE THREAD

**Issue by SaSiNO97** [HeidiSQL/HeidiSQL#1505] opened 2021-12-28 22:46 UTC
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: 10.4.21-MariaDB
* OS: Microsoft Windows [Version 10.0.19042.1288]

**Describe the bug**

An error popup appears every time I edit any binary field. Clicking "continue" fortunately doesn't cause any other issue, but the popup is annoying.

**To Reproduce**

Open and close a "binary editor" with the view type set to HEX
![image](https://user-images.githubusercontent.com/17410173/147612470-365df9a2-14cc-4835-bb21-5d43b5597623.png)
![image](https://user-images.githubusercontent.com/17410173/147612488-0b686447-883d-42b2-8edb-2fe1a5c1c9c8.png)

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/17410173/147612447-9f42890a-bcf9-4605-ab21-83d1603b2019.png)
![image](https://user-images.githubusercontent.com/17410173/147612453-ca0937ad-2ca0-4691-b0c8-6ee4957a5e66.png)

**Comment by ansgarbecker** [comment] 2022-04-15 07:18
Duplicate of #1349

**Closed by ansgarbecker** 2022-04-15 07:18 UTC
